---
permalink: sg6000/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: ハードウェア障害やケーブル接続エラーによってストレージコントローラまたは SG6000-CN コントローラのブート処理が完了しなかった場合は、 StorageGRID アプライアンスインストーラを使用できなくなることがあります。 
---
= ハードウェアのセットアップがハングしたように見えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェア障害やケーブル接続エラーによってストレージコントローラまたは SG6000-CN コントローラのブート処理が完了しなかった場合は、 StorageGRID アプライアンスインストーラを使用できなくなることがあります。

.手順
. ストレージコントローラの場合は、デジタル表示ディスプレイのコードを監視します。
+
電源投入時にハードウェアが初期化される際に、 2 つのデジタル表示ディスプレイに一連のコードが表示されます。ハードウェアが正常にブートすると、デジタル表示ディスプレイが両方に表示されます `99`。

. SG6000-CN コントローラの LED と、 BMC に表示されたブート時のコードとエラーコードを確認します。
. 問題 の解決にサポートが必要な場合は、テクニカルサポートにお問い合わせください。


.関連情報
link:viewing-boot-up-status-codes-for-sg6000-storage-controllers.html["SG6000ストレージコントローラのブート時のステータスコードを確認する"]

https://["E5700 and E2800 System Monitoring Guide"^]

link:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.html["SG6000-CNコントローラのステータスインジケータとボタンの表示"]

link:viewing-boot-up-codes-for-sg6000-cn-controller.html["SG6000-CNコントローラのブート時のコードを確認する"]

link:viewing-error-codes-for-sg6000-cn-controller.html["SG6000-CNコントローラのエラーコードの確認"]
