---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, CBSE, CBRE, SCMT, SREM 
summary: オブジェクトストレージ監査カテゴリに属する監査メッセージについて十分に理解しておく必要があります。StorageGRID システム内のオブジェクトのストレージと管理に関連するイベントを示します。オブジェクトの格納と読み出し、グリッドノードからグリッドノードへの転送、および検証が含まれます。 
---
= オブジェクトストレージ監査メッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトストレージ監査カテゴリに属する監査メッセージについて十分に理解しておく必要があります。StorageGRID システム内のオブジェクトのストレージと管理に関連するイベントを示します。オブジェクトの格納と読み出し、グリッドノードからグリッドノードへの転送、および検証が含まれます。

|===
| コード | 説明 | を参照してください 


 a| 
APCT
 a| 
Archive Purge from Cloud-Tier ： S3 API を使用して StorageGRID に接続する外部アーカイブストレージシステムから、アーカイブされたオブジェクトデータが削除されました。
 a| 
link:apct-archive-purge-from-cloud-tier.html["APCT ：クラウド階層からのアーカイブの削除"]



 a| 
ARCB
 a| 
Archive Object Retrieve Begin ： ARC サービスが、外部アーカイブストレージシステムからオブジェクトデータの読み出しを開始しました。
 a| 
link:arcb-archive-object-retrieve-begin.html["ARCB ：アーカイブオブジェクトの読み出しが開始されました"]



 a| 
ARCE
 a| 
Archive Object Retrieve End ：オブジェクトデータが外部アーカイブストレージシステムから読み出され、 ARC サービスが読み出し処理のステータスをレポートします。
 a| 
link:arce-archive-object-retrieve-end.html["ARCE ：アーカイブオブジェクトの読み出しが終了しました"]



 a| 
ARCT
 a| 
Archive Retrieve from Cloud-Tier ： S3 API を使用して StorageGRID に接続する外部アーカイブストレージシステムから、アーカイブされたオブジェクトデータが読み出されました。
 a| 
link:arct-archive-retrieve-from-cloud-tier.html["ARCT ：クラウド階層からアーカイブを取得します"]



 a| 
AREM
 a| 
Archive Object Remove ：外部アーカイブストレージシステムからのコンテンツブロックの削除が成功または失敗しました。
 a| 
link:arem-archive-object-remove.html["AREM ：アーカイブオブジェクトの削除"]



 a| 
ASCE
 a| 
Archive Object Store End ：コンテンツブロックが外部アーカイブストレージシステムに書き込まれ、 ARC サービスが書き込み処理のステータスをレポートします。
 a| 
link:asce-archive-object-store-end.html["ASCE ：アーカイブオブジェクトストアの終了"]



 a| 
▽ SCT 。△
 a| 
Archive Store Cloud-Tier ： S3 API を使用して StorageGRID に接続する外部アーカイブストレージシステムに、オブジェクトデータが格納されました。
 a| 
link:asct-archive-store-cloud-tier.html["ASCT ：アーカイブストアのクラウド階層"]



 a| 
ATCE
 a| 
Archive Object Store Begin ：外部アーカイブストレージへのコンテンツブロックの書き込みが開始されました。
 a| 
link:atce-archive-object-store-begin.html["ATCE ：アーカイブオブジェクトストアが開始されました"]



 a| 
AVCC の場合
 a| 
Archive Validate Cloud-Tier Configuration ：指定されたアカウントおよびバケットの設定の検証に成功または失敗しました。
 a| 
link:avcc-archive-validate-cloud-tier-configuration.html["AVCC ：アーカイブによってクラウド階層の構成を検証"]



 a| 
CBSE
 a| 
Object Send End ：ソースエンティティが、グリッドノードからグリッドノードへのデータ転送処理を完了しました。
 a| 
link:cbse-object-send-end.html["CBSE ：オブジェクト送信終了"]



 a| 
CBRE
 a| 
Object Receive End ：デスティネーションエンティティが、グリッドノードからグリッドノードへのデータ転送処理を完了しました。
 a| 
link:cbre-object-receive-end.html["CBRE ：オブジェクト受信終了"]



 a| 
SCMT
 a| 
Object Store Commit ：コンテンツブロックの格納と検証がすべて完了し、要求可能な状態になりました。
 a| 
link:scmt-object-store-commit.html["SCMT ：オブジェクトストアのコミット"]



 a| 
SREM
 a| 
Object Store Remove ：コンテンツブロックがグリッドノードから削除され、直接要求できなくなりました。
 a| 
link:srem-object-store-remove.html["SREM ：オブジェクトストアの削除"]

|===