---
settings:
  name: StorageGRID 11.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - name: StorageGRID
    url: "/storagegrid-115"
    version-number: '11.5'
  - name: StorageGRID
    url: "/storagegrid-116"
    version-number: '11.6'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63374&language=en-US
    version-number: '11.4'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023&archive=true
    version-number: '11.3'
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.5のドキュメント
    url: "/index.html"
  - section: release-notes
  - title: はじめに
    entries:
    - section: primer
    - section: network
  - title: ソフトウェアをインストールしてアップグレードする
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: ハードウェアを設置して保守する
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: 構成と管理
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: StorageGRID を使用します
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 監視とトラブルシューティング
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: メンテナンス
    entries:
    - section: expand
    - section: maintain
  - title: 以前のバージョン
    url: "/earlier-versions.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: リリースノート
      url: "/release-notes/index.html"
    - title: 新機能
      url: "/upgrade/whats-new.html"
    - title: StorageGRID の詳細をご覧ください
      url: "/primer/index.html"
    - title: ネットワークのガイドライン
      url: "/network/index.html"
  - title: ハードウェアのメンテナンスをインストールします
    links:
    - title: SG6000 ストレージアプライアンス
      url: "/sg6000/index.html"
    - title: SG5700 ストレージアプライアンス
      url: "/sg5700/index.html"
    - title: SG5600 ストレージアプライアンス
      url: "/sg5600/index.html"
    - title: SG100 および SG1000 サービスアプライアンス
      url: "/sg100-1000/index.html"
  - title: アップグレードソフトウェアをインストールします
    links:
    - title: Red Hat Enterprise Linux または CentOS をインストールします
      url: "/rhel/index.html"
    - title: Ubuntu または Debian をインストールします
      url: "/ubuntu/index.html"
    - title: VMware をインストールする
      url: "/vmware/index.html"
    - title: ソフトウェアをアップグレードする
      url: "/upgrade/index.html"
  - title: グリッドを設定します
    links:
    - title: StorageGRID の管理
      url: "/admin/index.html"
    - title: ILM を使用してオブジェクトを管理する
      url: "/ilm/index.html"
    - title: システムの保護対策
      url: "/harden/index.html"
    - title: StorageGRID for FabricPool を設定します
      url: "/fabricpool/index.html"
  - title: オブジェクトを管理します
    links:
    - title: テナントアカウントを使用する
      url: "/tenant/index.html"
    - title: S3 REST APIを使用する
      url: "/s3/index.html"
    - title: Swift REST APIを使用する
      url: "/swift/index.html"
  - title: 監視とメンテナンス
    links:
    - title: モニタ
      url: "/monitor/index.html"
    - title: トラブルシューティングを行う
      url: "/troubleshoot/troubleshooting-storagegrid-system.html"
    - title: 監査ログを確認します
      url: "/audit/index.html"
    - title: グリッドを展開します
      url: "/expand/index.html"
    - title: リカバリとメンテナンス
      url: "/maintain/index.html"
  - title: デモチュートリアル
    links:
    - title: StorageGRID を有効にする方法について説明します
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: StorageGRID ビデオライブラリ
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: ネットアップラーニングサービス
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: リソースの追加
    links:
    - title: StorageGRID のサポートページ
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: ネットアップの Interoperability Matrix Tool （ IMT ）
      url: https://imt.netapp.com/matrix/#welcome
    - title: StorageGRID ナレッジベース
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: ネットアップのブログ
      url: https://netapp.com/blog/
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/
  - title: 以前のバージョン
    links:
    - title: StorageGRID 11.4 ドキュメント
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: StorageGRID 11.3 のドキュメント
      url: https://docs.netapp.com/sgws-113/index.jsp
