---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, firewall, ports 
summary: StorageGRID システムをアップグレードする前に、システムがアップグレードできる状態にあることを確認する必要があります。システムが正常に稼働し、すべてのグリッドノードが動作している必要があります。 
---
= ソフトウェアをアップグレードする前に、システムの状態を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムをアップグレードする前に、システムがアップグレードできる状態にあることを確認する必要があります。システムが正常に稼働し、すべてのグリッドノードが動作している必要があります。

.手順
. サポートされているブラウザを使用してGrid Managerにサインインします。
. アクティブなアラートがないかを確認し、ある場合は解決します。
+
特定のアラートの詳細については、監視とトラブルシューティングの手順を参照してください。

. 競合するグリッドタスクがアクティブまたは保留中でないことを確認します。
+
.. Support *>* Tools *>* Grid Topology *を選択します。
.. _site * > * _primary Admin Node_* > * CMN * > * Grid Tasks * > * Configuration * を選択します。
+
情報ライフサイクル管理評価（ ILME ）タスクは、ソフトウェアのアップグレードと同時に実行できる唯一のグリッドタスクです。

.. 他のグリッドタスクがアクティブまたは保留中の場合は、それらが終了するまで、またはロックが解放されるまで待ちます。
+

NOTE: タスクが終了しない、またはロックが解放されない場合は、テクニカルサポートにお問い合わせください。



. アップグレード前に、11.5バージョンのネットワークガイドラインで内部ポートと外部ポートのリストを参照し、必要なすべてのポートが開いていることを確認します。
+

IMPORTANT: カスタムのファイアウォールポートが開いている場合は、アップグレードの事前確認中に通知されます。アップグレードを続行する前に、テクニカルサポートに連絡する必要があります。



.関連情報
link:../monitor/index.html["トラブルシューティングを監視します"]

link:../admin/index.html["StorageGRID の管理"]

link:../maintain/index.html[""]

link:../network/index.html["ネットワークガイドライン"]
