---
permalink: upgrade/docker-image-availability-check-error-messages.html 
sidebar: sidebar 
keywords: upgrade, error message, docker image availability 
summary: アップグレードプロセスを開始しようとすると、「 The following issues were identified by the Docker image availability check validation suite 」というエラーメッセージが表示される場合があります。 アップグレードを完了する前に、すべての問題を解決しておく必要があります。 
---
= 「 Docker image availability check 」というエラーメッセージが表示される
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードプロセスを開始しようとすると、「 The following issues were identified by the Docker image availability check validation suite 」というエラーメッセージが表示される場合があります。 アップグレードを完了する前に、すべての問題を解決しておく必要があります。

見つかった問題の解決に必要な変更内容がわからない場合は、テクニカルサポートにお問い合わせください。

[cols="1a,1a,1a"]
|===
| メッセージ | 原因 | 解決策 


 a| 
アップグレードバージョンを特定できません。バージョン情報ファイルをアップグレードします `{file_path}` 想定される形式と一致しませんでした。
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
バージョン情報ファイルをアップグレードします `{file_path}` が見つかりませんでした。アップグレードバージョンを特定できません。
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
に現在インストールされているリリースバージョンを確認できません `{node_name}`。
 a| 
ノード上の重要なファイルが破損しています。
 a| 
テクニカルサポートにお問い合わせください。



 a| 
のバージョンを表示しようとしているときに接続エラーが発生しました `{node_name}`
 a| 
ノードがオフラインであるか、接続が中断されました。
 a| 
すべてのノードがオンラインで、プライマリ管理ノードからアクセスできることを確認して、操作をやり直します。



 a| 
ノードのホスト `{node_name}` にはStorageGRID がありません `{upgrade_version}` イメージがロードされましたアップグレードを続行するには、イメージとサービスがホストにインストールされている必要があります。
 a| 
ノードを実行しているホストにアップグレード用の RPM パッケージまたは DEB パッケージがインストールされていないか、イメージのインポートがまだ終了していません。

* 注：このエラーは、 Linux でコンテナとして実行されている環境 ノードのみに該当します。
 a| 
RPM パッケージまたは DEB パッケージが、ノードが実行されているすべての Linux ホストにインストールされていることを確認します。サービスとイメージファイルの両方について、バージョンが正しいことを確認します。数分待ってから再試行してください。

詳細については、使用しているLinuxプラットフォーム用のインストール手順を参照してください。



 a| 
ノードの確認中にエラーが発生しました `{node_name}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。



 a| 
事前確認の実行時に不明なエラーが発生する。 `{error_string}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。

|===
.関連情報
link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]

link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]
