---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: StorageGRID 11.5へのアップグレードを計画するときは、アップグレードにかかる時間に応じて、いつ実行するかを考慮する必要があります。また、アップグレードの各ステージ中に実行できる処理と実行できない処理についても把握しておく必要があります。 
---
= アップグレード所要時間の見積もり
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5へのアップグレードを計画するときは、アップグレードにかかる時間に応じて、いつ実行するかを考慮する必要があります。また、アップグレードの各ステージ中に実行できる処理と実行できない処理についても把握しておく必要があります。

.このタスクについて
StorageGRID のアップグレード完了までに必要な時間は、クライアントの負荷やハードウェアのパフォーマンスなどのさまざまな要因によって異なります。

次の表に、アップグレードの主なタスクをまとめ、各タスクに必要なおおよその時間を示します。表に続いて、システムのアップグレード時間を見積もる手順を記載します。


IMPORTANT: StorageGRID 11.4から11.5にアップグレードすると、ストレージノード上のCassandraデータベーステーブルがアップグレードされます。データベースのアップグレード*タスクはバックグラウンドで実行されますが、完了までにかなりの時間がかかることがあります。データベースのアップグレード中も、新しい機能の使用、ホットフィックスの適用、ノードのリカバリ処理を安全に実行できます。ただし、他のメンテナンス手順を実行できない場合があります。


NOTE: 拡張が緊急に必要な場合は、11.5にアップグレードする前に拡張を実行します。

[cols="1a,1a,1a,a"]
|===
| アップグレードタスク | 説明 | おおよその所要時間です | このタスクの実行中です 


 a| 
アップグレードサービスを開始します
 a| 
アップグレードの事前確認が実行され、ソフトウェアファイルが配布されて、アップグレードサービスが開始されます。
 a| 
検証エラーが報告されないかぎり、グリッドノードあたり 3 分
 a| 
必要に応じて、スケジュールされたアップグレードのメンテナンス時間の前に、アップグレードの事前確認を手動で実行できます。



 a| 
Grid ノード（プライマリ管理ノード）をアップグレード
 a| 
プライマリ管理ノードが停止されてアップグレードされ、再起動されます。
 a| 
最大30分
 a| 
プライマリ管理ノードにはアクセスできません。接続エラーが報告されますが、無視してかまいません。



 a| 
Grid ノード（他のすべてのノード）をアップグレード
 a| 
他のすべてのグリッドノードのソフトウェアが、ノードを承認した順序でアップグレードされます。システムの各ノードが一度に 1 つずつ数分間停止されます。
 a| 
ノードあたり15~45分、アプライアンスストレージノードで最も時間が必要です

* 注： * アプライアンスノードの場合、 StorageGRID アプライアンスインストーラは自動的に最新リリースに更新されます。
 a| 
* グリッド設定は変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM 設定を更新しないでください。
* ホットフィックス、運用停止、拡張など、別のメンテナンス手順 は実行しないでください。
+
*注：リカバリ手順 を実行する必要がある場合は、テクニカル・サポートにお問い合わせください。





 a| 
機能を有効にします
 a| 
新しいバージョンの新機能が有効になります。
 a| 
5 分未満
 a| 
* グリッド設定は変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM 設定を更新しないでください。
* 別のメンテナンス手順 は実行しないでください。




 a| 
データベースをアップグレードします
 a| 
すべてのストレージノードに存在するCassandraデータベーステーブルがアップグレードされている。
 a| 
システム内のメタデータの量に応じて、数時間から数日を指定します
 a| 
データベースのアップグレードタスク中は、アップグレード済みのグリッドは正常に動作しますが、アップグレードは進行中です。このタスクでは、次の操作を実行できます。

* 新しいStorageGRID バージョンの新機能を使用します。
* 監査レベル設定の変更
* ILM設定の更新
* ホットフィックスを適用します。
* ノードをリカバリ


*注：*最終アップグレード手順*が完了するまで、手順 の運用停止や拡張は実行できません。



 a| 
最終アップグレード手順
 a| 
一時ファイルが削除され、新しいリリースへのアップグレードが完了します。
 a| 
5 分
 a| 
[* 最終アップグレードステップ * ] タスクが完了すると、すべてのメンテナンス手順を実行できます。

|===
.手順
. すべてのグリッドノードのアップグレードに必要な推定時間を見積もります（データベースのアップグレード*を除くすべてのアップグレードタスクを考慮）。
+
.. StorageGRID システムのノード数に30分（平均）を掛けます。
.. この時間に1時間を追加して、をダウンロードするために必要な時間を考慮してください `.upgrade` ファイルを選択し、事前確認検証を実行して、最終アップグレード手順を完了します。


. Linux ノードがある場合は、 RPM パッケージまたは DEB パッケージをダウンロードしてインストールするために必要な時間として、各ノードに 15 分を追加します。
. データベースのアップグレードに必要な推定時間。
+
.. Grid Managerから* Nodes *を選択します。
.. ツリーの最初のエントリ（グリッド全体）を選択し、*ストレージ*タブを選択します。
.. 「* Storage Used - Object Metadata *」グラフにカーソルを合わせ、「Used *」の値を探します。これは、グリッド上にあるオブジェクトメタデータのバイト数を示します。
.. Used *値を1日あたり1.5TBで割り、データベースのアップグレードに必要な日数を決定します。


. 手順1、2、3の結果を追加して、アップグレードの合計推定時間を計算します。




== 例：StorageGRID 11.4から11.5へのアップグレード時間の見積もり

システムにグリッドノードが 14 個あり、そのうち 8 個が Linux ノードであるとします。また、オブジェクトメタデータの* used *の値が6TBであるとします。

. 14に30分を掛け、1時間を足します。すべてのノードのアップグレードにかかる推定時間は8時間です。
. LinuxノードにRPMパッケージまたはDEBパッケージをインストールする時間として、8~15分/ノードが複数必要です。この手順の推定時間は 2 時間です。
. 6を1.5 TB/日で割ります。データベースのアップグレード*タスクの推定日数は4日です。
+

NOTE: データベースのアップグレード*タスクの実行中は、新しい機能の使用、ホットフィックスの適用、ノードのリカバリ処理を安全に実行できます。

. 値をまとめて追加します。システムのStorageGRID 11.5.0へのアップグレードを完了するまでに5日かかります。

