---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。 
---
= アップグレード中にシステムが受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。



== StorageGRID のアップグレードは無停止で実行されます

StorageGRID システムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。アップグレード中に一度に 1 つずつグリッドノードが停止されるため、すべてのグリッドノードが使用できなくなることはありません。

継続的な可用性を確保するには、オブジェクトが適切な ILM ポリシーを使用して冗長に格納されていることを確認する必要があります。また、次のいずれかに要求を送信するようにすべての外部の S3 または Swift クライアントを設定する必要があります。

* ハイアベイラビリティ（ HA ）グループとして設定された StorageGRID エンドポイント
* 高可用性のサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== アプライアンスファームウェアがアップグレードされている

StorageGRID 11.5へのアップグレード中：

* すべてのStorageGRID アプライアンスノードは、StorageGRID アプライアンスインストーラファームウェアバージョン3.5に自動的にアップグレードされます。
* SG6060とSGF6024アプライアンスは、BIOSファームウェアバージョン3B03.EXおよびBMCファームウェアバージョンBMC 3.90.07に自動的にアップグレードされます。
* SG100およびSG1000アプライアンスは、自動的にBIOSファームウェアバージョン3B08.ECおよびBMCファームウェアバージョン4.64.07にアップグレードされます。




== アラートがトリガーされる可能性があります

アラートは、サービスの開始と停止、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）にトリガーされることがあります。たとえば、サービスが停止しているときに「ノードと通信できません」というアラートが表示されたり、一部のノードがStorageGRID 11.5にアップグレードされても、他のノードでStorageGRID 11.4が実行されているときに「Cassandra communication error *」アラートが表示されることがあります。

通常、これらのアラートはアップグレードが完了するとクリアされます。

アップグレードが完了したら、Grid Managerのダッシュボードで「Recently Resolved alerts」を選択して、アップグレード関連のアラートを確認できます。


NOTE: StorageGRID 11.5へのアップグレード中に、ストレージノードが停止したときに「ILM placement unAchievable *」アラートがトリガーされることがあります。このアラートは、アップグレードが正常に完了してから1日後も継続する場合があります。



== 多数の SNMP 通知が生成されます

アップグレード中にグリッドノードが停止および再起動されると、多数の SNMP 通知が生成される場合があります。過剰な通知を避けるには、[* SNMPエージェント通知を有効にする*]チェックボックス（* Configuration *>* Monitoring *>* SNMP Agent *）をオフにして、アップグレードを開始する前にSNMP通知を無効にします。その後、アップグレードの完了後に通知を再度有効にします。



== 設定の変更は制限されています

[ 新しい機能を有効にする *] タスクが完了するまで :

* グリッドの設定は変更しないでください。
* 監査レベルの設定は変更しないでください。
* 新しい機能を有効または無効にしないでください。
* ILM 設定を更新しないでください。ILM の動作が不安定になり、正常に動作しない場合があります。
* ホットフィックスの適用やグリッドノードのリカバリは行わないでください。


[* Final Upgrade Steps * （最終アップグレード手順 * ） ] タスクが完了するまで：

* 拡張手順 は実行しないでください。
* 手順 の運用停止は実行しないでください。

