---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, software upgrade 
summary: Software Upgradeページの指示に従って、必要なファイルをアップロードし、StorageGRID システム内のすべてのグリッドノードをアップグレードします。 
---
= アップグレードを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Software Upgradeページの指示に従って、必要なファイルをアップロードし、StorageGRID システム内のすべてのグリッドノードをアップグレードします。

.必要なもの
次の点に注意してください。

* Grid Managerを使用して、プライマリ管理ノードからすべてのデータセンターサイトのすべてのグリッドノードをアップグレードする必要があります。
* 問題を検出して解決するために、実際のアップグレードを開始する前にアップグレードの事前確認を手動で実行できます。アップグレードを開始した場合も、同じ事前確認が実行されます。事前確認が失敗すると、アップグレードプロセスが停止し、解決のためにテクニカルサポートの支援が必要になる場合があります。
* アップグレードを開始すると、プライマリ管理ノードが自動的にアップグレードされます。
* プライマリ管理ノードのアップグレードが完了したら、次にアップグレードするグリッドノードを選択できます。
* アップグレードを完了するには、StorageGRID システムですべてのグリッドノードをアップグレードする必要がありますが、個 々 のグリッドノードは任意の順序でアップグレードしてかまいません。個 々 のグリッドノード、グリッドノードのグループ、またはすべてのグリッドノードを選択できます。グリッドノードの選択プロセスを必要な回数だけ繰り返し、すべてのサイトのすべてのグリッドノードをアップグレードします。
* グリッドノードでアップグレードを開始すると、そのノードのサービスは停止します。グリッドノードはあとでリブートされます。グリッドノードを停止およびリブートして問題ないことを確認するまでは、そのノードのアップグレードを承認しないでください。
* すべてのグリッドノードがアップグレードされると、新しい機能が有効になり、運用を再開できます。ただし、バックグラウンドの*アップグレードデータベース*タスクおよび*最終アップグレード手順*タスクが完了するまでは、運用停止または拡張手順 の実行を待つ必要があります。
* アップグレードを開始したハイパーバイザープラットフォームでアップグレードを完了する必要があります。


.手順
. link:linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux：すべてのホストにRPMパッケージまたはDEBパッケージをインストールします"]
. link:starting-upgrade.html["アップグレードを開始する"]
. link:upgrading-grid-nodes-and-completing-upgrade.html["グリッドノードのアップグレードとアップグレードの完了"]
. link:increasing-metadata-reserved-space-setting.html["Metadata Reserved Space設定を拡張しています"]


.関連情報
link:../admin/index.html["StorageGRID の管理"]

link:estimating-time-to-complete-upgrade.html["アップグレード所要時間の見積もり"]
