---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: new features, 11.5, object lock, kmip, kms, ilm, decommission, node clone 
summary: StorageGRID 11.5では、S3オブジェクトロック、データのKMIP暗号化のサポート、ILMの操作性の向上、Tenant Managerユーザインターフェイスの再設計、StorageGRID サイトの運用停止のサポート、およびアプライアンスノードのクローン手順 が導入されています。 
---
= StorageGRID 11.5の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5では、S3オブジェクトロック、データのKMIP暗号化のサポート、ILMの操作性の向上、Tenant Managerユーザインターフェイスの再設計、StorageGRID サイトの運用停止のサポート、およびアプライアンスノードのクローン手順 が導入されています。



== S3オブジェクトロックで準拠データをロック

StorageGRID 11.5のS3オブジェクトロック機能は、Amazon Simple Storage Service（Amazon S3）のS3オブジェクトロックに相当するオブジェクト保護解決策 です。StorageGRID システムに対してグローバルな S3 オブジェクトロック設定を有効にすると、 S3 テナントアカウントで S3 オブジェクトのロックを有効にした状態でバケットを作成できるようになります。テナントは、S3クライアントアプリケーションを使用して、必要に応じてバケット内のオブジェクトの保持設定とリーガルホールド設定を指定できます。

S3オブジェクトロックを使用すると、テナントユーザは、一定期間、または無期限に特定のオブジェクトを保持することを求める規制に準拠できます。

.詳細はこちら。
* link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]
* link:../s3/index.html["S3 を使用する"]
* link:../tenant/index.html["テナントアカウントを使用する"]




== KMS暗号化キー管理

Grid Managerで1つ以上の外部キー管理サーバ（KMS）を設定して、StorageGRID サービスとストレージアプライアンスに暗号化キーを提供できるようになりました。KMS や KMS の各クラスタは、 Key Management Interoperability Protocol （ KMIP ）を使用して、関連する StorageGRID サイトにあるアプライアンスノードに暗号化キーを提供します。アプライアンスのボリュームを暗号化すると、ノードが KMS と通信できないかぎり、アプライアンスのデータにアクセスすることはできません。


NOTE: 暗号化キー管理を使用する場合は、アプライアンスをグリッドに追加する前に、StorageGRID アプライアンスインストーラを使用してアプライアンスのノード暗号化*設定を有効にする必要があります。

.詳細はこちら。
* link:../admin/index.html["StorageGRID の管理"]




== 情報ライフサイクル管理（ILM）のユーザビリティ向上

* ストレージプールの合計容量と使用済みスペースおよび空きスペースを表示できるようになりました。また、ストレージプールに含まれているノード、およびストレージプールを使用しているILMルールとイレイジャーコーディングプロファイルも確認できます。
* 複数のテナントアカウントに適用されるILMルールを設計できるようになりました。
* イレイジャーコーディング用のILMルールを作成する際に、非常に小さなオブジェクトがイレイジャーコーディングされないように、高度なフィルタ「オブジェクトサイズ（MB）」を0.2より大きい値に設定するように求められます。
* これで、デフォルトのILMルールが、別のルールに一致しないオブジェクトに常に使用されるようになりました。StorageGRID 11.5以降では、デフォルトルールで基本または高度なフィルタを使用することはできず、自動的にポリシーの最後のルールとして配置されます。
+

NOTE: 現在のILMポリシーが新しい要件に準拠していない場合は、StorageGRID 11.5へのアップグレード後もそのまま使用できます。ただし、アップグレード後に非準拠ポリシーをクローニングする場合は、フィルタを含まないデフォルトルールを選択するように求められ、デフォルトルールをポリシーの末尾に配置する必要があります。

* 新しいILMルールまたは新しいイレイジャーコーディングプロファイルを作成するときに、組み込みのAll Storage Nodesストレージプールがデフォルトで選択されなくなりました。また、どのルールでも使用されていないかぎり、All Storage Nodesストレージプールを削除できるようになりました。
+

NOTE: All Storage Nodesストレージプールにはすべてのサイトが含まれているため、このストレージプールを使用することは推奨されません。複数のサイトを含むStorageGRID システムでこのストレージプールを使用する場合は、オブジェクトの複数のコピーが同じサイトに配置されることがあります。

* アクティブポリシーまたはドラフトポリシーで使用されていないかぎり、組み込みのMake 2 Copiesルール（All Storage Nodesストレージプールを使用）を削除できるようになりました。
* クラウドストレージプールに格納されているオブジェクトをただちに削除できるようになりました（同期削除）。


.詳細はこちら。
* link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]




== Grid Managerの機能が強化されています

* 再設計されたTenant Accountsページでは、テナントアカウントの使用状況を簡単に確認できます。テナントの概要テーブルに、使用済みスペース、クォータ利用率、クォータ、オブジェクト数の列が表示されるようになりました。新しい* View Details *ボタンをクリックすると、各テナントの概要に加え、アカウントのS3バケットまたはSwiftコンテナの詳細情報にアクセスできます。さらに、2つのをエクスポートできるようになりました `.csv` テナントで使用するファイル：すべてのテナントの使用量の値とテナントのバケットまたはコンテナの詳細を含むファイル。
+
この変更に関連して、テナントアカウントの使用状況を追跡するために次の3つの新しいPrometheus指標が追加されました。

+
** `storagegrid_tenant_usage_data_bytes`
** `storagegrid_tenant_usage_object_count`
** `storagegrid_tenant_usage_quota_bytes`


* Admin Groupsページの新しい* Access Mode *フィールド（* Configuration *>* Access Control *）では、グループの管理権限を読み取り/書き込み（デフォルト）と読み取り専用のどちらにするかを指定できます。読み取り/書き込みアクセスモードのグループに属しているユーザは、Grid Managerおよびグリッド管理APIで設定を変更して処理を実行できます。読み取り専用アクセスモードのグループに属しているユーザは、グループに対して選択されている設定と機能のみを表示できます。
+

NOTE: StorageGRID 11.5にアップグレードすると、既存のすべての管理者グループに対して読み取り/書き込みアクセスモードオプションが選択されます。

* AutoSupport のユーザインターフェイスが再設計されました。グリッドマネージャの1つのページから、イベントトリガー型、ユーザトリガー型、および週次のAutoSupport メッセージを設定できるようになりました。AutoSupport メッセージの追加の送信先を設定することもできます。
+

NOTE: AutoSupport が有効になっていない場合は、Grid ManagerDashboardにリマインダメッセージが表示されます。

* Nodesページで* Storage Used - Object Data *グラフを表示したときに、レプリケートされたオブジェクトデータの量と、グリッド、サイト、またはストレージノード（* Nodes *>*_grid/site / Storage Node_*>* Storage *）上のイレイジャーコーディングデータの量の推定値が表示されるようになりました。
* Grid Managerのメニューオプションが再編成され、オプションが簡単に見つかりました。たとえば、新しい*ネットワーク設定*サブメニューが*環境設定*メニューに追加され、*メンテナンス*および*サポート*メニューのオプションがアルファベット順に表示されるようになりました。


.詳細はこちら。
* link:../admin/index.html["StorageGRID の管理"]




== Tenant Managerの機能拡張

* Tenant Managerのユーザインターフェイスの外観と構成は、ユーザエクスペリエンスを向上させるために完全に再設計されています。
* 新しいTenant Managerダッシュボードには各アカウントの概要が表示されます。バケットの詳細と、バケットまたはコンテナ、グループ、ユーザ、プラットフォームサービスのエンドポイント（設定されている場合）の数が表示されます。


.詳細はこちら。
* link:../tenant/index.html["テナントアカウントを使用する"]




== Prometheus指標エクスポート用のクライアント証明書

クライアント証明書（* Configuration *>* Access Control *>* Client Certificates *）をアップロードまたは生成できるようになりました。この証明書を使用して、StorageGRID Prometheusデータベースへのセキュアで認証されたアクセスを提供できます。たとえば、Grafanaを使用して外部からStorageGRID を監視する必要がある場合、クライアント証明書を使用できます。

.詳細はこちら。
* link:../admin/index.html["StorageGRID の管理"]




== ロードバランサの機能拡張

* サイトでルーティング要求を処理する際に、ロードバランササービスでロード対応ルーティングが実行されるようになりました。これにより、同じサイトにあるストレージノードのCPUの可用性が考慮されます。CPU の可用性に関する情報が、ロードバランササービスが配置されているサイトに制限されている場合があります。
+

NOTE: CPUアウェアネスは、サイトのストレージノードの3分の2以上がStorageGRID 11.5にアップグレードされてCPU統計がレポートされるまで有効になりません。

* セキュリティを強化するために、ロードバランサエンドポイントごとにバインディングモードを指定できるようになりました。エンドポイントのピン接続を使用すると、各エンドポイントのアクセス性を特定のハイアベイラビリティグループまたはノードインターフェイスに制限できます。


.詳細はこちら。
* link:../admin/index.html["StorageGRID の管理"]




== オブジェクトのメタデータが変更される

* *新しい実際のリザーブスペース指標*：各ストレージノードでのオブジェクトメタデータのスペース使用量を把握および監視するために、ストレージノードのStorage Used - Object Metadataグラフ（* Nodes *>*_Storage Node_*>* Storage *）に新しいPrometheus指標が表示されます。
+
[listing]
----
storagegrid_storage_utilization_metadata_reserved
----
+
Actual Reserved Space *指標は、特定のストレージノードでオブジェクトメタデータ用にStorageGRID がリザーブしているスペースの量を示します。

* *大容量のストレージノードを使用した環境でのメタデータスペースの増加*：次のように、128GB以上のRAMを搭載したストレージノードを含むStorageGRID システムでは、システム全体のMetadata Reserved Space設定が拡張されています。
+
** 注：新規インストールの場合は8TB *：StorageGRID 11.5システムをインストールし、グリッド内の各ストレージノードに128GB以上のRAMがある場合、システム全体のMetadata Reserved Space設定は、3TBではなく8TBに設定されます。
** *アップグレード用に4TB *：StorageGRID 11.5にアップグレードする際、いずれかのサイトの各ストレージノードに128GB以上のRAMが搭載されている場合、システム全体のMetadata Reserved Space設定が3TBではなく4TBに設定されています。
+
Metadata Reserved Space設定の新しい値によって、これらの大容量ストレージノードで使用できるメタデータスペースが最大2.64TB増加し、将来のハードウェアとソフトウェアのバージョン用に十分なメタデータスペースがリザーブされるようになりました。

+
[NOTE]
====
ストレージノードに十分なRAMがあり、ボリューム0に十分なスペースがある場合は、アップグレード後にMetadata Reserved Space設定を手動で8TBに増やすことができます。StorageGRID 11.5へのアップグレード後にメタデータスペースをリザーブすると、以降のハードウェアおよびソフトウェアのアップグレードが簡単になります。

link:increasing-metadata-reserved-space-setting.html["Metadata Reserved Space設定を拡張しています"]

====
+

NOTE: StorageGRID システムで任意のストレージノードに2.64TBを超えるメタデータを格納（または格納する予定がある場合）がある場合、許可されるメタデータスペースが増加することがあります。各ストレージノードのストレージボリューム0に空きスペースがあり、128GBを超えるRAMが搭載されている場合は、ネットアップのアカウント担当者にお問い合わせください。要件を確認し、可能であれば各ストレージノードで許可されているメタデータスペースを増やします。



* *削除されたメタデータの自動クリーンアップ*：ストレージノードに格納されているメタデータの20%以上を削除する準備ができた場合（対応するオブジェクトが削除されたため）、StorageGRID はそのストレージノードに対して自動コンパクションを実行できるようになりました。このバックグラウンドプロセスは、システムの負荷が低い場合にのみ実行されます。つまり、使用可能なCPU、ディスクスペース、メモリがある場合にのみ実行されます。新しいコンパクションプロセスでは、以前のリリースよりも前に削除されたオブジェクトのメタデータが削除されるため、新しいオブジェクトを格納するためのスペースを解放できます。


.詳細はこちら。
* link:../admin/index.html["StorageGRID の管理"]




== S3 REST API のサポートに関する変更点

* S3 REST APIを使用して指定できるようになりました <<S3オブジェクトロックで準拠データをロック,S3 オブジェクトのロック>> 設定：
+
** S3オブジェクトロックを有効にしてバケットを作成するには、でPUT Bucket要求を使用します `x-amz-bucket-object-lock-enabled` ヘッダー。
** バケットでS3オブジェクトロックが有効になっているかどうかを確認するには、GET Object Lock Configuration要求を使用します。
** S3オブジェクトのロックが有効になっているバケットにオブジェクトのバージョンを追加する場合は、次の要求ヘッダーを使用して保持設定とリーガルホールド設定を指定します。 `x-amz-object-lock-mode`、 `x-amz-object-lock-retain-until-date`および `x-amz-object-lock-legal-hold`。


* バージョン管理が有効になったバケットでDELETE Multiple Objectsを使用できるようになりました。
* PUT、GET、DELETE Bucket encryption要求を使用して、既存のS3バケットの暗号化を管理できるようになりました。
* のフィールド名が若干変更されました `Expiration` パラメータこのパラメータは、ライフサイクル設定環境 内の有効期限ルールが特定のオブジェクトである場合に、PUT Object、HEAD Object、またはGET Object要求への応答に含まれます。照合された有効期限ルールを示すフィールドは、以前に名前が付けられていました `rule_id`。このフィールドの名前がに変更されました `rule-id` AWSの実装に合わせて調整できます。
* デフォルトでは、S3 GET Storage Usage要求は、strong-global整合性を使用して、テナントアカウントとそのバケットで使用されているストレージの取得を試みます。strong-global整合性を保証できない場合、StorageGRID は、strong-site整合性を保証して使用状況の情報を取得します。
* 。 `Content-MD5` 要求ヘッダーが正しくサポートされるようになりました。


.詳細はこちら。
* link:../s3/index.html["S3 を使用する"]




== CloudMirrorオブジェクトの最大サイズが5TBに拡張されました

CloudMirrorレプリケーションサービスでデスティネーションバケットにレプリケートできるオブジェクトの最大サイズが5TBに拡張されました。これはStorageGRID でサポートされる最大オブジェクトサイズです。

.詳細はこちら。
* link:../s3/index.html["S3 を使用する"]
* link:../swift/index.html["Swift を使用します"]




== 新しいアラートが追加されました

StorageGRID 11.5で追加された新しいアラートは次のとおりです。

* アプライアンスの BMC 通信エラー
* アプライアンスのファイバ・チャネル障害が検出されました
* アプライアンスのファイバ・チャネル HBA ポート障害
* アプライアンスの LACP ポートがありません
* Cassandra 自動コンパクターエラーです
* Cassandra 自動コンパクターメトリックが古くなっています
* Cassandra の圧縮処理が過負荷です
* ディスク I/O が非常に遅い
* KMS CA 証明書の有効期限
* KMS クライアント証明書の有効期限
* KMS の設定をロードできませんでした
* KMS 接続エラー
* KMS 暗号化キー名が見つかりません
* KMS 暗号化キーのローテーションに失敗しました
* KMS は設定されていません
* KMS キーでアプライアンスボリュームを復号化できませんでした
* KMS サーバ証明書の有効期限
* ストレージプールの空き容量が不足しています
* ノードネットワーク受信フレームエラー
* サービスアプライアンスストレージの接続がデグレードされました
* ストレージアプライアンスストレージ接続のデグレード（以前の名称はアプライアンスストレージ接続デグレード）
* テナントクォータの使用率が高い
* 予期しないノードのリブートです


.詳細はこちら。
* link:../monitor/index.html["トラブルシューティングを監視します"]




== SNMPトラップのTCPサポート

SNMPトラップの送信先のプロトコルとしてTransmission Control Protocol（TCP；伝送制御プロトコル）を選択できるようになりました。以前は、User Datagram Protocol（UDP）プロトコルだけがサポートされていました。

.詳細はこちら。
* link:../monitor/index.html["トラブルシューティングを監視します"]




== インストールとネットワークの機能拡張

* * MACアドレス・クローニング*：MACアドレス・クローニングを使用して、特定の環境のセキュリティを強化できるようになりました。MACアドレスクローニングを使用すると、グリッドネットワーク、管理ネットワーク、およびクライアントネットワークに専用の仮想NICを使用できます。Dockerコンテナでホスト上の専用NICのMACアドレスを使用すると、プロミスキャスモードのネットワーク設定を回避できます。Linuxベース（ベアメタル）ノードのノード構成ファイルに3つの新しいMACアドレスクローニングキーが追加されました。
* * DNSおよびNTPホストルートの自動検出*:これまでは、クライアントネットワーク上にすべてのNTPおよびDNSサーバを配置できなかったという要件など、NTPおよびDNSサーバが接続する必要のあるネットワークに制限がありました。現在、これらの制限は削除されています。


.詳細はこちら。
* link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]
* link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]




== ストレージノードの拡張後のイレイジャーコーディング（EC）データのリバランシングをサポート

EC Rebalance手順 は、新しいストレージノードを追加したあとに必要になる可能性があるコマンドラインスクリプトです。手順 を実行すると、StorageGRID によって、サイトの既存および新しく拡張したストレージノードにイレイジャーコーディングフラグメントが再配分されます。


IMPORTANT: ECのリバランシング手順 は、限られた場合にのみ実行してください。たとえば、推奨数のストレージノードを追加して拡張できない場合は、ECのリバランシング手順 を使用してイレイジャーコーディングされたオブジェクトを追加で格納できます。

.詳細はこちら。
* link:../expand/index.html["グリッドを展開します"]




== 新規および改訂されたメンテナンス手順

* *サイトの運用停止*：StorageGRID システムから運用サイトを削除できるようになりました。接続されたサイトの運用停止手順 は、運用サイトを削除し、データを保持します。新しいDecommission Siteウィザードの指示に従って、次のプロセスを実行できます（* Maintenance *>* Decommission *>* Decommission Site *）。
* *アプライアンスノードのクローニング*：既存のアプライアンスノードをクローニングして、ノードを新しいアプライアンスモデルにアップグレードできるようになりました。たとえば、容量の小さいアプライアンスノードを容量の大きいアプライアンスにクローニングできます。また、アプライアンスノードをクローニングして、KMS暗号化に必要な新しい* Node Encryption *設定などの新機能を実装することもできます。
* *プロビジョニングパスフレーズの変更*：プロビジョニングパスフレーズ（* Configuration *>* Access Control *>* Grid Passwords *）を変更できるようになりました。パスフレーズは、リカバリ、拡張、およびメンテナンスの手順で必要になります。
* *拡張SSHパスワードの動作*：StorageGRID アプライアンスのセキュリティを強化するため、アプライアンスを保守モードにしてもSSHパスワードは変更されません。また、ノードをStorageGRID 11.5にアップグレードすると、新しいSSHホスト証明書とホストキーが生成されます。
+

NOTE: StorageGRID 11.5へのアップグレード後にSSHを使用してノードにログインすると、ホストキーが変更されたことを示す警告が表示されます。この動作は想定される動作であり、新しいキーを安全に承認することができます。



.詳細はこちら。
* link:../maintain/index.html[""]




== StorageGRID アプライアンスに対する変更

* *ストレージアプライアンス用のSANtricity システムマネージャへの直接アクセス*：StorageGRID アプライアンスインストーラおよびグリッドマネージャからEシリーズSANtricity システムマネージャのユーザインターフェイスにアクセスできるようになりました。これらの新しい方法を使用すると、アプライアンスの管理ポートを使用せずにSANtricity System Managerにアクセスできます。グリッドマネージャからSANtricity システムマネージャにアクセスする必要があるユーザには、新しいストレージアプライアンス管理者権限が必要です。
* *ノード暗号化*:新しいKMS暗号化機能の一部として、StorageGRID アプライアンスインストーラに新しい*ノード暗号化*設定が追加されました。暗号化キー管理を使用してアプライアンスのデータを保護する場合は、アプライアンスのハードウェア構成ステージでこの設定を有効にする必要があります。
* * UDPポート接続*：StorageGRID アプライアンスとUDPポート間のネットワーク接続をテストできるようになりました。たとえば、外部NFSサーバやDNSサーバに使用されるポートなどです。StorageGRID アプライアンスインストーラから、*Configure Networking *>* Port Connectivity Test (nmap)*を選択します。
* *インストールと設定の自動化*：StorageGRID アプライアンスインストーラに新しいJSON構成のアップロードページが追加されました（* Advanced *>* Update Appliance Configuration *）。このページでは、1つのファイルを使用して大規模なグリッド内に複数のアプライアンスを設定できます。また、も参照してください `configure-sga.py` StorageGRID アプライアンスインストーラの機能に合わせてPythonスクリプトが更新されました。


.詳細はこちら。
* link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]
* link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
* link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
* link:../sg5600/index.html["SG5600 ストレージアプライアンス"]




== 監査メッセージに対する変更

* *上書きされたオブジェクトの自動クリーンアップ*：以前は、特定のケースで上書きされたオブジェクトがディスクから削除されず、結果として追加のスペースが消費されていました。上書きされたこれらのオブジェクトはユーザがアクセスできなくなり、ストレージスペースを節約するために自動的に削除されるようになりました。詳細については、LCU監査メッセージを参照してください。
* * S3オブジェクトロック*用の新しい監査コード：SPUT監査メッセージに4つの新しい監査コードが追加されました <<S3オブジェクトロックで準拠データをロック,S3 オブジェクトのロック>> 要求ヘッダー：
+
** LKEN：オブジェクトロックが有効です
** LKLH：オブジェクトロックリーガルホールド
** LKMD：オブジェクトロック保持モード
** LKRU：オブジェクトロックまで保持日


* *最終変更時刻と前のオブジェクトサイズの新しいフィールド*:オブジェクトが上書きされた日時と元のオブジェクトサイズを追跡できるようになりました。
+
** MTME（Last Modified Time）フィールドが次の監査メッセージに追加されました。
+
*** SDEL（S3 DELETE）
*** SPUT（S3 PUT）
*** WDEL（Swift DELETE）
*** WPUT（Swift PUT）


** CSIZ（Previous Object Size）フィールドがOVWR（Object Overwrite）監査メッセージに追加されました。




.詳細はこちら。
* link:../audit/index.html["監査ログを確認します"]




== 新しいnms.requestlogファイル

新しいログファイル、 `/var/local/log/nms.requestlog`は、すべての管理ノードで管理されます。このファイルには、管理APIから内部StorageGRID サービスへの発信接続に関する情報が格納されます。

.詳細はこちら。
* link:../monitor/index.html["トラブルシューティングを監視します"]




== StorageGRID のマニュアルの変更点

* ネットワーク情報と要件を見つけやすくし、環境 StorageGRID アプライアンスノードに関する情報も明確にするために、ネットワーク関連のドキュメントはソフトウェアベースのインストールガイド（Red Hat Enterprise Linux/CentOS、Ubuntu / Debian、VMware）から新しいネットワークガイドに移動されました。
+
link:../network/index.html["ネットワークガイドライン"]

* ILM関連の手順や例を簡単に見つけることができるように、情報ライフサイクル管理を含むオブジェクトを管理するためのドキュメントを、_管理者ガイド_から新しいILMガイドに移動しました。
+
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

* 新しいFabricPool ガイドでは、StorageGRID をNetApp FabricPool クラウド階層として設定する方法の概要を示し、ILMおよびFabricPool ワークロードのその他のStorageGRID オプションを設定するためのベストプラクティスについて説明します。
+
link:../fabricpool/index.html["StorageGRID for FabricPool を設定します"]

* グリッドマネージャからいくつかの手順ビデオにアクセスできるようになりました。最新のビデオでは、アラート、カスタムアラート、ILMルール、ILMポリシーを管理する手順について説明しています。

