---
permalink: sg100-1000/automating-appliance-installation-and-configuration.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, automate, automating, automation, automatic, install, installation, configuration, configure 
summary: アプライアンスのインストールと設定、および StorageGRID システム全体の設定を自動化することができます。 
---
= アプライアンスのインストールと設定の自動化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスのインストールと設定、および StorageGRID システム全体の設定を自動化することができます。

.このタスクについて
インストールと設定を自動化すると、複数の StorageGRID インスタンス、または大規模で複雑な StorageGRID インスタンスを 1 つ導入する場合に便利です。

インストールと設定を自動化するには、次のオプションを 1 つ以上使用します。

* アプライアンスの構成設定を指定した JSON ファイルを作成します。StorageGRID アプライアンスインストーラを使用して JSON ファイルをアップロードします。
+

NOTE: 同じファイルを使用して、複数のアプライアンスを設定できます。

* StorageGRID を使用します``configure-sga.py`` アプライアンスの設定を自動化するPythonスクリプト。
* 追加の Python スクリプトを使用して、 StorageGRID システム全体の他のコンポーネント（「グリッド」）を設定します。



NOTE: Python スクリプトを StorageGRID 自動化で直接使用することも、 StorageGRID インストール REST API を独自に開発するグリッド導入および設定ツールで使用する例として使用することもできます。リカバリとメンテナンスの手順のStorageGRID インストールファイルのダウンロードと展開に関する情報を参照してください。

.関連情報
link:../maintain/index.html[""]
