---
permalink: ubuntu/automating-installation-and-configuration-of-storagegrid-host-service.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。 
---
= StorageGRID ホストサービスのインストールと設定を自動化する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。

StorageGRID ホストサービスは、 DEB 形式でパッケージ化されており、あらかじめ構成ファイルを用意して（またはプログラム化して）おくことで自動インストールが可能です。すでに Ubuntu または Debian のインストールおよび設定に標準的なオーケストレーションフレームワークを使用している場合は、プレイブックやレシピに StorageGRID を追加する方が簡単です。

次のタスクを自動化できます。

. Linux をインストールしています
. Linux の設定
. StorageGRID の要件を満たすホストネットワークインターフェイスを設定する
. StorageGRID の要件を満たすホストストレージを構成する
. Docker をインストールする
. StorageGRID ホストサービスをインストールしています
. でのStorageGRID ノード構成ファイルの作成 `/etc/storagegrid/nodes`
. StorageGRID ノード構成ファイルを検証しています
. StorageGRID ホストサービスを開始しています




== サンプルの Ansible のロールとプレイブック

サンプルの Ansible のロールとプレイブックは、 /extras フォルダに含まれるインストールアーカイブに含まれています。Ansibleプレイブックは、の仕組みを示しています `storagegrid` 役割ホストを準備し、ターゲットサーバーにStorageGRID をインストールします。必要に応じて、ロールまたはプレイブックをカスタマイズできます。
