---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, ubuntu, debian, download installation files, downloading installation files 
summary: StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。 
---
= StorageGRID インストールファイルのダウンロードと展開
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。

.手順
. ネットアップの StorageGRID ダウンロードページにアクセスします。
+
https://["ネットアップのダウンロード： StorageGRID"^]

. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. 「注意 / 必ずお読みください」という記述が表示されたら、それを読んでチェックボックスを選択してください。
+
StorageGRID リリースのインストール後に、必要な修正プログラムを適用する必要があります。詳細については、リカバリおよびメンテナンスの手順にあるホットフィックス手順 を参照してください。

. エンドユーザライセンス契約を読み、チェックボックスをオンにして、「 * 同意して続行 * 」を選択します。
+
選択したバージョンのダウンロードページが表示されます。このページには 3 つの列があります。

. [Install StorageGRID *（インストールソフトウェアのインストール）]列で、適切なソフトウェアを選択します。
+
を選択します `.tgz` または `.zip` 使用するプラットフォームに対応したアーカイブファイルです。

+
** `StorageGRID-Webscale-version-DEB-uniqueID.zip`
** `StorageGRID-Webscale-version-DEB-uniqueID.tgz`
+
圧縮ファイルには、UbuntuまたはDebianのDEBファイルとスクリプトが含まれています。



+

NOTE: を使用します `.zip` ファイルサービスラップトップでWindowsを実行している場合。

. アーカイブファイルを保存して展開します。
. 次のリストから必要なファイルを選択します。
+
必要なファイルは、計画したグリッドトポロジおよび StorageGRID グリッドの導入方法によって異なります。

+

NOTE: 次の表に示すパスは、展開されたインストールアーカイブによってインストールされた最上位ディレクトリに対する相対パスです。



[cols="1a,2a"]
|===
| パスとファイル名 | 説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境およびコンセプトの実証環境に使用できる、非本番環境のネットアップライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



 a| 
*展開スクリプトツール*
 a| 
* 概要 *



| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
で使用するサンプル構成ファイル `configure-storagegrid.py` スクリプト：



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。

|===
.関連情報
link:../maintain/index.html[""]
