---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: クライアントは、コンテンツの取り込みと読み出しを行うためにグリッドノードと通信する必要があります。使用するポートは、選択したオブジェクトストレージプロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。 
---
= 外部との通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントは、コンテンツの取り込みと読み出しを行うためにグリッドノードと通信する必要があります。使用するポートは、選択したオブジェクトストレージプロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。

エンタープライズネットワークポリシーでいずれかのポートへのアクセスが制限されている場合は、ロードバランサエンドポイントを使用してユーザ定義のポートへのアクセスを許可できます。信頼されていないクライアントネットワーク機能を使用すると、ロードバランサエンドポイントポートにのみアクセスを許可できます。


NOTE: SMTP 、 DNS 、 SSH 、 DHCP などのシステムとプロトコルを使用するには、ノードを導入する際にポートを再マッピングする必要があります。ただし、バランサエンドポイントを再マッピングしないでください。ポートの再マッピングの詳細については、ご使用のプラットフォームのインストール手順を参照してください。

次の表に、ノードに着信するトラフィックに使用されるポートを示します。


NOTE: このリストには、ロードバランサエンドポイントとして設定されている可能性のあるポートは含まれていません。詳細については、ロードバランサエンドポイントの設定手順を参照してください。

[cols="1a,1a,1a,1a,1a,2a"]
|===
| ポート | tcp または udp です | プロトコル | 移動元 | 終了： | 詳細 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソールの手順を実行するには、 SSH アクセスまたはコンソールアクセスが必要です。必要に応じて、ポート 22 の代わりに 2022 を使用できます。



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
管理ノード
 a| 
E メールサーバ
 a| 
アラートおよび E メールベースの AutoSupport に使用されます。Email Servers ページを使用して、デフォルトのポート設定である 25 を上書きできます。



 a| 
53
 a| 
TCP / UDP
 a| 
DNS
 a| 
すべてのノード
 a| 
DNS サーバ
 a| 
ドメインネームシステムに使用します。



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
すべてのノード
 a| 
DHCP サービス
 a| 
必要に応じて、 DHCP ベースのネットワーク設定のサポートに使用します。dhclient サービスは、静的に設定されたグリッドに対しては実行されません。



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
DHCP サービス
 a| 
すべてのノード
 a| 
必要に応じて、 DHCP ベースのネットワーク設定のサポートに使用します。dhclient サービスは、静的 IP アドレスを使用するグリッドに対しては実行されません。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
管理ノード
 a| 
ポート 80 は、管理ノードのユーザインターフェイス用のポート 443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
アプライアンス
 a| 
ポート 80 は、 StorageGRID アプライアンスインストーラ用のポート 8443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ADC を採用するストレージノード
 a| 
AWS
 a| 
AWS または HTTP を使用するその他の外部サービスに送信されるプラットフォームサービスのメッセージに使用します。エンドポイントの作成時に、テナントのデフォルトの HTTP ポート設定である 80 よりも優先される。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ストレージノード
 a| 
AWS
 a| 
HTTP を使用する AWS ターゲットに送信されるクラウドストレージプール要求。クラウドストレージプールを設定するときに、グリッド管理者がデフォルトの HTTP ポート設定である 80 を上書きできます。



 a| 
111
 a| 
TCP / UDP
 a| 
rpcbind
 a| 
NFS クライアント
 a| 
管理ノード
 a| 
NFS ベースの監査エクスポート（ portmap ）で使用します。

* 注：このポートは、 NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
プライマリ NTP ノード
 a| 
外部 NTP
 a| 
ネットワークタイムプロトコルサービス。プライマリ NTP ソースとして選択されたノードは、クロックの時間と外部 NTP の時間ソースとの同期も行います。



 a| 
137
 a| 
UDP
 a| 
NETBIOS
 a| 
SMB クライアント
 a| 
管理ノード
 a| 
NetBIOS サポートを必要とするクライアントの SMB ベースの監査エクスポートで使用します。

* 注：このポートは、 SMB ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
138
 a| 
UDP
 a| 
NETBIOS
 a| 
SMB クライアント
 a| 
管理ノード
 a| 
NetBIOS サポートを必要とするクライアントの SMB ベースの監査エクスポートで使用します。

* 注：このポートは、 SMB ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
139
 a| 
TCP
 a| 
SMB
 a| 
SMB クライアント
 a| 
管理ノード
 a| 
NetBIOS サポートを必要とするクライアントの SMB ベースの監査エクスポートで使用します。

* 注：このポートは、 SMB ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
161
 a| 
TCP / UDP
 a| 
SNMP
 a| 
SNMP クライアント
 a| 
すべてのノード
 a| 
SNMP ポーリングに使用します。すべてのノードは基本情報を提供し、管理ノードはアラートデータとアラームデータも提供します。設定時のデフォルトの UDP ポートは 161 です。

* 注：このポートは必須です。 SNMP が設定されている場合にのみノードファイアウォールで開かれます。SNMP を使用する場合は、代替ポートを設定できます。

* 注： StorageGRID での SNMP の使用については、ネットアップの営業担当者にお問い合わせください。



 a| 
162
 a| 
TCP / UDP
 a| 
SNMP 通知
 a| 
すべてのノード
 a| 
通知の送信先
 a| 
アウトバウンド SNMP 通知およびトラップのデフォルトの UDP ポートは 162 です。

* 注：このポートは、 SNMP が有効で通知の送信先が設定されている場合にのみ必要です。SNMP を使用する場合は、代替ポートを設定できます。

* 注： StorageGRID での SNMP の使用については、ネットアップの営業担当者にお問い合わせください。



 a| 
389
 a| 
TCP / UDP
 a| 
LDAP
 a| 
ADC を採用するストレージノード
 a| 
Active Directory / LDAP
 a| 
アイデンティティフェデレーション用の Active Directory または LDAP サーバに接続するために使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
Grid Manager と Tenant Manager にアクセスするために Web ブラウザと管理 API クライアントで使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
管理ノード
 a| 
Active Directory
 a| 
シングルサインオン（ SSO ）が有効な場合に、 Active Directory に接続する管理ノードで使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
アーカイブノード
 a| 
Amazon S3
 a| 
アーカイブノードから Amazon S3 にアクセスするために使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ADC を採用するストレージノード
 a| 
AWS
 a| 
AWS または HTTPS を使用するその他の外部サービスに送信されるプラットフォームサービスのメッセージに使用します。エンドポイントの作成時に、テナントがデフォルトの HTTP ポート設定である 443 を上書きできる。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ストレージノード
 a| 
AWS
 a| 
HTTPS を使用する AWS ターゲットに送信されるクラウドストレージプール要求。クラウドストレージプールの設定時に、グリッド管理者がデフォルトの HTTPS ポート設定である 443 を上書きできます。



 a| 
445
 a| 
TCP
 a| 
SMB
 a| 
SMB クライアント
 a| 
管理ノード
 a| 
SMB ベースの監査エクスポートで使用します。

* 注：このポートは、 SMB ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
903.
 a| 
TCP
 a| 
NFS
 a| 
NFS クライアント
 a| 
管理ノード
 a| 
NFSベースの監査エクスポートで使用します (`rpc.mountd`）。

* 注：このポートは、 NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソールの手順を実行するには、 SSH アクセスまたはコンソールアクセスが必要です。必要に応じて、 2022 の代わりにポート 22 を使用できます。



 a| 
2049
 a| 
TCP
 a| 
NFS
 a| 
NFS クライアント
 a| 
管理ノード
 a| 
NFS ベースの監査エクスポート（ NFS ）で使用します。

* 注：このポートは、 NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
アプライアンス
 a| 
KMS
 a| 
ノードの暗号化用に設定されたアプライアンスから Key Management Server （ KMS ）へのキー管理 Interoperability Protocol （ KMIP ）の外部トラフィック（ StorageGRID アプライアンスインストーラの KMS 構成のページで別のポートを指定している場合を除く）。



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
ポート 8022 で SSH を使用すると、サポートとトラブルシューティング用に、アプライアンスと仮想ノードプラットフォーム上のベースのオペレーティングシステムへのアクセスが許可されます。このポートは Linux ベース（ベアメタル）ノードには使用されず、グリッドノード間または通常運用時にアクセス可能である必要はありません。



 a| 
「 8082 」
 a| 
TCP
 a| 
HTTPS
 a| 
S3 クライアント
 a| 
ゲートウェイノード
 a| 
ゲートウェイノードへのS3関連の外部トラフィック（HTTPS）。



 a| 
8083
 a| 
TCP
 a| 
HTTPS
 a| 
Swift クライアント
 a| 
ゲートウェイノード
 a| 
ゲートウェイノードへのSwift関連の外部トラフィック（HTTPS）。



 a| 
8084
 a| 
TCP
 a| 
HTTP
 a| 
S3 クライアント
 a| 
ゲートウェイノード
 a| 
ゲートウェイノードへのS3関連の外部トラフィック（HTTP）。



 a| 
8085
 a| 
TCP
 a| 
HTTP
 a| 
Swift クライアント
 a| 
ゲートウェイノード
 a| 
ゲートウェイノードへのSwift関連の外部トラフィック（HTTP）。



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
任意。Grid Manager にアクセスするために Web ブラウザと管理 API クライアントで使用されます。を使用して、 Grid Manager と Tenant Manager の通信を分離できます。



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
アプライアンス
 a| 
サポートとトラブルシューティングのために、構成前モードでの StorageGRID アプライアンスへのアクセスを許可します。このポートは、グリッドノード間で、または通常運用時にアクセス可能である必要はありません。



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
外部の Grafana サービス
 a| 
管理ノード
 a| 
外部の Grafana サービスが StorageGRID Prometheus サービスへのセキュアなアクセスに使用します。

* 注：このポートは、証明書ベースの Prometheus アクセスが有効になっている場合にのみ必要です。



 a| 
ポート 1
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
任意。Tenant Manager にアクセスするために Web ブラウザと管理 API クライアントで使用します。を使用して、 Grid Manager と Tenant Manager の通信を分離できます。



 a| 
18082 年
 a| 
TCP
 a| 
HTTPS
 a| 
S3 クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのS3関連の外部トラフィック（HTTPS）。



 a| 
18083 年
 a| 
TCP
 a| 
HTTPS
 a| 
Swift クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのSwift関連の外部トラフィック（HTTPS）。



 a| 
18084 年
 a| 
TCP
 a| 
HTTP
 a| 
S3 クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのS3関連の外部トラフィック（HTTP）。



 a| 
18085 年になります
 a| 
TCP
 a| 
HTTP
 a| 
Swift クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのSwift関連の外部トラフィック（HTTP）。

|===
.関連情報
link:internal-grid-node-communications.html["内部でのグリッドノードの通信"]

link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]

link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]

link:../vmware/index.html["VMware をインストールする"]

link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]

link:../sg6000/index.html["SG6000 ストレージアプライアンス"]

link:../sg5700/index.html["SG5700 ストレージアプライアンス"]

link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
