---
permalink: network/host-network-configuration-for-docker-deployments.html 
sidebar: sidebar 
keywords:  
summary: DockerコンテナプラットフォームでStorageGRID の導入を開始する前に、各ノードで使用するネットワーク（グリッド、管理、クライアント）を決定します。各ノードのネットワークインターフェイスが正しい仮想または物理ホストインターフェイス上に設定されていること、および各ネットワークに十分な帯域幅があることを確認する必要があります。 
---
= Docker環境向けのホストネットワーク構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DockerコンテナプラットフォームでStorageGRID の導入を開始する前に、各ノードで使用するネットワーク（グリッド、管理、クライアント）を決めます。各ノードのネットワークインターフェイスが正しい仮想または物理ホストインターフェイスに設定されていること、および各ネットワークに十分な帯域幅があることを確認してください。



== 物理ホスト

物理ホストを使用してグリッドノードをサポートする場合は、次の手順を実行します。

* すべてのホストで各ノードインターフェイスに同じホストインターフェイスを使用していることを確認します。この方法により、ホストの構成が簡易化され、将来のノードの移行にも対応できます
* 物理ホスト自体の IP アドレスを取得します。
+

NOTE: ホスト上の物理インターフェイスは、ホスト自体と、ホスト上で実行されている 1 つ以上のノードで使用できます。このインターフェイスを使用するホストまたはノードには、一意の IP アドレスを割り当てる必要があります。ホストとノードは IP アドレスを共有できません。

* ホストに必要なポートを開きます。




== 最小帯域幅の推奨値

次の表に、 StorageGRID ノードのタイプとネットワークのタイプ別に推奨される最小帯域幅を示します。それぞれの物理ホストまたは仮想ホストについて、そのホストで実行する StorageGRID ノードの総数とタイプに応じて、アグリゲートの最小帯域幅要件を満たすように十分なネットワーク帯域幅を確保する必要があります。

|===
| ノードのタイプ 3+| ネットワークのタイプ 


 a| 
| グリッド（ Grid ） | 管理 | クライアント 


 a| 
管理
| 10 Gbps | 1 Gbps | 1 Gbps 


 a| 
ゲートウェイ
| 10 Gbps | 1 Gbps | 10 Gbps 


 a| 
ストレージ
| 10 Gbps | 1 Gbps | 10 Gbps 


 a| 
Archive サービスの略
| 10 Gbps | 1 Gbps | 10 Gbps 
|===

NOTE: この表には、共有ストレージへのアクセスに必要な SAN の帯域幅は含まれていません。イーサネット経由（ iSCSI または FCoE ）でアクセスする共有ストレージを使用する場合は、各ホストで物理インターフェイスを別途プロビジョニングして十分な SAN の帯域幅を確保する必要があります。ボトルネックにならないように、各ホストの SAN の帯域幅として、そのホストで実行されるすべてのストレージノードの総ネットワーク帯域幅とほぼ同じ帯域幅を確保します。

上記の表を参照して、それぞれのホストに最小限必要なネットワークインターフェイスの数を確認します。これは、そのホストで実行する StorageGRID ノードの数とタイプで決まります。

たとえば、単一のホストで管理ノード、ゲートウェイノード、およびストレージノードを 1 つずつ実行するには、次の手順を実行します。

* 管理ノードにグリッドネットワークと管理ネットワークを接続する（必要な帯域幅： 10 + 1 = 11Gbps ）
* ゲートウェイノードにグリッドネットワークとクライアントネットワークを接続する（必要な帯域幅： 10 + 10 = 20Gbps ）
* ストレージノードにグリッドネットワークを接続する（必要な帯域幅： 10Gbps ）


このシナリオでは、少なくとも 11+20+10=41 Gbps のネットワーク帯域幅を提供する必要があります。 2 つの 40Gbps インターフェイスまたは 5 つの 10Gbps インターフェイスで対応できます。これらは潜在的にトランクに集約され、ホストを含む物理データセンターに対してローカルなグリッド、管理、およびクライアントのサブネットを伝送する 3 つ以上の VLAN によって共有されます。

StorageGRID クラスタのホストの物理リソースおよびネットワークリソースを設定してStorageGRID を導入する準備として推奨される方法については、使用しているLinuxプラットフォームのインストール手順のホストネットワークの設定に関する情報を参照してください。

.関連情報
link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]

link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]
