---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID プラットフォームサービスまたはクラウドストレージプールを使用する場合は、デスティネーションエンドポイントに到達できるようにグリッドネットワークとファイアウォールを設定する必要があります。プラットフォームサービスには、検索統合、イベント通知、CloudMirrorレプリケーションを提供する外部サービスが含まれます。 
---
= プラットフォームサービスとクラウドストレージプール用のネットワークとポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID プラットフォームサービスまたはクラウドストレージプールを使用する場合は、デスティネーションエンドポイントに到達できるようにグリッドネットワークとファイアウォールを設定する必要があります。プラットフォームサービスには、検索統合、イベント通知、CloudMirrorレプリケーションを提供する外部サービスが含まれます。

プラットフォームサービスには、 StorageGRID ADC サービスをホストするストレージノードから外部サービスエンドポイントへのアクセスが必要です。アクセスの提供例は次のとおりです。

* ADC サービスがあるストレージノードで、ターゲットエンドポイントにルーティングする AESL エントリを使用して一意の管理ネットワークを設定します。
* クライアントネットワークが提供するデフォルトルートを使用します。この例では、信頼されていないクライアントネットワーク機能を使用して、インバウンド接続を制限できます。


また、クラウドストレージプールは、ストレージノードから、 Amazon S3 Glacier や Microsoft Azure BLOB ストレージなどの使用する外部サービスが提供するエンドポイントへのアクセスを必要とします。

デフォルトでは、プラットフォームサービスとクラウドストレージプールの通信には次のポートが使用されます。

* *80*：で始まるエンドポイントURIの場合 `http`
* *442*：で始まるエンドポイントURI `https`


エンドポイントの作成時または編集時に別のポートを指定できます。

非透過型プロキシサーバを使用する場合は、プロキシの設定で、インターネット上のエンドポイントなどの外部エンドポイントへのメッセージの送信を許可する必要もあります。プロキシの設定方法については、StorageGRID の管理を参照してください。

信頼されていないクライアントネットワークの詳細については、StorageGRID の管理手順を参照してください。プラットフォームサービスの詳細については、テナントアカウントの使用手順を参照してください。クラウドストレージプールの詳細については、情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照してください。

.関連情報
link:network-port-reference.html["ネットワークポートのリファレンス"]

link:../primer/index.html["グリッド入門"]

link:../admin/index.html["StorageGRID の管理"]

link:../tenant/index.html["テナントアカウントを使用する"]

link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]
