---
permalink: tenant/using-search-integration-service.html 
sidebar: sidebar 
keywords: storagegrid, tenant, search integration, search integration service, configuring search integration, configure search integration 
summary: 検索統合サービスは、 3 つの StorageGRID プラットフォームサービスのうちの 1 つです。このサービスを有効にすると、オブジェクトが作成、削除されたとき、またはそのメタデータやタグが更新されたときに、デスティネーションの検索インデックスにオブジェクトメタデータを送信できます。 
---
= 検索統合サービスを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
検索統合サービスは、 3 つの StorageGRID プラットフォームサービスのうちの 1 つです。このサービスを有効にすると、オブジェクトが作成、削除されたとき、またはそのメタデータやタグが更新されたときに、デスティネーションの検索インデックスにオブジェクトメタデータを送信できます。

テナントマネージャを使用して検索統合を設定し、カスタム StorageGRID 設定 XML をバケットに適用できます。


NOTE: 検索統合サービスではオブジェクトメタデータがデスティネーションに送信されるため、その設定 XML は _ メタデータ通知設定 xml_ と呼ばれます。この設定 XML は、イベント通知を有効にするための _ 通知設定 xml_ とは異なります。

次のカスタムのStorageGRID S3 REST API処理の詳細については、S3クライアントアプリケーションを実装する手順を参照してください。

* DELETE Bucket metadata notification configuration 要求
* GET Bucket metadata notification configuration 要求
* PUT Bucket metadata notification configuration 要求


.関連情報
link:configuration-xml-for-search-configuration.html["検索統合用の XML を設定します"]

link:object-metadata-included-in-metadata-notifications.html["メタデータ通知に含まれているオブジェクトメタデータ"]

link:json-generated-by-search-integration-service.html["検索統合サービスで生成される JSON"]

link:configuring-search-integration-service.html["検索統合サービスの設定"]

link:../s3/index.html["S3 を使用する"]
