---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords:  
summary: グリッドノードを導入する前に、ネットワーク設定と VMware 環境に関する情報を収集する必要があります。 
---
= 導入環境に関する情報を収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードを導入する前に、ネットワーク設定と VMware 環境に関する情報を収集する必要があります。



== VMware の情報

導入環境にアクセスし、 VMware 環境に関する情報、グリッドネットワーク、管理ネットワーク、クライアントネットワーク用に作成されたネットワークに関する情報、およびストレージノードで使用する予定のストレージボリュームタイプに関する情報を収集する必要があります。

VMware 環境に関する次の情報を収集する必要があります。

* 導入を完了するための適切な権限を持つ VMware vSphere アカウントのユーザ名とパスワード。
* 各 StorageGRID グリッドノード仮想マシンのホスト、データストア、およびネットワーク設定に関する情報。



IMPORTANT: VMware のライブ vMotion を使用すると仮想マシンのクロック時間が急に進むため、この機能はどのタイプのグリッドノードでもサポートされていません。まれにではありますが、クロック時間が不正確だとデータや設定の更新が失われることがあります。



== グリッドネットワークの情報

StorageGRID グリッドネットワーク（必須）用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* DHCP を使用しない場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、およびネットワークマスク）。
* DHCP を使用しない場合は、グリッドネットワーク上のプライマリ管理ノードの IP アドレス。詳細については、「グリッドノードによるプライマリ管理ノードの検出」を参照してください。




== 管理ネットワークの情報

ノードがオプションの StorageGRID 管理ネットワークに接続される場合は、このネットワーク用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* 静的または DHCP のいずれかの IP アドレスの割り当てに使用する方法。
* 静的 IP アドレスを使用する場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、ネットワークマスク）。
* 管理ネットワークの外部サブネットリスト（ ESL ）。




== クライアントネットワークの情報

ノードがオプションの StorageGRID クライアントネットワークに接続される場合は、このネットワーク用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* 静的または DHCP のいずれかの IP アドレスの割り当てに使用する方法。
* 静的 IP アドレスを使用する場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、ネットワークマスク）。




== 仮想ストレージノードのストレージボリューム

仮想マシンベースのストレージノードに関する次の情報を収集する必要があります。

* 追加するストレージボリューム（ストレージ LUN ）の数とサイズ。「ストレージとパフォーマンスの要件」を参照してください。




== グリッドの設定情報

グリッドを設定するための情報を収集する必要があります。

* Grid ライセンス
* Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバの IP アドレス
* Domain Name System （ DNS ；ドメインネームシステム）サーバの IP アドレス


.関連情報
link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"]

link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"]
