---
permalink: vmware/configuration-file-settings.html 
sidebar: sidebar 
keywords:  
summary: deploy-vsphere-ovftool.ini構成ファイルには、仮想グリッドノードを導入するために必要な設定が含まれています。 
---
= 構成ファイルの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `deploy-vsphere-ovftool.ini` 構成ファイルには、仮想グリッドノードを導入するために必要な設定が含まれています。

構成ファイルでは、最初にグローバルパラメータがリストされ、そのあとにノード名で定義されるセクションにノード固有のパラメータがリストされます。ファイルの使用状況：

* _Global parameters_ は、すべてのグリッドノードに適用されます。
* _Node-specific parameters_override グローバルパラメータ。




== グローバルパラメータ

グローバルパラメータは、個々のセクションの設定で上書きされないかぎり、すべてのグリッドノードに適用されます。複数のノードに適用するパラメータをグローバルパラメータセクションに配置し、個々のノードのセクションで必要に応じてこれらの設定を上書きします。

* * OVFTOOL_ARGUMENTS * ： OVFTOOL_ARGUMENTS をグローバル設定として指定するか、または特定のノードに個別に引数を適用できます。例：
+
[source, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=thin --datastore='_datastore_name_'
----
+
を使用できます `--powerOffTarget` および `--overwrite` 既存の仮想マシンをシャットダウンおよび交換するオプション。

+

IMPORTANT: ノードを別々のデータストアに導入し、 OVFTOOL_ARGUMENTS をグローバルに指定するのではなくノードごとに指定する必要があります。

* * source *：StorageGRID 仮想マシン・テンプレートへのパス (`.vmdk`)ファイルと `.ovf` および `.mf` 個 々 のグリッドノードのファイル。デフォルトでは現在のディレクトリに設定されます。
+
[source, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* * target * ： StorageGRID の導入先となる VMware vSphere 仮想インフラ（ vi ）の URL 。例：
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* * GRID_NETWORK_CONFIG * ：静的または DHCP のいずれかの IP アドレスの取得に使用される方法。デフォルトは「 STATIC 」です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_CONFIG = DHCP
----
* * GRID_NETWORK_TARGET * ：グリッドネットワークに使用される既存の VMware ネットワークの名前。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_TARGET = SG-Admin-Network
----
* * GRID_NETWORK_MASK * ：グリッドネットワークのネットワークマスク。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* * GRID_NETWORK_GATEWAY * ：グリッドネットワークのネットワークゲートウェイ。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* * GRID_NETWORK_MTU * ：オプション。グリッドネットワークでの最大伝送ユニット（ MTU ）です。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。例：
+
[listing]
----
GRID_NETWORK_MTU = 8192
----
+
省略すると 1400 に設定されます。

+
ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

+

IMPORTANT: ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定されている値と同じである必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

+

IMPORTANT: ネットワークのパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU 値はすべてのネットワークタイプで同じである必要はありません。

* * ADMIN_NETWORK_CONFIG * ： IP アドレスの取得に使用された方法。無効、静的、または DHCP のいずれかです。デフォルトは disabled です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* * ADMIN_NETWORK_TARGET * ：管理ネットワークに使用する既存の VMware ネットワークの名前。この設定は、管理ネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_TARGET = SG-Admin-Network
----
* * ADMIN_NETWORK_MASK * ：管理ネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* * ADMIN_NETWORK_GATEWAY * ：管理ネットワークのネットワークゲートウェイ。この設定は、 IP アドレスを静的に指定し、かつ ADMIN_NETWORK_ESL 設定で外部サブネットを指定する場合に必要となります（ ADMIN_NETWORK_ESL が空の場合は不要です）。 全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* * ADMIN_NETWORK_ESL * ：管理ネットワークの外部サブネットリスト（ルート）。 CIDR ルートのデスティネーションをカンマで区切ったリストとして指定します。全ノードまたはほとんどのノードが同じ外部サブネットリストを使用する場合は、ここでそのリストを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* * ADMIN_NETWORK_MTU * ：オプション。管理ネットワークでの最大伝送ユニット（ MTU ）です。ADMIN_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると 1400 に設定されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードが管理ネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* * CLIENT_NETWORK_CONFIG * ： IP アドレスの取得に使用する方法。無効、静的、または DHCP のいずれかになります。デフォルトは disabled です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* * client_network_target * ：クライアントネットワークに使用する既存の VMware ネットワークの名前。この設定は、クライアントネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_TARGET = SG-Client-Network
----
* * CLIENT_NETWORK_MASK * ：クライアントネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* * client_network_gateway * ：クライアントネットワークのネットワークゲートウェイ。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* * CLIENT_NETWORK_MTU * ：オプション。クライアントネットワークでの最大伝送ユニット（ MTU ）です。CLIENT_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると 1400 に設定されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードがクライアントネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* * PORT_REMAP * ：ノードが内部でのグリッドノードの通信または外部との通信に使用するポートを再マッピングします。StorageGRID で使用される 1 つ以上のポートがエンタープライズネットワークポリシーによって制限される場合は、ポートの再マッピングが必要です。StorageGRID で使用されるポートのリストについては、で内部でのグリッドノードの通信および外部との通信を参照してください link:../network/index.html["ネットワークのガイドライン"]。
+

IMPORTANT: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。

+

NOTE: PORT_REMAP のみを設定すると、指定したマッピングがインバウンド通信とアウトバウンド通信の両方に使用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。



使用される形式は次のとおりです。 `_network type_/_protocol/_default port used by grid node_/_new port_`network typeはgrid、admin、clientのいずれかで、protocolはTCPまたはUDPです。

例：

[listing]
----
PORT_REMAP = client/tcp/18082/443
----
この例の設定だけを使用した場合は、グリッドノードのインバウンド通信とアウトバウンド通信の両方が、ポート 18082 からポート 443 へと対称的にマッピングされます。この例の設定を PORT_REMAP_INBOUND とともに使用した場合は、アウトバウンド通信がポート 18082 からポート 443 にマッピングされます。

* * port_remap_inbound * ：指定したポートのインバウンド通信を再マッピングします。PORT_REMAP_INBOUND を指定して PORT_REMAP に値を指定しなかった場合は、ポートのアウトバウンド通信が変更されません。
+

IMPORTANT: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。



使用される形式は次のとおりです。 `_network type_/_protocol/_default port used by grid node_/_new port_`network typeはgrid、admin、clientのいずれかで、protocolはTCPまたはUDPです。

例：

[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
次の例は、ポート 443 に送信されたトラフィックを内部ファイアウォールを通過させ、グリッドノードが S3 要求をリスンしているポート 18082 に転送します。



== ノード固有のパラメータ

構成ファイルには、各ノード専用のセクションがあります。各ノードには次の設定が必要です。

* セクションヘッドでは、 Grid Manager に表示されるノード名を定義します。この値を無視するには、ノードに対してオプションの node_name パラメータを指定します。
* * node_name * ： VM_Admin_Node 、 VM_Storage_Node 、 VM_Archive_Node 、 VM_API_Gateway_Node のいずれか
* * GRID_NETWORK_IP * ：グリッドネットワークでのノードの IP アドレス。
* * ADMIN_NETWORK_IP * ：管理ネットワークでのノードの IP アドレス。ノードが管理ネットワークに接続され、かつ ADMIN_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * client_network_ip * ：クライアントネットワーク上のノードの IP アドレス。ノードがクライアントネットワークに接続され、かつノードの CLIENT_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * ADMIN_IP * ：グリッドネットワークでのプライマリ管理ノードの IP アドレス。プライマリ管理ノードの GRID_NETWORK_IP で指定した値を使用します。このパラメータを省略すると、ノードは mDNS を使用してプライマリ管理ノードの IP を検出しようとします。詳細については、を参照してください link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"]。
+

NOTE: プライマリ管理ノードでは ADMIN_IP パラメータが無視されます。

* グローバルに設定されていないすべてのパラメータ。たとえば、ノードが管理ネットワークに接続されていて、 ADMIN_NETWORK_NETWORK パラメータをグローバルに指定していない場合は、ノードに対してそれらのパラメータを指定する必要があります。




== プライマリ管理ノード

プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：プライマリ


次のエントリ例は、プライマリ管理ノードが 3 つのネットワークすべてに接続される場合を示しています。

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。



== ストレージノード

ストレージノードには次の設定を追加する必要があります。

* * node_name * ： VM_Storage_Node
+
次のエントリ例は、ストレージノードがグリッドネットワークと管理ネットワークに接続され、クライアントネットワークに接続されない場合を示しています。このノードでは、 ADMIN_IP 設定を使用してグリッドネットワークでのプライマリ管理ノードの IP アドレスを指定しています。

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
2 番目のエントリ例は、ストレージノードがクライアントネットワークに接続される場合を示しています。ここでは、 S3 クライアントアプリケーションがストレージノードへのアクセスに使用できるポートが、ユーザのエンタープライズネットワークポリシーによって 80 または 443 に制限されています。この例の構成ファイルでは、 PORT_REMAP を使用して、ストレージノードがポート 443 で S3 メッセージを送受信できるようにしています。

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
最後の例では、 ssh トラフィックに対してポート 22 からポート 3022 への対称的な再マッピングが作成されますが、インバウンドとアウトバウンドの両方のトラフィックに明示的に値が設定されます。

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


ストレージノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、ストレージノードに対して RangeDB 用に 3 つの 4TB ディスクが割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----




== アーカイブノード

アーカイブノードには次の設定を追加する必要があります。

* * node_name * ： VM_Archive_Node


次のエントリ例は、アーカイブノードがグリッドネットワークと管理ネットワークに接続され、クライアントネットワークに接続されない場合を示しています。

[listing]
----
[DC1-ARC1]
  NODE_TYPE = VM_Archive_Node

  GRID_NETWORK_IP = 10.1.0.4
  ADMIN_NETWORK_IP = 10.3.0.4

  ADMIN_IP = 10.1.0.2
----


== ゲートウェイノード

ゲートウェイノードには次の設定を追加する必要があります。

* * node_name * ： VM_API_Gateway


次のエントリ例は、ゲートウェイノードが 3 つのネットワークすべてに接続される場合を示しています。この例では、構成ファイルのグローバルセクションでクライアントネットワークのパラメータが指定されていないため、ノードに対してそれらのパラメータを指定する必要があります。

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG-Client-Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----


== 非プライマリ管理ノード

非プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：非プライマリ


次のエントリ例は、非プライマリ管理ノードがクライアントネットワークに接続されない場合を示しています。

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG-Grid-Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
非プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。

.関連情報
link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"]

link:../network/index.html["ネットワークのガイドライン"]
