---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, vmware, download installation files, downloading installation files 
summary: StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。 
---
= StorageGRID インストールファイルのダウンロードと展開
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。

.手順
. ネットアップの StorageGRID ダウンロードページにアクセスします。
+
https://["ネットアップのダウンロード： StorageGRID"^]

. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. 「注意 / 必ずお読みください」という記述が表示されたら、それを読んでチェックボックスを選択してください。
+
StorageGRID リリースのインストール後に、必要な修正プログラムを適用する必要があります。詳細については、リカバリおよびメンテナンスの手順にあるホットフィックス手順 を参照してください。

. エンドユーザライセンス契約を読み、チェックボックスをオンにして、「 * 同意して続行 * 」を選択します。
. [Install StorageGRID *（インストールソフトウェアのインストール）]列で、適切なソフトウェアを選択します。
+
をダウンロードします `.tgz` または `.zip` 使用するプラットフォームに対応したアーカイブファイルです。

+
** `StorageGRID-Webscale-version-VMware-uniqueID.zip`
** `StorageGRID-Webscale-version-VMware-uniqueID.tgz`





NOTE: を使用します `.zip` ファイルサービスラップトップでWindowsを実行している場合。

. アーカイブファイルを保存して展開します。
. 次のリストから必要なファイルを選択します。
+
必要なファイルは、計画したグリッドトポロジおよび StorageGRID システムの導入方法によって異なります。




NOTE: 次の表に示すパスは、展開されたインストールアーカイブによってインストールされた最上位ディレクトリに対する相対パスです。

[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./vsphere/README （ ./vsphere/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./vsphere/NLF000000.txt にアクセスします  a| 
製品サポートのない無償ライセンス。



| ./vsphere/NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere-primary-admin.mf  a| 
Open Virtualization Formatテンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を使用してください。



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）。非プライマリ管理ノードを導入する場合に使用します。



| ./vsphere/vsphere-archive.ovf ./vsphere-archive.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を使用してアーカイブノードを導入します。



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を選択します。



| ./vsphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を選択します。



| 導入スクリプトツール | 説明 


| ./vsphere/deploy-vsphere-ovftool.sh にアクセスします  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| ./vsphere/deploy-vsphere-ovftool-sample.ini にアクセスします  a| 
で使用するサンプル構成ファイル `deploy-vsphere-ovftool.sh` スクリプト：



| ./vsphere/configure-storagegrid.py にアクセスします  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./vsphere/configure-sga.py にアクセスします  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./vsphere/storagegrid-ssoauth.py にアクセスします  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./vsphere/configure -storagegrid-sample.json という形式で実行します  a| 
で使用するサンプル構成ファイル `configure-storagegrid.py` スクリプト：



| ./vsphere/configure -storagegrid-bank.json （ページ構成  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：

|===
.関連情報
link:../maintain/index.html[""]
