---
permalink: rhel/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords:  
summary: グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。 
---
= StorageGRID の設定の自動化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.必要なもの
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
|===
| ファイル名 | 説明 


 a| 
`configure-storagegrid.py`
 a| 
設定を自動化するための Python スクリプト



 a| 
`configure-storagegrid.sample.json`
 a| 
スクリプトで使用するサンプル構成ファイル



 a| 
`configure-storagegrid.blank.json`
 a| 
スクリプトで使用する空の構成ファイルです

|===
* を作成しておきます `configure-storagegrid.json` 構成ファイルこのファイルを作成するには、サンプル構成ファイルを変更します (`configure-storagegrid.sample.json`)または空の構成ファイル (`configure-storagegrid.blank.json`）。


.このタスクについて
を使用できます `configure-storagegrid.py` Pythonスクリプトおよび `configure-storagegrid.json` StorageGRID システムの設定を自動化するための構成ファイル。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
ここで、 `platform` はです `debs`、 `rpms`または `vsphere`。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
リカバリパッケージ `.zip` 設定プロセスでファイルが生成され、インストールと設定を実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、を展開する必要があります `Passwords.txt` ファイルを開き、StorageGRID システムへのアクセスに必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
link:configuring-grid-and-completing-installation.html["グリッドの設定とインストールの完了"]

link:overview-of-installation-rest-api.html["インストール REST API の概要"]
