---
permalink: rhel/configuring-host-network.html 
sidebar: sidebar 
keywords:  
summary: ホストへの Linux のインストールの完了後、このあとに導入する StorageGRID ノードにマッピングする一連のネットワークインターフェイスを準備するために、各ホストでいくつかの追加の設定が必要になることがあります。 
---
= ホストネットワークを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストへの Linux のインストールの完了後、このあとに導入する StorageGRID ノードにマッピングする一連のネットワークインターフェイスを準備するために、各ホストでいくつかの追加の設定が必要になることがあります。

.必要なもの
* StorageGRID のネットワークに関するガイドラインを確認しておきます。
+
link:../network/index.html["ネットワークガイドライン"]

* ノードコンテナの移行要件に関する情報を確認しておく必要があります。
+
link:node-container-migration-requirements.html["ノードコンテナの移行要件"]

* 仮想ホストを使用している場合は、MACアドレスのクローニングに関する考慮事項と推奨事項を確認してから、ホストネットワークを設定してください。
+
link:considerations-and-recommendations-for-mac-address-cloning.html["MAC アドレスのクローニングに関する考慮事項と推奨事項"]




NOTE: VM をホストとして使用する場合は、仮想ネットワークアダプタとして VMXNET 3 を選択する必要があります。VMware E1000 ネットワークアダプタは、特定の Linux のディストリビューションで導入された StorageGRID コンテナで接続の問題が発生しました。

.このタスクについて
グリッドノードは、グリッドネットワークにアクセスできる必要があります。また、管理ネットワークとクライアントネットワークにアクセスすることもできます。このアクセスを確立するには、ホストの物理インターフェイスを各グリッドノードの仮想インターフェイスに関連付けるマッピングを作成します。ホストインターフェイスを作成するときにわかりやすい名前を使用すると、すべてのホストへの導入が簡単になり、移行も可能になります。

ホストと 1 つ以上のノードで、同じインターフェイスを共有できます。たとえば、ホストアクセス用とノード管理ネットワークアクセス用のインターフェイスに同じものを使用すると、ホストとノードをメンテナンスしやすくなります。ホストと個々のノードで同じインターフェイスを共有できますが、 IP アドレスはすべて異なっている必要があります。IP アドレスはノード間やホストと任意のノード間で共有できません。

グリッドネットワークのインターフェイスについては、ホストのすべての StorageGRID ノードで同じホストネットワークインターフェイスを使用したり、ノードごとに異なるホストネットワークインターフェイスを使用したり、任意のインターフェイスを使用したりできます。ただし、通常は、単一のホストのグリッドネットワークと管理ネットワークの両方のインターフェイス、またはいずれかのノードのグリッドネットワークのインターフェイスと別のホストのクライアントネットワークのインターフェイスに同じホストネットワークインターフェイスを使用することはありません。

このタスクはさまざまな方法で実行できます。たとえば、仮想マシンをホストとする環境でホストごとに 1 つまたは 2 つの StorageGRID ノードを導入する場合は、ハイパーバイザーで正しい数のネットワークインターフェイスを作成し、 1 対 1 のマッピングを使用できます。本番環境用のベアメタルホストに複数のノードを導入する場合は、 Linux ネットワークスタックの VLAN と LACP のサポートを利用してフォールトトレランスと帯域幅の共有を実現できます。以降のセクションでは、これら両方の例について詳細なアプローチを紹介します。これらのいずれかを使用する必要はありません。それぞれのニーズに合わせてアプローチを選択できます。


NOTE: ボンドデバイスやブリッジデバイスをコンテナネットワークインターフェイスとして直接使用しないでください。これにより、カーネル問題 が原因で発生するノードの起動が妨げられ、コンテナネームスペース内のボンドデバイスおよびブリッジデバイスで MACVLAN が使用される可能性があります。代わりに、 VLAN ペアや仮想イーサネット（ veth ）ペアなどの非ボンディングデバイスを使用してください。このデバイスをノード構成ファイルのネットワークインターフェイスとして指定してください。

.関連情報
link:../network/index.html["ネットワークガイドライン"]

link:node-container-migration-requirements.html["ノードコンテナの移行要件"]

link:creating-node-configuration-files.html["ノード構成ファイルを作成しています"]
