---
permalink: rhel/considerations-and-recommendations-for-mac-address-cloning.html 
sidebar: sidebar 
keywords:  
summary: MACアドレスのクローニングでは、DockerコンテナでホストのMACアドレスが使用され、指定したアドレスまたはランダムに生成されたアドレスのMACアドレスがホストで使用されます。プロミスキャスモードのネットワーク設定を使用しないようにするには、 MAC アドレスのクローニングを使用します。 
---
= MAC アドレスのクローニングに関する考慮事項と推奨事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MACアドレスのクローニングでは、DockerコンテナでホストのMACアドレスが使用され、指定したアドレスまたはランダムに生成されたアドレスのMACアドレスがホストで使用されます。プロミスキャスモードのネットワーク設定を使用しないようにするには、 MAC アドレスのクローニングを使用します。



== MAC クローニングのイネーブル化

環境によっては、管理ネットワーク、グリッドネットワーク、およびクライアントネットワークに専用の仮想 NIC を使用できるため、 MAC アドレスのクローニングによってセキュリティを強化できます。Dockerコンテナでホスト上の専用NICのMACアドレスを使用すると、プロミスキャスモードのネットワーク設定を回避できます。


IMPORTANT: MAC アドレスクローニングは、仮想サーバ環境で使用するためのものであり、物理アプライアンスのすべての構成で正常に機能しない場合があります。


NOTE: MAC クローニングのターゲットインターフェイスがビジー状態のためにノードを起動できない場合は、ノードを起動する前にリンクを「停止」に設定しなければならないことがあります。また、リンクが稼働しているときに仮想環境でネットワークインターフェイス上の MAC クローニングが実行されないことがあります。インターフェイスがビジーなためにノードで MAC アドレスの設定が失敗してノードが起動しなかった場合は、問題 を修正する前にリンクを「停止」に設定することがあります。

MAC アドレスクローニングは、デフォルトでは無効になっており、ノード設定キーで設定する必要があります。StorageGRID をインストールするときに有効にする必要があります。

ネットワークごとに 1 つのキーがあります。

* `ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC`
* `GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC`
* `CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC`


キーを「true」に設定すると、DockerコンテナでホストのNICのMACアドレスが使用されます。さらに、ホストは指定されたコンテナネットワークの MAC アドレスを使用します。デフォルトでは、コンテナアドレスはランダムに生成されたアドレスですが、を使用して設定した場合は、です `_NETWORK_MAC` ノード設定キー。アドレスを代わりに使用します。ホストとコンテナの MAC アドレスは常に異なります。


IMPORTANT: ハイパーバイザーでプロミスキャスモードも有効にせずに仮想ホストの MAC クローニングを有効にすると、ホストのインターフェイスを使用して原因 Linux ホストのネットワークが停止する可能性があります。



== MAC クローン作成の使用例

MAC クローニングでは、次の 2 つのユースケースを検討します。

* MACクローン作成が有効になっていない場合 `_CLONE_MAC` ノード構成ファイルのキーが設定されていないか「false」に設定されていない場合、ホストはホストNIC MACを使用し、にMACを指定しないかぎりコンテナにStorageGRIDによって生成されたMACが含まれます `_NETWORK_MAC` キーを押します。アドレスがに設定されている場合 `_NETWORK_MAC` キーを指定すると、コンテナのアドレスがに指定されます `_NETWORK_MAC` キーを押します。このキーの設定では、プロミスキャスモードを使用する必要があります。
* MACクローン作成が有効になっている場合 `_CLONE_MAC` ノード構成ファイルのキーは「true」に設定されています。コンテナではホストNIC MACを使用し、でMACを指定しないかぎりStorageGRIDによって生成されたMACをホストで使用します `_NETWORK_MAC` キーを押します。アドレスがに設定されている場合 `_NETWORK_MAC` キー。ホストは、生成されたアドレスではなく、指定されたアドレスを使用します。このキーの設定では、プロミスキャスモードは使用しないでください。



NOTE: MAC アドレスのクローニングを使用せずに、ハイパーバイザーによって割り当てられた MAC アドレス以外の MAC アドレスのデータをすべてのインターフェイスが送受信できるようにする場合は、次の手順を実行します。 仮想スイッチおよびポートグループレベルのセキュリティプロパティが、無差別モード、 MAC アドレスの変更、および Forged Transmits の *Accept* に設定されていることを確認します。仮想スイッチに設定された値は、ポートグループレベルの値によって上書きできるため、両方のレベルで設定が同じであることを確認してください。

MAC クローニングをイネーブルにするには、を参照してください link:creating-node-configuration-files.html["ノード構成ファイルの作成手順"]。



== MAC クローニングの例

MAC アドレスが 11 ： 22 ： 33 ： 44 ： 55 ： 66 のホストでインターフェイス ens256 の MAC クローニングをイネーブルにし、ノード構成ファイルで次のキーを使用する例：

* `ADMIN_NETWORK_TARGET = ens256`
* `ADMIN_NETWORK_MAC = b2:9c:02:c2:27:10`
* `ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC = true`


* 結果 * ： ens256 のホスト MAC は b2 ： 9C ： 02 ： c2 ： 27 ： 10 で、管理ネットワーク MAC は 11 ： 22 ： 33 ： 44 ： 55 ： 66 です
