---
permalink: rhel/installation-overview.html 
sidebar: sidebar 
keywords: storagegrid, rhel installation, redhat installation, redhat linux, centos installation 
summary: Red Hat Enterprise Linux \（RHEL \）またはCentOS Linux環境へのStorageGRID システムのインストールは、主に3つの手順で行われます。 
---
= インストールの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Red Hat Enterprise Linux （ RHEL ）環境または CentOS Linux 環境への StorageGRID システムのインストールは、主に 3 つの手順で行われます。

. * 準備 * ：計画と準備の際に、次のタスクを実行します。
+
** StorageGRID のハードウェア要件とストレージ要件について説明します。
** ネットワークを適切に設定するためのStorageGRID ネットワークの詳細について説明します。詳細については、StorageGRID のネットワークに関するガイドラインを参照してください。
** StorageGRID グリッドノードのホストとして使用する物理サーバまたは仮想サーバを決めて準備する。
** 準備したサーバで、次の作業を行います。
+
*** Linux をインストールします
*** ホストネットワークを設定する
*** ホストストレージを設定する
*** Docker をインストールする
*** StorageGRID ホストサービスをインストールする




. * 導入 * ：適切なユーザインターフェイスを使用してグリッドノードを導入します。導入したグリッドノードは、 StorageGRID システムの一部として作成され、 1 つ以上のネットワークに接続されます。
+
.. Linux のコマンドライン構成ファイルとノード構成ファイルを使用して、手順 1 で準備したホストにソフトウェアベースのグリッドノードを導入します。
.. StorageGRID アプライアンスノードを導入するには、 StorageGRID アプライアンスインストーラを使用します。
+

NOTE: ハードウェア固有の設置と統合の手順は、 StorageGRID インストール手順 には含まれていません。StorageGRID アプライアンスのインストール方法については、使用するアプライアンスのインストールとメンテナンスの手順を参照してください。



. *構成*：すべてのノードが導入されたら、StorageGRIDWebscaleを使ってグリッドを構成し、インストールを完了します。


ここでは、標準的なアプローチで StorageGRID システムを導入して設定する方法を推奨します。次の代替アプローチに関する情報も参照してください。

* Ansible、Puppet、Chefなどの標準的なオーケストレーションフレームワークを使用して、RHELまたはCentOSのインストール、ネットワークとストレージの設定、DockerとStorageGRID ホストサービスのインストール、および仮想グリッドノードの導入を行う。
* Python 設定スクリプト（インストールアーカイブに付属）を使用して、 StorageGRID システムの導入と設定を自動化します。
* Python 設定スクリプト（インストールアーカイブまたは StorageGRID アプライアンスインストーラで入手可能）を使用して、アプライアンスグリッドノードの導入と設定を自動化する。
* StorageGRID 環境を高度に開発する場合は、インストール REST API を使用して StorageGRID グリッドノードのインストールを自動化します。


.関連情報
link:planning-and-preparation.html["計画と準備"]

link:deploying-virtual-grid-nodes.html["仮想グリッドノードの導入"]

link:configuring-grid-and-completing-installation.html["グリッドの設定とインストールの完了"]

link:automating-installation.html["インストールの自動化"]

link:overview-of-installation-rest-api.html["インストール REST API の概要"]

link:../network/index.html["ネットワークガイドライン"]
