---
permalink: admin/creating-tenant-account-if-sso-is-enabled.html 
sidebar: sidebar 
keywords:  
summary: テナントアカウントを作成する際は、名前、クライアントプロトコル、およびオプションでストレージクォータを指定します。StorageGRID でシングルサインオン\（SSO \）が有効になっている場合は、テナントアカウントを設定するためのRoot Access権限が割り当てられているフェデレーテッドグループも指定します。 
---
= SSOが有効な場合のテナントアカウントの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントアカウントを作成する際は、名前、クライアントプロトコル、およびオプションでストレージクォータを指定します。StorageGRID でシングルサインオン（SSO）が有効になっている場合は、テナントアカウントを設定するためのRoot Access権限が割り当てられているフェデレーテッドグループも指定します。

.手順
. [*表示名*]テキストボックスに、このテナントアカウントの表示名を入力します。
+
表示名は一意である必要はありません。作成したテナントアカウントには、一意の数値アカウントIDが割り当てられます。

. このテナントアカウントで使用するクライアントプロトコルとして、* S3 *または* Swift *を選択します。
. S3テナントアカウントの場合は、このテナントでS3バケットにプラットフォームサービスを使用しないようにする場合を除き、プラットフォームサービスの許可*チェックボックスをオンのままにしておきます。
+
プラットフォームサービスが有効になっている場合、テナントは外部サービスにアクセスする CloudMirror レプリケーションなどの機能を使用できます。これらの機能の使用を無効にすることで、テナントが消費するネットワーク帯域幅またはその他のリソースの量を制限できます。「プラットフォームサービスの管理」を参照してください。

. [*ストレージクォータ*]テキストボックスに、このテナントのオブジェクトで使用可能にする最大ギガバイト数、テラバイト数、またはペタバイト数をオプションで入力します。次に、ドロップダウンリストから単位を選択します。
+
このテナントのクォータを無制限にする場合は、このフィールドを空白のままにします。

+

NOTE: テナントのストレージクォータは、物理容量（ディスクのサイズ）ではなく、論理容量（オブジェクトのサイズ）を表します。ILMのコピーおよびイレイジャーコーディングは、クォータの使用量にはカウントされません。クォータを超過すると、テナントアカウントは新しいオブジェクトを作成できなくなります。

+

NOTE: 各テナントアカウントのストレージ使用状況を監視するには、「*使用状況*」を選択します。テナントアカウントは、Tenant Managerのダッシュボードまたはテナント管理APIを使用してストレージ使用状況を監視することもできます。ノードがグリッド内の他のノードから切断されていると、テナントのストレージ使用状況の値が最新ではなくなる場合があります。合計はネットワーク接続が回復すると更新されます。

. [独自のアイデンティティソースを使用する*]チェックボックスがオフになっており、無効になっていることに注意してください。
+
SSOが有効であるため、テナントはGrid Manager用に設定されたアイデンティティソースを使用する必要があります。ローカルユーザはサインインできません。

. [* Root Access Group]フィールドで、テナントに対する最初のRoot Access権限を持つ既存のフェデレーテッドグループをGrid Managerから選択します。
+

NOTE: 適切な権限がある場合は、フィールドをクリックすると、Grid Managerから既存のフェデレーテッドグループが表示されます。それ以外の場合は、グループの一意の名前を入力します。

. [ 保存（ Save ） ] をクリックします。
+
テナントアカウントが作成されます。Tenant Accountsページが表示され、新しいテナントの行が追加されます。

. Root Accessグループのユーザは、必要に応じて新しいテナントの* Sign In *リンクをクリックしてTenant Managerにすぐにアクセスし、テナントを設定できます。それ以外の場合は、テナントアカウントの管理者に*サインイン*リンクのURLを提供します。（テナントのURLは、いずれかの管理ノードの完全修飾ドメイン名またはIPアドレスのあとにを追加したものです `/?accountId=_20-digit-account-id_`. ）
+

NOTE: テナントアカウントのRoot Accessグループに属していない場合は、* Sign In *をクリックするとアクセス拒否のメッセージが表示されます。



.関連情報
link:configuring-sso.html["シングルサインオンを設定しています"]

link:managing-platform-services-for-s3-tenant-accounts.html["S3テナントアカウント用のプラットフォームサービスの管理"]

link:../tenant/index.html["テナントアカウントを使用する"]
