---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords:  
summary: ハイアベイラビリティ（HA）グループはいくつかの理由で使用できます。 
---
= HAグループの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハイアベイラビリティ（HA）グループはいくつかの理由で使用できます。

* HA グループは、 Grid Manager または Tenant Manager への可用性の高い管理接続を提供します。
* HA グループは、 S3 / Swift クライアントに可用性の高いデータ接続を提供できます。
* インターフェイスが 1 つしかない HA グループでは、多数の VIP アドレスを指定したり、 IPv6 アドレスを明示的に設定したりできます。


HA グループは、グループに含まれるすべてのノードが同じサービスを提供する場合にのみ高可用性を提供できます。HA グループを作成するときは、必要なサービスを提供するタイプのノードからインターフェイスを追加してください。

* * 管理ノード * ：ロードバランササービスが含まれ、 Grid Manager またはテナントマネージャへのアクセスを有効にします。
* * ゲートウェイノード * ：ロードバランササービスと CLB サービス（廃止）が含まれます。


[cols="1a,1a"]
|===
| HA グループの目的 | このタイプのノードを HA グループに追加します 


 a| 
Grid Manager へのアクセス
 a| 
* プライマリ管理ノード（*優先マスター*）
* 非プライマリ管理ノード


*注：*プライマリ管理ノードが優先マスターである必要があります。一部のメンテナンス手順は、プライマリ管理ノードでしか実行できません。



 a| 
Tenant Manager のみにアクセスします
 a| 
* プライマリ管理ノードまたは非プライマリ管理ノード




 a| 
S3 または Swift クライアントアクセス - ロードバランササービス
 a| 
* 管理ノード
* ゲートウェイノード




 a| 
S3 または Swift クライアントアクセス - CLB サービス

* 注： * CLB サービスは廃止されました。
 a| 
* ゲートウェイノード


|===


== Grid Manager または Tenant Manager で HA グループを使用する場合の制限事項

Grid ManagerまたはTenant Managerのサービスで障害が発生しても、HAグループ内でフェイルオーバーはトリガーされません。

フェイルオーバーの発生時に Grid Manager または Tenant Manager にサインインしている場合はサインアウトされるため、再度サインインしてタスクを再開する必要があります。

プライマリ管理ノードを使用できない場合は、一部のメンテナンス手順を実行できません。フェイルオーバー中は、 Grid Manager を使用して StorageGRID システムを監視できます。



== CLB サービスで HA グループを使用する場合の制限事項

CLB サービスに障害が発生しても、 HA グループ内でフェイルオーバーはトリガーされません。


NOTE: CLB サービスは廃止されました。
