---
permalink: admin/managing-local-users.html 
sidebar: sidebar 
keywords:  
summary:  
---
= ローカルユーザの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルユーザを作成してローカル管理者グループに割り当て、そのユーザがアクセスできるGrid Manager機能を決定することができます。

Grid Managerには'ルートという名前の'事前定義されたローカル・ユーザが1つ含まれていますローカルユーザは追加および削除できますが、rootユーザを削除することはできません。


NOTE: シングルサインオン（SSO）が有効になっている場合、ローカルユーザはStorageGRID にサインインできません。

* Grid Managerにはサポートされているブラウザを使用してサインインする必要があります。
* 特定のアクセス権限が必要です。




== ローカルユーザを作成しています

ローカル管理者グループを作成した場合は、1人以上のローカルユーザを作成し、各ユーザを1つ以上のグループに割り当てることができます。このグループの権限は、ユーザがアクセスできるGrid Manager機能を制御します。

.このタスクについて
作成できるのはローカルユーザだけで、作成したユーザはローカル管理者グループにのみ割り当てることができます。フェデレーテッドユーザとフェデレーテッドグループは、外部のアイデンティティソースを使用して管理されます。

.手順
. [*構成*（Configuration *）]>[*アクセス制御*（* Access Control *）]>[*管理者ユーザー*（* Admin Users *）
. [ 作成（ Create ） ] をクリックします。
. ユーザの表示名、一意の名前、およびパスワードを入力します。
. アクセス権限を制御する1つ以上のグループにユーザを割り当てます。
+
グループ名のリストは'グループ(Groups)テーブルから生成されます

. [ 保存（ Save ） ] をクリックします。


.関連情報
link:managing-admin-groups.html["管理者グループの管理"]



== ローカルユーザアカウントの変更

ローカル管理者ユーザのアカウントを変更して、ユーザの表示名またはグループメンバーシップを更新できます。ユーザが一時的にシステムにアクセスできないように設定することもできます。

.このタスクについて
編集できるのはローカルユーザのみです。フェデレーテッドユーザの詳細は、外部のアイデンティティソースと自動的に同期されます。

.手順
. [*構成*（Configuration *）]>[*アクセス制御*（* Access Control *）]>[*管理者ユーザー*（* Admin Users *）
. 編集するユーザを選択します。
+
システムに20個を超えるアイテムが含まれている場合は、各ページに一度に表示する行数を指定できます。その後、ブラウザの検索機能を使用して、現在表示されている行の特定の項目を検索できます。

. [ 編集（ Edit ） ] をクリックします。
. 必要に応じて、名前またはグループメンバーシップを変更します。
. 必要に応じて、ユーザが一時的にシステムにアクセスできないようにするには、*アクセス拒否*をオンにします。
. [ 保存（ Save ） ] をクリックします。
+
新しい設定は、次回ユーザがグリッドマネージャからサインアウトして再度サインインしたときに適用されます。





== ローカルユーザのアカウントを削除する

Grid Managerへのアクセスが不要になったローカルユーザのアカウントを削除できます。

.手順
. [*構成*（Configuration *）]>[*アクセス制御*（* Access Control *）]>[*管理者ユーザー*（* Admin Users *）
. 削除するローカルユーザを選択します。
+

NOTE: 事前定義されたrootローカルユーザは削除できません。

+
システムに20個を超えるアイテムが含まれている場合は、各ページに一度に表示する行数を指定できます。その後、ブラウザの検索機能を使用して、現在表示されている行の特定の項目を検索できます。

. [ 削除（ Remove ） ] をクリックします。
. [OK] をクリックします。




== ローカルユーザのパスワードを変更する

ローカルユーザは、 Grid Manager のバナーで * Change Password * オプションを使用して自分のパスワードを変更できます。また、Admin Usersページへのアクセス権を持つユーザは、他のローカルユーザのパスワードを変更できます。

.このタスクについて
変更できるのはローカルユーザのパスワードのみです。フェデレーテッドユーザは、自分のパスワードを外部のアイデンティティソース内で変更する必要があります。

.手順
. [*構成*（Configuration *）]>[*アクセス制御*（* Access Control *）]>[*管理者ユーザー*（* Admin Users *）
. [ユーザー]ページで、ユーザーを選択します。
+
システムに20個を超えるアイテムが含まれている場合は、各ページに一度に表示する行数を指定できます。その後、ブラウザの検索機能を使用して、現在表示されている行の特定の項目を検索できます。

. [パスワードの変更*]をクリックします。
. パスワードを入力して確認し、*保存*をクリックします。

