---
permalink: admin/monitoring-data-migration.html 
sidebar: sidebar 
keywords:  
summary: 所定の期間内にILMポリシーに従ってデータが配置されるよう、必要に応じてデータ移行を監視し、調整する必要があります。 
---
= データ移行の監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所定の期間内にILMポリシーに従ってデータが配置されるよう、必要に応じてデータ移行を監視し、調整する必要があります。

次の表に、データ移行中に監視する必要がある属性とその内容を示します。

取り込み速度を抑制するためにレート制限を指定したトラフィック分類ポリシーを使用する場合は、次の表に示す統計情報とともに、観察されたレートを監視し、必要に応じて制限を減らすことができます。

[cols="1a,2a"]
|===
| モニタ | 説明 


 a| 
ILM による評価を待機しているオブジェクトの数
 a| 
. Support *>* Tools *>* Grid Topology *を選択します。
. [*_deployment_***概要*Main*]を選択します。
. ILM アクティビティセクションで、次の属性について表示されるオブジェクトの数を監視します。
+
** * Awaiting - All （ XQUZ ） * ： ILM による評価を待機しているオブジェクトの合計数です。
** * Awaiting - Client （ XCQZ ） * ：クライアント処理（取り込みなど）から ILM による評価を待機しているオブジェクトの合計数です。


. これらの属性のどちらかに対して表示されるオブジェクトの数が 100 、 000 を超えた場合は、オブジェクトの取り込み速度を調整して、 StorageGRID システムへの負荷を軽減してください。




 a| 
ターゲットアーカイブシステムのストレージ容量
 a| 
ILM ポリシーによって、移行対象データのコピーがターゲットアーカイブストレージシステム（テープまたはクラウド）に保存される場合は、ターゲットアーカイブストレージシステムの容量を監視して、移行対象データ用の十分な容量が確保されていることを確認してください。



 a| 
*アーカイブノード* ARC * Store *
 a| 
「 Store Failures （ ARVF ） * 」属性のアラームがトリガーされた場合、対象のアーカイブストレージシステムの容量が上限に達している可能性があります。ターゲットアーカイブストレージシステムをチェックして、アラームをトリガーした問題を解決してください。

|===