---
permalink: admin/temporarily-disabling-and-reenabling-sso-for-admin-node.html 
sidebar: sidebar 
keywords:  
summary: シングルサインオン \ （ SSO \ ）システムが停止すると、 Grid Manager にサインインできない可能性があります。この場合は、 1 つの管理ノードに対して SSO を一時的に無効にしてから再度有効にすることができます。SSO を無効にしてから再度有効にするには、ノードのコマンドシェルにアクセスする必要があります。 
---
= 1つの管理ノードのシングルサインオンの一時的な無効化と再有効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シングルサインオン（ SSO ）システムが停止すると、 Grid Manager にサインインできない場合があります。この場合は、 1 つの管理ノードに対して SSO を一時的に無効にしてから再度有効にすることができます。SSO を無効にしてから再度有効にするには、ノードのコマンドシェルにアクセスする必要があります。

.必要なもの
* 特定のアクセス権限が必要です。
* を用意しておく必要があります `Passwords.txt` ファイル。
* ローカルのrootユーザのパスワードを確認しておく必要があります。


.このタスクについて
1 つの管理ノードに対して SSO を無効にすると、ローカルの root ユーザとして Grid Manager にサインインできます。StorageGRID システムを保護するために、ノードのコマンドシェルを使用してサインアウト後すぐに管理ノードの SSO を再度有効にする必要があります。


IMPORTANT: 1 つの管理ノードに対して SSO を無効にしても、グリッド内の他の管理ノードの SSO 設定には影響しません。Grid Manager のシングルサインオンページの * SSO * を有効にするチェックボックスはオンのままで、既存の SSO 設定はすべて更新しないかぎり維持されます。

.手順
. 管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@Admin_Node_IP`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 次のコマンドを実行します。``disable-saml``
+
環境 this admin Node only コマンドのメッセージが表示されます。

. SSO を無効にすることを確認します。
+
ノードでシングルサインオンが無効になったことを示すメッセージが表示されます。

. Web ブラウザから、同じ管理ノード上の Grid Manager にアクセスする。
+
SSO を無効にしたため、 Grid Manager のサインインページが表示されます。

. ユーザ名「 root 」とローカルの root ユーザのパスワードを使用してサインインします。
. SSO 設定の修正が必要なために SSO を一時的に無効にした場合は、次の手順を実行します
+
.. 「* Configuration * Access Control * Single Sign-On *」を選択します。
.. 正しくない SSO 設定または古い SSO 設定を変更します。
.. [ 保存（ Save ） ] をクリックします。
+
シングルサインオンページで* Save *をクリックすると、グリッド全体でSSOが自動的に再有効化されます。



. 他の理由で Grid Manager へのアクセスが必要であったために SSO を一時的に無効にした場合は、次の手順を実行します。
+
.. 必要なタスクを実行します。
.. [*サインアウト*]をクリックして、Grid Managerを閉じます。
.. 管理ノードで SSO を再度有効にします。次のいずれかの手順を実行します。
+
*** 次のコマンドを実行します。 `enable-saml`
+
環境 this admin Node only コマンドのメッセージが表示されます。

+
SSO を有効にすることを確認します。

+
ノードでシングルサインオンが有効になったことを示すメッセージが表示されます。

*** グリッドノードをリブートします。 `reboot`




. Web ブラウザから、同じ管理ノードから Grid Manager にアクセスする。
. StorageGRID のサインインページが表示され、グリッドマネージャにアクセスするには SSO クレデンシャルを入力する必要があることを確認します。


.関連情報
link:configuring-sso.html["シングルサインオンを設定しています"]
