---
permalink: admin/using-storagegrid-security-certificates.html 
sidebar: sidebar 
keywords:  
summary: セキュリティ証明書は、 StorageGRID コンポーネント間、および StorageGRID コンポーネントと外部システム間のセキュアで信頼された接続の確立に使用される小さいデータファイルです。 
---
= StorageGRID セキュリティ証明書を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ証明書は、 StorageGRID コンポーネント間、および StorageGRID コンポーネントと外部システム間のセキュアで信頼された接続の確立に使用される小さいデータファイルです。

StorageGRID では、 2 種類のセキュリティ証明書が使用されます。

* * HTTPS 接続を使用する場合は、サーバー証明書 * が必要です。サーバ証明書は、クライアントとサーバ間のセキュアな接続を確立し、クライアントに対するサーバの ID を認証し、データのセキュアな通信パスを提供するために使用されます。サーバとクライアントには、それぞれ証明書のコピーがあります。
* * クライアント証明書 * は、クライアントまたはユーザー ID をサーバーに対して認証し、パスワードだけではなく、より安全な認証を提供します。クライアント証明書はデータを暗号化しません。


クライアントが HTTPS を使用してサーバに接続すると、サーバはサーバ証明書を返します。このサーバ証明書には公開鍵が含まれています。クライアントは、サーバの署名と証明書のコピーの署名を比較して、この証明書を検証します。署名が一致した場合、クライアントは同じ公開鍵を使用してサーバとのセッションを開始します。

StorageGRID は、一部の接続（ロードバランサエンドポイントなど）のサーバとして、または他の接続（ CloudMirror レプリケーションサービスなど）のクライアントとして機能します。

外部の認証局（ CA ）は、組織の情報セキュリティポリシーに完全に準拠した問題 カスタム証明書を作成できます。StorageGRID には、システムのインストール時に内部CA証明書を生成するCAも組み込まれています。デフォルトでは、これらの内部CA証明書を使用して、内部StorageGRID トラフィックが保護されます。非本番環境では内部CA証明書を使用できますが、本番環境では外部の認証局が署名したカスタム証明書を使用することを推奨します。証明書なしのセキュアでない接続もサポートされますが、推奨されません。

* カスタム CA 証明書では内部証明書は削除されませんが、カスタム証明書にはサーバ接続の検証用の証明書を指定する必要があります。
* すべてのカスタム証明書が、サーバ証明書のシステム強化ガイドラインを満たしている必要があります。
+
link:../harden/index.html["システムの保護対策"]

* StorageGRID では、 CA からの証明書を 1 つのファイル（ CA 証明書バンドル）にバンドルすることがサポートされています。



NOTE: StorageGRID には、すべてのグリッドで同じオペレーティングシステムの CA 証明書も含まれています。本番環境では、オペレーティングシステムの CA 証明書の代わりに、外部の認証局によって署名されたカスタム証明書を指定してください。

サーバ証明書とクライアント証明書のタイプのバリエーションは、いくつかの方法で実装されます。システムを設定する前に、特定の StorageGRID 構成に必要なすべての証明書を準備しておく必要があります。

[cols="1a,1a,1a,1a,1a"]
|===
| 証明書 | 証明書のタイプ | 説明 | ナビゲーションの場所 | 詳細 


 a| 
管理者クライアント証明書
 a| 
クライアント
 a| 
StorageGRID が外部クライアントアクセスを認証できるように、各クライアントにインストールします。

* 許可された外部クライアントから StorageGRID Prometheus データベースにアクセスできるようにします。
* 外部ツールを使用して StorageGRID をセキュアに監視できます。

 a| 
*設定*>*アクセス制御*>*クライアント証明書*
 a| 
link:configuring-administrator-client-certificates.html["管理者クライアント証明書の設定"]



 a| 
アイデンティティフェデレーション証明書
 a| 
サーバ
 a| 
StorageGRID と外部のActive Directory、OpenLDAP、またはOracle Directory Server間の接続が認証されます。アイデンティティフェデレーションに使用され、管理者グループとユーザを外部システムで管理できます。
 a| 
*設定*>*アクセス制御*>*アイデンティティフェデレーション*
 a| 
link:using-identity-federation.html["アイデンティティフェデレーションを使用する"]



 a| 
シングルサインオン（ SSO ）証明書
 a| 
サーバ
 a| 
シングルサインオン（SSO）要求に使用されるActive Directoryフェデレーションサービス（AD FS）とStorageGRID 間の接続を認証します。
 a| 
*環境設定*>*アクセスコントロール*>*シングルサインオン*
 a| 
link:configuring-sso.html["シングルサインオンを設定しています"]



 a| 
キー管理サーバ（ KMS ）の証明書
 a| 
サーバとクライアント
 a| 
StorageGRID と外部キー管理サーバ（ KMS ）の間の接続を認証します。この接続により、 StorageGRID アプライアンスノードに暗号化キーが提供されます。
 a| 
*構成*>*システム設定*>*キー管理サーバ*
 a| 
link:kms-adding.html["キー管理サーバの追加（KMS）"]



 a| 
E メールアラート通知の証明書
 a| 
サーバとクライアント
 a| 
アラート通知に使用される SMTP E メールサーバと StorageGRID 間の接続を認証します。

* SMTP サーバとの通信に Transport Layer Security （ TLS ）が必要な場合は、 E メールサーバの CA 証明書を指定する必要があります。
* SMTP E メールサーバで認証用のクライアント証明書が必要な場合にのみ、クライアント証明書を指定してください。

 a| 
*アラート*>*電子メールの設定*
 a| 
link:../monitor/index.html["トラブルシューティングを監視します"]



 a| 
ロードバランサエンドポイントの証明書
 a| 
サーバ
 a| 
S3またはSwiftクライアントとゲートウェイノードまたは管理ノード上のStorageGRID ロードバランササービスの間の接続を認証します。ロードバランサエンドポイントを設定する際に、ロードバランサ証明書をアップロードまたは生成します。クライアントアプリケーションは、StorageGRID に接続してオブジェクトデータを保存および読み出す際にロードバランサ証明書を使用します。

*注：*ロードバランサ証明書は、通常のStorageGRID 処理で最も使用される証明書です。
 a| 
*設定*>*ネットワーク設定*>*ロードバランサエンドポイント*
 a| 
* link:configuring-load-balancer-endpoints.html["ロードバランサエンドポイントの設定"]
* FabricPool のロードバランサエンドポイントの作成
+
link:../fabricpool/index.html["StorageGRID for FabricPool を設定します"]





 a| 
管理インターフェイスのサーバ証明書
 a| 
サーバ
 a| 
クライアントの Web ブラウザと StorageGRID 管理インターフェイスの間の接続を認証することで、ユーザがセキュリティの警告なしで Grid Manager とテナントマネージャにアクセスできるようにします。

この証明書は、 Grid 管理 API 接続とテナント管理 API 接続も認証します。

内部のCA証明書を使用するか、カスタム証明書をアップロードすることができます。
 a| 
*構成*>*ネットワーク設定*>*サーバー証明書*
 a| 
* link:configuring-server-certificates.html["サーバ証明書の設定"]
* link:configuring-custom-server-certificate-for-grid-manager-tenant-manager.html["Grid ManagerおよびTenant Manager用のカスタムサーバ証明書を設定する"]




 a| 
クラウドストレージプールのエンドポイントの証明書
 a| 
サーバ
 a| 
StorageGRID クラウドストレージプールから外部ストレージ（S3 GlacierやMicrosoft Azure BLOBストレージなど）への接続を認証します。クラウドプロバイダのタイプごとに別の証明書が必要です。
 a| 
* ilm *>*ストレージ・プール*
 a| 
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]



 a| 
プラットフォームサービスのエンドポイント証明書
 a| 
サーバ
 a| 
StorageGRID プラットフォームサービスから S3 ストレージリソースへの接続を認証します。
 a| 
* Tenant Manager * > * storage （ S3 ） * > * Platform services endpoints *
 a| 
link:../tenant/index.html["テナントアカウントを使用する"]



 a| 
Object Storage API Service Endpoint Server証明書
 a| 
サーバ
 a| 
ストレージノード上のLocal Distribution Router（LDR）サービスまたはゲートウェイノード上の廃止されたConnection Load Balancer（CLB）サービスへのセキュアなS3またはSwiftクライアント接続を認証します。
 a| 
*設定*>*ネットワーク設定*>*ロードバランサエンドポイント*
 a| 
link:configuring-custom-server-certificate-for-storage-node-or-clb.html["ストレージノードまたはCLBサービスへの接続用のカスタムサーバ証明書を設定する"]

|===


== 例 1 ：ロードバランササービス

この例では、 StorageGRID がサーバとして機能します。

. ロードバランサエンドポイントを設定し、 StorageGRID でサーバ証明書をアップロードまたは生成します。
. S3 または Swift クライアント接続をロードバランサエンドポイントに設定し、同じ証明書をクライアントにアップロードします。
. クライアントは、データを保存または取得する際に HTTPS を使用してロードバランサエンドポイントに接続します。
. StorageGRID は、公開鍵を含むサーバ証明書と、秘密鍵に基づく署名を返します。
. クライアントは、サーバの署名と証明書のコピーの署名を比較して、この証明書を検証します。署名が一致した場合、クライアントは同じ公開鍵を使用してセッションを開始します。
. クライアントがオブジェクトデータを StorageGRID に送信




== 例 2 ：外部キー管理サーバ（ KMS ）

この例では、 StorageGRID がクライアントとして機能します。

. 外部キー管理サーバソフトウェアを使用する場合は、 StorageGRID を KMS クライアントとして設定し、 CA 署名済みサーバ証明書、パブリッククライアント証明書、およびクライアント証明書の秘密鍵を取得します。
. Grid Manager を使用して KMS サーバを設定し、サーバ証明書とクライアント証明書およびクライアント秘密鍵をアップロードします。
. StorageGRID ノードで暗号化キーが必要な場合、証明書からのデータと秘密鍵に基づく署名を含む KMS サーバに要求が送信されます。
. KMS サーバは証明書の署名を検証し、 StorageGRID を信頼できることを決定します。
. KMS サーバは、検証済みの接続を使用して応答します。

