---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords:  
summary: StorageGRID システムでの S3 REST API のサポートに関する変更点に注意する必要があります。 
---
= S3 REST API のサポートに関する変更点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムでの S3 REST API のサポートに関する変更点に注意する必要があります。

|===
| リリース。 | コメント 


 a| 
11.5
 a| 
* バケットの暗号化の管理のサポートが追加されました。
* S3 オブジェクトのロックと廃止された従来の準拠要求のサポートを追加しました。
* バージョン管理されたバケットでの DELETE Multiple Objects の使用のサポートが追加されました。
* 。 `Content-MD5` 要求ヘッダーが正しくサポートされるようになりました。




 a| 
11.4
 a| 
* DELETE Bucket tagging 、 GET Bucket tagging 、 PUT Bucket tagging のサポートが追加されました。コスト割り当てタグはサポートされていません。
* StorageGRID 11.4 で作成されたバケットでは、オブジェクトキー名がパフォーマンスのベストプラクティスに適合するように制限する必要はなくなりました。
* でバケット通知のサポートが追加されました `s3:ObjectRestore:Post` イベントタイプ。
* マルチパートの AWS サイズの上限が適用されるようになりました。マルチパートアップロードの各パートのサイズは 5MiB から 5GiB の間にする必要があります。最後の部分は 5MiB より小さくすることができます。
* TLS 1.3 のサポートの追加、およびサポートされる TLS 暗号スイートのリストの更新。
* CLB サービスは廃止されました。




 a| 
11.3
 a| 
* ユーザ指定のキーによるオブジェクトデータのサーバ側暗号化（ SSE-C ）がサポートされるようになりました。
* DELETE Bucket lifecycle、GET Bucket lifecycle、PUT Bucket lifecycleの各処理（Expirationアクションのみ）とがサポートされるようになりました `x-amz-expiration` 応答ヘッダー。
* PUT Object 、 PUT Object - Copy 、 Multipart Upload が更新されて、取り込み時に同期配置を使用する ILM ルールの影響を受けるようになりました。
* サポートされる TLS 暗号スイートのリストが更新されました。TLS 1.1 暗号はサポートされなくなりました。




 a| 
11.2
 a| 
クラウドストレージプールで POST Object restore を使用できるようになりました。グループポリシーとバケットポリシーの ARN 、ポリシー条件キー、およびポリシー変数で AWS 構文を使用できるようになりました。StorageGRID 構文を使用する既存のグループポリシーとバケットポリシーは引き続きサポートされます。

* 注：カスタム StorageGRID 機能で使用される ARN やその他の構成 JSON / XML での使用に変更はありませんでした。



 a| 
11.1
 a| 
Cross-Origin Resource Sharing （ CORS ）、グリッドノードへの S3 クライアント接続での HTTP の使用、バケットでの準拠設定がサポートされるようになりました。



 a| 
11.0
 a| 
バケットでのプラットフォームサービス（ CloudMirror レプリケーション、通知、および Elasticsearch 検索統合）の設定がサポートされるようになりました。また、バケットに対するオブジェクトタグ付け機能の場所の制約、および整合性制御設定「 available 」がサポートされるようになりました。



 a| 
10.4.
 a| 
ILM スキャンのバージョン管理、エンドポイントドメインの名前ページの更新、ポリシーの条件と変数、ポリシーの例、および PutOverwriteObject 権限の変更のサポートが追加されました。



 a| 
10.3
 a| 
バージョン管理のサポートが追加されました。



 a| 
10.2
 a| 
グループとバケットのアクセスポリシー、およびマルチパートコピー（ Upload Part - Copy ）のサポートが追加されました。



 a| 
10.1
 a| 
マルチパートアップロード、仮想ホスト形式の要求、および v4 認証のサポートが追加されました。



 a| 
10.0
 a| 
StorageGRID システムで S3 REST API のサポートが初めて導入されました。現在サポートされているバージョンの _Simple Storage Service API Reference_is 2006-03-01 。

|===