---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: このセクションでは、 StorageGRID システムでオブジェクトの S3 REST API 処理を実装する方法について説明します。 
---
= オブジェクトの処理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このセクションでは、 StorageGRID システムでオブジェクトの S3 REST API 処理を実装する方法について説明します。

* link:using-s3-object-lock.html["S3 オブジェクトロックを使用する"]
* link:using-server-side-encryption.html["サーバ側の暗号化を使用する"]
* link:get-object.html["オブジェクトの取得"]
* link:head-object.html["HEAD Object の実行"]
* link:post-object-restore.html["POST Object restore の実行"]
* link:put-object.html["PUT Object の場合"]
* link:put-object-copy.html["PUT Object - Copy の各コマンドを実行します"]


すべてのオブジェクトの処理に次の条件が適用されます。

* StorageGRID 整合性制御は、次の点を除いて、オブジェクトに対するすべての処理でサポートされます。
+
** GET Object ACL の場合
** `OPTIONS /`
** オブジェクトのリーガルホールドを適用します
** PUT Object retention のことです


* 同一キーに書き込む2つのクライアントなど'競合するクライアント要求は'最新のWINS形式で解決されます「latest-wins」評価のタイミングは、S3クライアントが処理を開始するタイミングではなく、StorageGRID システムが特定の要求を完了したタイミングに基づいています。
* StorageGRID バケット内のオブジェクトは、匿名ユーザまたは別のアカウントが作成したオブジェクトも含めて、すべてバケット所有者によって所有されます。
* Swift を使用して StorageGRID システムに取り込まれたデータオブジェクトに S3 を使用してアクセスすることはできません。


次の表に、 StorageGRID での S3 REST API オブジェクト処理の実装方法を示します。

|===
| 操作 | 実装 


 a| 
オブジェクトを削除します
 a| 
多要素認証（MFA）と応答ヘッダー `x-amz-mfa` はサポートされていません。

StorageGRID は、 DELETE Object 要求を処理する際に、オブジェクトのすべてのコピーをすべての格納場所からただちに削除しようとします。成功すると、 StorageGRID はただちにクライアントに応答を返します。30 秒以内にすべてのコピーを削除できなかった場合（格納場所が一時的に使用不能などの理由で）、 StorageGRID は削除対象のコピーをキューに登録し、クライアントに処理が成功したことを通知します。

* バージョン管理 *

特定のバージョンを削除するには、バケットの所有者を要求元にしてを使用する必要があります `versionId` サブリソース：このサブリソースを使用すると、バージョンが完全に削除されます。状況に応じて `versionId` 削除マーカー、応答ヘッダーに対応します `x-amz-delete-marker` はに設定されています `true`。

* を使用せずにオブジェクトが削除された場合 `versionId` バージョンが有効になっているバケットのサブリソースが表示されると、削除マーカーが生成されます。。 `versionId` 削除マーカーの場合は、を使用して戻ります `x-amz-version-id` 応答ヘッダー、および `x-amz-delete-marker` 応答ヘッダーがに設定されて返されます `true`。
* を使用せずにオブジェクトが削除された場合 `versionId` バージョンが一時停止中のバケットについて、既存の「null」バージョンまたは「null」削除マーカーが完全に削除され、新しい「null」削除マーカーが生成されます。。 `x-amz-delete-marker` 応答ヘッダーがに設定されて返されます `true`。


* 注 * ：特定の場合、 1 つのオブジェクトに複数の削除マーカーが存在することがあります。



 a| 
複数のオブジェクトを削除します
 a| 
多要素認証（MFA）と応答ヘッダー `x-amz-mfa` はサポートされていません。

同じ要求メッセージで複数のオブジェクトを削除できます。



 a| 
オブジェクトのタグ付けを削除します
 a| 
を使用します `tagging` サブリソース：オブジェクトからすべてのタグを削除します。Amazon S3 REST API のすべての動作が実装されています。

* バージョン管理 *

状況に応じて `versionId` クエリパラメータが要求で指定されていない場合、バージョン管理されたバケット内のオブジェクトの最新バージョンからすべてのタグが削除されます。オブジェクトの現在のバージョンが削除マーカーの場合は、"MethodNotAllowed`"ステータスがとともに返されます `x-amz-delete-marker` 応答ヘッダーをに設定しました `true`。



 a| 
オブジェクトの取得
 a| 
link:get-object.html["オブジェクトの取得"]



 a| 
GET Object ACL の場合
 a| 
アカウントに必要なアクセスクレデンシャルがある場合、オブジェクトの所有者にオブジェクトに対するフルアクセスがあることを示す応答が返され、所有者の ID 、表示名、および権限が表示されます。



 a| 
オブジェクトのリーガルホールドを取得します
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["S3 オブジェクトロックを使用する"]



 a| 
GET Object retention のことです
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["S3 オブジェクトロックを使用する"]



 a| 
GET Object tagging
 a| 
を使用します `tagging` サブリソース：オブジェクトのすべてのタグを返すために使用します。Amazon S3 REST API のすべての動作が実装されています

* バージョン管理 *

状況に応じて `versionId` クエリパラメータが要求で指定されていない場合、バージョン管理されたバケット内のオブジェクトの最新バージョンからすべてのタグが返されます。オブジェクトの現在のバージョンが削除マーカーの場合は、"MethodNotAllowed`"ステータスがとともに返されます `x-amz-delete-marker` 応答ヘッダーをに設定しました `true`。



 a| 
HEAD Object の実行
 a| 
link:head-object.html["HEAD Object の実行"]



 a| 
POST Object restore の実行
 a| 
link:post-object-restore.html["POST Object restore の実行"]



 a| 
PUT Object の場合
 a| 
link:put-object.html["PUT Object の場合"]



 a| 
PUT Object - Copy の各コマンドを実行します
 a| 
link:put-object-copy.html["PUT Object - Copy の各コマンドを実行します"]



 a| 
オブジェクトのリーガルホールドを適用します
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["S3 オブジェクトロックを使用する"]



 a| 
PUT Object retention のことです
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["S3 オブジェクトロックを使用する"]



 a| 
PUT Object tagging
 a| 
を使用します `tagging` サブリソース：既存のオブジェクトに一連のタグを追加します。Amazon S3 REST API のすべての動作が実装されています

* タグの更新と取り込み動作 *

PUT Object tagging を使用してオブジェクトのタグを更新した場合、 StorageGRID はオブジェクトを再取り込みしません。これは、一致する ILM ルールで指定されている取り込み動作が使用されないことを意味します。更新によって発生したオブジェクト配置の変更は、通常のバックグラウンド ILM プロセスで ILM が再評価されるときに実施されます。

このため、 ILM ルールの取り込み動作に Strict オプションが指定されている場合、必要なオブジェクト配置を実行できないと（たとえば、新たに必要となった場所を使用できない場合）、アクションは実行されません。更新されたオブジェクトは、必要な配置を実行可能になるまで現在の配置が維持されます。

* 衝突の解決 *

同一キーに書き込む2つのクライアントなど'競合するクライアント要求は'最新のWINS形式で解決されます「latest-wins」評価のタイミングは、S3クライアントが処理を開始するタイミングではなく、StorageGRID システムが特定の要求を完了したタイミングに基づいています。

* バージョン管理 *

状況に応じて `versionId` クエリパラメータが要求で指定されていません。処理は、バージョン管理されたバケット内のオブジェクトの最新バージョンにタグを追加します。オブジェクトの現在のバージョンが削除マーカーの場合は、"MethodNotAllowed`"ステータスがとともに返されます `x-amz-delete-marker` 応答ヘッダーをに設定しました `true`。

|===
.関連情報
link:consistency-controls.html["整合性制御"]

link:s3-operations-tracked-in-audit-logs.html["監査ログで追跡される S3 処理"]
