---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords:  
summary:  
---
= S3 REST API のサポートされる処理と制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは Simple Storage Service API （ API バージョン 2006-03-01 ）を実装しており、ほとんどの処理をサポートしていますが、いくつかの制限事項があります。S3 REST API クライアントアプリケーションを統合するときは、実装の詳細を理解しておく必要があります。

StorageGRID システムでは、仮想ホスト形式の要求とパス形式の要求の両方がサポートされます。

* link:authenticating-requests.html["要求の認証"]
* link:operations-on-the-service.html["サービスの処理"]
* link:operations-on-buckets.html["バケットの処理"]
* link:custom-operations-on-buckets.html["バケットのカスタム処理"]
* link:operations-on-objects.html["オブジェクトの処理"]
* link:operations-for-multipart-uploads.html["マルチパートアップロードの処理"]
* link:error-responses.html["エラー応答"]




== 日付の処理

S3 REST API の StorageGRID 実装では、有効な HTTP の日付形式のみをサポートしています。

StorageGRID システムでは、日付の値を設定できるすべてのヘッダーで、有効な HTTP の日付形式のみがサポートされます。日付の時刻の部分は、 Greenwich Mean Time （ GMT ；グリニッジ標準時）の形式で指定するか、タイムゾーンのオフセットなし（ +0000 を指定）の Universal Coordinated Time （ UTC ；協定世界時）の形式で指定できます。を指定する場合は `x-amz-date` 要求のヘッダー。Date要求ヘッダーで指定された値を上書きします。AWS署名バージョン4を使用している場合は、を参照してください `x-amz-date` 日付ヘッダーがサポートされていないため、署名済み要求にヘッダーが含まれている必要があります。



== 代表的な要求ヘッダー

StorageGRID システムでは、以下の例外を除き、_Simple Storage Service API Reference_で 定義されている共通の要求ヘッダーがサポートされます。

|===
| 要求ヘッダー | 実装 


 a| 
承認
 a| 
AWS 署名バージョン 2 は完全にサポートされます

AWS 署名バージョン 4 は次の例外を除いてサポートされます。

* 要求の本文の SHA256 の値は計算されません。ユーザが送信した値は、値の場合と同様に、検証なしで受け入れられます `UNSIGNED-PAYLOAD` は用に提供されていた `x-amz-content-sha256` ヘッダー。




 a| 
x-amz-security-token を指定します
 a| 
実装されていませんを返します `XNotImplemented`。

|===


== 共通の応答ヘッダー

StorageGRID システムでは、以下の例外を除き、 _Simple Storage Service API Reference_で 定義されている共通の応答ヘッダーがすべてサポートされます。

|===
| 応答ヘッダー | 実装 


 a| 
x-amz-id-2
 a| 
使用されません

|===
.関連情報
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services （ AWS ）ドキュメント：「 Amazon Simple Storage Service API Reference"]
