---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts, reference 
summary: 次の表に、デフォルトの StorageGRID アラートをすべて示します。必要に応じて、システムの管理方法に合わせてカスタムのアラートルールを作成できます。 
---
= アラート一覧
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、デフォルトの StorageGRID アラートをすべて示します。必要に応じて、システムの管理方法に合わせてカスタムのアラートルールを作成できます。

一部のアラートで使用される指標については、よく使用されるPrometheus指標に関する情報を参照してください。

|===
| アラート名 | 概要 および推奨される対処方法 


 a| 
アプライアンスのバッテリの有効期間が終了し
 a| 
アプライアンスのストレージコントローラのバッテリの有効期間が終了しました。

. バッテリを交換します。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリに問題があります
 a| 
アプライアンスのストレージコントローラのバッテリに障害が発生しました。

. バッテリを交換します。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスバッテリの学習容量が不足しています
 a| 
アプライアンスのストレージコントローラのバッテリで学習容量が不足しています。

. バッテリを交換します。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスバッテリの有効期限が近づいています
 a| 
アプライアンスのストレージコントローラのバッテリの有効期限が近づいています。

. すぐにバッテリを交換してください。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリが取り外されました
 a| 
アプライアンスのストレージコントローラのバッテリがありません。

. バッテリを取り付けます。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリが高温になっています
 a| 
アプライアンスのストレージコントローラのバッテリが過熱しています。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. ファンや HVAC の故障など、温度上昇の考えられる原因を調査する。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの BMC 通信エラー
 a| 
ベースボード管理コントローラ（ BMC ）との通信が失われました。

. BMC が正常に動作していることを確認します。ノード*を選択し、アプライアンスノードのハードウェア*タブを選択します。Compute Controller BMC IP フィールドを探し、その IP を参照します。
. ノードをメンテナンスモードにしてから、アプライアンスの電源をオフにしてオンにし、 BMC の通信をリストアします。使用しているアプライアンスのインストールとメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスキャッシュバックアップデバイスに障害が発生しました
 a| 
永続的キャッシュバックアップデバイスで障害が発生しました。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
アプライアンスキャッシュバックアップデバイスに十分な容量がありません
 a| 
キャッシュバックアップデバイスの容量が不足しています。テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのキャッシュ・バックアップ・デバイスの書き込み保護
 a| 
キャッシュバックアップデバイスは書き込み保護されています。テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのキャッシュメモリサイズが一致しません
 a| 
アプライアンスの2台のコントローラのキャッシュサイズが異なります。テクニカルサポートにお問い合わせください。



 a| 
アプライアンスコンピューティングコントローラシャーシの温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの温度が公称のしきい値を超えました。

. ハードウェアコンポーネントの過熱状態を確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスのコンピューティングコントローラの CPU 温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの CPU 温度が公称のしきい値を超えました。

. ハードウェアコンポーネントの過熱状態を確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスのコンピューティングコントローラを確認する必要があります
 a| 
StorageGRID アプライアンスのコンピューティングコントローラでハードウェア障害が検出されました。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスコンピューティングコントローラの電源装置 A に問題があります
 a| 
コンピューティングコントローラの電源装置 A に問題があります。このアラートは、電源装置に障害が発生したか、電源の供給に問題があることを示している可能性があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスコンピューティングコントローラの電源装置 B に問題があります
 a| 
コンピューティングコントローラの電源装置Bに問題があります。このアラートは、電源装置に障害が発生したか、電源の供給に問題があることを示している可能性があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスコンピューティングハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスによってデータのレポートが停止されました。

. ベース OS の EOS-system-status サービスのステータスを確認する。
. サービスが停止またはエラー状態の場合は、サービスを再起動します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのファイバ・チャネル障害が検出されました
 a| 
アプライアンスのストレージコントローラとコンピューティングコントローラの間のFibre Channel接続に問題があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認します（* Nodes *>*_appliance node_name >* Hardware *）。いずれかのコンポーネントのステータスが「公称」でない場合は、次のアクションを実行します。
+
.. コントローラ間の Fibre Channel ケーブルが完全に接続されていることを確認します。
.. ファイバチャネルケーブルが過度に曲がっていないことを確認します。
.. SFP+ モジュールが正しく装着されていることを確認します。




* 注： * この問題が解決しない場合、 StorageGRID システムは問題のある接続を自動的にオフラインにすることがあります。

. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスのインストールとメンテナンスの手順を参照してください。




 a| 
アプライアンスのファイバ・チャネル HBA ポート障害
 a| 
ファイバチャネルHBAポートで障害が発生しているか、障害が発生しています。テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのフラッシュキャッシュドライブが最適な状態でありません
 a| 
SSD キャッシュに使用されているドライブが最適な状態でありません。

. SSD キャッシュドライブを交換します。アプライアンスの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスインターコネクト / バッテリキャニスターが取り外されました
 a| 
インターコネクト / バッテリキャニスターがありません。

. バッテリを交換します。バッテリの取り外しと交換の手順は、アプライアンスの設置とメンテナンスの手順のストレージコントローラを交換するための手順 に含まれています。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの LACP ポートがありません
 a| 
StorageGRID アプライアンスのポートが LACP ボンドに参加していません。

. スイッチの設定を確認します。インターフェイスが正しいリンクアグリゲーショングループに設定されていることを確認してください。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンス全体の電源装置がデグレード状態になりました
 a| 
StorageGRID アプライアンスの電源が、推奨される動作電圧から逸脱しています。

. 電源装置 A と B のステータスを調べ、どちらの電源装置に異常があるかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]






 a| 
アプライアンスストレージコントローラ A の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ A で障害が発生した。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージコントローラ B の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ B で障害が発生した。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージコントローラのドライブ障害
 a| 
StorageGRID アプライアンスの 1 つ以上のドライブで障害が発生しているか、または最適な状態でありません。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージコントローラハードウェア問題
 a| 
SANtricity ソフトウェアから、 StorageGRID アプライアンスのコンポーネントについて「 Needs Attention 」が報告されます。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージコントローラの電源装置 A に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 A が、推奨される動作電圧から逸脱しています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージコントローラの電源装置 B に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 B が、推奨される動作電圧から逸脱しています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスストレージハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスによってデータのレポートが停止されました。

. ベース OS の EOS-system-status サービスのステータスを確認する。
. サービスが停止またはエラー状態の場合は、サービスを再起動します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスストレージシェルフがデグレード状態になります
 a| 
ストレージアプライアンスのストレージシェルフのいずれかのコンポーネントのステータスがデグレードになっています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
アプライアンスの温度が超過しました
 a| 
アプライアンスのストレージコントローラの公称温度または最大温度を超えました。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. ファンや HVAC の故障など、温度上昇の考えられる原因を調査する。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの温度センサーが取り外されました
 a| 
温度センサーが取り外されました。テクニカルサポートにお問い合わせください。



 a| 
Cassandra 自動コンパクターエラーです
 a| 
Cassandraの自動compactorでエラーが発生しました。Cassandraの自動compactorはすべてのストレージノードに存在し、オーバーライトおよび大量のワークロードを削除するためにCassandraデータベースのサイズを管理します。この状態が解消されない間は、特定のワークロードでメタデータの消費量が予期せずに増加します。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
Cassandra 自動コンパクターメトリックが古くなっています
 a| 
Cassandra の自動圧縮機能を説明する指標が最新ではありません。Cassandra の自動圧縮機能はすべてのストレージノードに存在し、オーバーライトや大量のワークロードの削除用に Cassandra データベースのサイズを管理します。このアラートが解決しない間、特定のワークロードでメタデータの使用量が予期せずに増加します。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
Cassandra 通信エラー
 a| 
Cassandraサービスを実行するノード間の通信で問題が発生しています。このアラートは、ノード間の通信に干渉していることを示しています。1 つ以上のストレージノードでネットワーク問題 または Cassandra サービスが停止している可能性があります。

. 1 つ以上のストレージノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. 1 つ以上のストレージノードに影響している可能性のあるネットワーク問題 がないかどうかを確認します。
. Support *>* Tools *>* Grid Topology *を選択します。
. システム内のストレージノードごとに、 * SSM * > * Services * を選択します。Cassandraサービスのステータスが「running」であることを確認します。
. Cassandraが実行されていない場合は、リカバリとメンテナンスの手順のサービスを開始または再開する手順に従います。
. Cassandra サービスのすべてのインスタンスが実行中でアラートが解決されない場合は、テクニカルサポートに連絡してください。


link:../maintain/index.html[""]



 a| 
Cassandra の圧縮処理が過負荷です
 a| 
Cassandraのコンパクションプロセスが過負荷状態です。コンパクションプロセスが過負荷の場合、読み取りパフォーマンスが低下し、RAMが使用される可能性があります。Cassandra サービスが応答しなくなったり、クラッシュしたりする可能性もあります。

. リカバリとメンテナンスの手順のサービスを再起動する手順に従って、Cassandraサービスを再起動します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


link:../maintain/index.html[""]



 a| 
Cassandra 修復指標が最新ではありません
 a| 
Cassandra 修復ジョブを説明する指標が最新ではありません。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. ノードをリブートします。Grid Managerから* Nodes *に移動し、ノードを選択してTasksタブを選択します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
Cassandra の修復の進捗が遅い
 a| 
Cassandraデータベースの修復の進捗状況が低速化しています。データベースの修復が低速化すると、Cassandraのデータ整合性処理が中断されます。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. すべてのストレージノードがオンラインで、ネットワーク関連のアラートがないことを確認します。
. このアラートを最大 2 日間監視して、問題 が自動的に解決するかどうかを確認します。
. データベースの修復に時間がかかる場合は、テクニカルサポートに連絡してください。




 a| 
Cassandra 修復サービスを使用できません
 a| 
Cassandra修復サービスは使用できません。Cassandra修復サービスはすべてのストレージノードに存在し、Cassandraデータベースに重要な修復機能を提供します。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. Support *>* Tools *>* Grid Topology *を選択します。
. システム内のストレージノードごとに、 * SSM * > * Services * を選択します。Cassandra Reaper サービスのステータスが「 Running 」であることを確認します。
. Cassandra Reaperが実行されていない場合は、リカバリとメンテナンスの手順のサービスを開始または再起動する手順に従います。
. Cassandra Reaper サービスのすべてのインスタンスが実行中で、アラートが解決されない場合は、テクニカルサポートにお問い合わせください。


link:../maintain/index.html[""]



 a| 
クラウドストレージプールの接続エラー
 a| 
クラウドストレージプールの健全性チェックで、新たなエラーが 1 つ以上検出されました。

. ストレージプールページのクラウドストレージプールセクションに移動します。
. Last Error 列を確認して、エラーが発生しているクラウドストレージプールを特定します。
. 情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照してください。


link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]



 a| 
DHCP リースの期限が切れました
 a| 
ネットワークインターフェイスのDHCPリースが期限切れです。DHCPリースの期限が切れている場合は、推奨される対処方法に従います。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。リカバリとメンテナンスの手順を参照してください。


link:../maintain/index.html[""]



 a| 
DHCP リースがまもなく期限切れになります
 a| 
ネットワークインターフェイスのDHCPリースがまもなく期限切れになります。DHCPリースが期限切れにならないようにするには、推奨される対処方法に従います。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。リカバリとメンテナンスの手順を参照してください。


link:../maintain/index.html[""]



 a| 
DHCP サーバが使用できません
 a| 
DHCPサーバが使用できません。StorageGRID ノードがDHCPサーバに接続できません。ノードの IP アドレスの DHCP リースを検証できません。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。リカバリとメンテナンスの手順を参照してください。


link:../maintain/index.html[""]



 a| 
ディスク I/O が非常に遅い
 a| 
ディスク I/O が非常に遅いと、 StorageGRID のパフォーマンスに影響している可能性があります。

. 問題 がストレージアプライアンスノードに関連している場合は、 SANtricity システムマネージャを使用して、障害が発生しているドライブ、予測される障害が発生しているドライブ、または進行中のドライブの修復を確認します。また、アプライアンスのコンピューティングコントローラとストレージコントローラ間のファイバチャネルまたは SAS リンクのステータスを調べて、リンクが停止しているか、エラー率が高いリンクが表示されていないかを確認します。
. このノードのボリュームをホストしているストレージシステムを調べて、低速な I/O のルート原因 を特定して修正します
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。



NOTE: 影響を受けるノードでは、グリッドの全体的なパフォーマンスへの影響を回避するために、サービスが無効になって、ノード自体原因となった状態が解消されて通常の I/O パフォーマンスが検出された場合は、フルサービスに自動的に戻ります。



 a| 
E メール通知のエラーです
 a| 
アラートのEメール通知を送信できませんでした。このアラートは、アラートEメール通知が失敗した場合、またはテストEメール（* Alerts *>* Email Setup *ページから送信）を配信できない場合にトリガーされます。

. アラートの「 * Site/Node * 」列に表示されている管理ノードから Grid Manager にサインインします。
. [*アラート*>*電子メール設定*]ページに移動し、設定を確認して、必要に応じて変更します。
. [ テストメールの送信 ] をクリックし、テスト受信者の電子メールの受信ボックスを確認します。テスト用 E メールを送信できない場合は、このアラートの新しいインスタンスがトリガーされることがあります。
. テスト用 E メールを送信できなかった場合は、 E メールサーバがオンラインであることを確認します。
. サーバが動作している場合は、* Support *>* Tools *>* Logs *を選択し、管理ノードのログを収集します。アラートの前後 15 分の期間を指定します。
. ダウンロードしたアーカイブを展開し、の内容を確認します `prometheus.log` `(_/GID<gid><time_stamp>/<site_node>/<time_stamp>/metrics/prometheus.log)`。
. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
クライアント証明書ページで設定された証明書の有効期限
 a| 
[クライアント証明書]ページで設定されている1つ以上の証明書の有効期限が近づいています。

. [* Configuration *>* Access Control *>* Client Certificates *]を選択します。
. 有効期限が近い証明書を選択してください。
. 「* Edit *」を選択して、新しい証明書をアップロードまたは生成します。
. 有効期限が近い証明書ごとに、上記の手順を繰り返します。


link:../admin/index.html["StorageGRID の管理"]



 a| 
ロードバランサエンドポイント証明書の有効期限
 a| 
1 つ以上のロードバランサエンドポイント証明書の有効期限が近づいています。

. [* Configuration *>* Network Settings *>* Load Balancer Endpoints *]を選択します。
. まもなく期限切れになる証明書を含むエンドポイントを選択してください。
. 「 * エンドポイントの編集」を選択して、新しい証明書をアップロードまたは生成します。
. 証明書の有効期限が切れているエンドポイントまたはまもなく期限切れになるエンドポイントごとに、上記の手順を繰り返します。


ロードバランサエンドポイントの管理の詳細については、StorageGRID の管理手順を参照してください。

link:../admin/index.html["StorageGRID の管理"]



 a| 
管理インターフェイス用のサーバ証明書の有効期限
 a| 
管理インターフェイスで使用されるサーバ証明書の有効期限が近づいています。

. [* Configuration *]>[* Network Settings *]>[* Server Certificates*]を選択します。
. 管理インターフェイスのサーバ証明書セクションで、新しい証明書をアップロードします。


link:../admin/index.html["StorageGRID の管理"]



 a| 
ストレージAPIエンドポイント用のサーバ証明書の有効期限
 a| 
ストレージ API エンドポイントへのアクセスに使用されるサーバ証明書の有効期限が近づいています。

. [* Configuration *]>[* Network Settings *]>[* Server Certificates*]を選択します。
. Object Storage API Service EndpointsのServer Certificateセクションで、新しい証明書をアップロードします。


link:../admin/index.html["StorageGRID の管理"]



 a| 
Grid ネットワーク MTU が一致しません
 a| 
グリッドネットワークインターフェイス（eth0）の最大伝送ユニット（MTU）設定は、グリッド内のノード間で大きく異なります。MTU設定の違いによって、eth0ネットワークの一部がジャンボフレーム用に設定されていることがわかります。MTU サイズが 1000 を超えると、原因 のネットワークパフォーマンスの問題が発生する可能性があります。

link:../troubleshoot/troubleshooting-storagegrid-system.html["Grid Network MTU mismatchアラートのトラブルシューティング"]



 a| 
Java ヒープの使用率が高い
 a| 
Javaヒープスペースの使用率が高くなっています。Javaヒープがいっぱいになると、メタデータサービスが使用できなくなり、クライアント要求が失敗することがあります。

. ダッシュボードで ILM アクティビティを確認します。このアラートは、 ILM ワークロードが減少すると自動的に解決する場合があります。
. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
メタデータクエリのレイテンシが高くなっています
 a| 
Cassandraメタデータクエリの平均時間が長すぎます。ディスクの交換などのハードウェアの変更や、取り込みの急増などのワークロードの変化が原因で、クエリのレイテンシが増加する可能性があります。

. クエリのレイテンシが増大した時間帯にハードウェアやワークロードの変化がなかったかを確認します。
. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
アイデンティティフェデレーションの同期に失敗する
 a| 
アイデンティティソースからフェデレーテッドグループとフェデレーテッドユーザを同期できません。

. 設定した LDAP サーバがオンラインで使用可能であることを確認します。
. アイデンティティフェデレーションページの設定を確認します。すべての値が最新であることを確認します。StorageGRID の管理手順の「フェデレーテッドアイデンティティソースの設定」を参照してください。
. ［ * 接続のテスト * ］ をクリックして、 LDAP サーバーの設定を確認します。
. 問題 を解決できない場合は、テクニカルサポートにお問い合わせください。


link:../admin/index.html["StorageGRID の管理"]



 a| 
ILM 配置を実現できません
 a| 
特定のオブジェクトに対するILMルールの配置手順を実行できません。このアラートは、配置手順に必要なノードが使用できないか、ILMルールの設定が正しくないことを示しています。たとえば、レプリケートコピーをストレージノードよりも多く指定するルールがあるとします。

. すべてのノードがオンラインであることを確認してください。
. すべてのノードがオンラインの場合は、アクティブな ILM ポリシーを使用しているすべての ILM ルールの配置手順を確認します。すべてのオブジェクトに対して有効な手順があることを確認します。情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照してください。
. 必要に応じて、ルールの設定を更新し、新しいポリシーをアクティブ化します。
+

NOTE: アラートがクリアされるまでに1日程度かかる場合があります。

. 問題が解決しない場合は、テクニカルサポートにお問い合わせください。



NOTE: このアラートはアップグレード中に表示され、アップグレードが正常に完了してから1日間は存続する場合があります。アップグレードによってこのアラートがトリガーされると、アラートは自動的にクリアされます。

link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]



 a| 
ILM のスキャン期間が長すぎます
 a| 
オブジェクトのスキャン、評価、およびILMの適用に必要な時間が長すぎます。ILMによるすべてのオブジェクトのフルスキャンが完了するまでの推定時間が長すぎると（ダッシュボードの* Scan Period - Estimated *を参照）、アクティブなILMポリシーが新たに取り込まれたオブジェクトに適用されない可能性があります。ILM ポリシーへの変更が既存のオブジェクトに適用されない場合があります。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. すべてのストレージノードがオンラインであることを確認します。
. クライアントトラフィックの量を一時的に減らします。たとえば、グリッドマネージャから、*Configuration*>*Network Settings*>*Traffic Classification*を選択し、帯域幅または要求数を制限するポリシーを作成します。
. ディスク I/O または CPU が過負荷状態の場合は、負荷を減らすか、リソースを増やしてください。
. 必要に応じて、同期配置を使用するように ILM ルールを更新します（ StorageGRID 11.3 以降に作成されたルールのデフォルト）。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


link:../admin/index.html["StorageGRID の管理"]



 a| 
ILM のスキャン速度が低下しています
 a| 
ILMのスキャン速度が100オブジェクト/秒未満に設定されています。このアラートは、システムのILMスキャン速度が1秒あたり100オブジェクト未満に変更されたことを示しています（デフォルト：400オブジェクト/秒）。新しく取り込まれたオブジェクトにはアクティブな ILM ポリシーが適用されない場合があります。以降に ILM ポリシーに対して行われた変更は、既存のオブジェクトには適用されません。

. 継続的なサポート調査の一環として ILM スキャン率に一時的に変更が加えられたかどうかを確認します。
. テクニカルサポートにお問い合わせください。



IMPORTANT: テクニカルサポートに連絡しなくても ILM のスキャン速度を変更しないでください。



 a| 
KMS CA 証明書の有効期限
 a| 
キー管理サーバ（ KMS ）証明書への署名に使用する CA 証明書の有効期限が近づいています。

. KMS ソフトウェアを使用して、キー管理サーバの CA 証明書を更新します。
. Grid Managerから、* Configuration *>* System Settings *>* Key Management Server *の順に選択します。
. 証明書ステータスの警告がある KMS を選択します。
. 「 * 編集 * 」を選択します。
. 「 * 次へ * 」を選択して、手順 2 （サーバー証明書のアップロード）に進みます。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. [ 保存（ Save ） ] を選択します。


link:../admin/index.html["StorageGRID の管理"]



 a| 
KMS クライアント証明書の有効期限
 a| 
キー管理サーバのクライアント証明書の有効期限が近づいています。

. Grid Managerから、* Configuration *>* System Settings *>* Key Management Server *の順に選択します。
. 証明書ステータスの警告がある KMS を選択します。
. 「 * 編集 * 」を選択します。
. 「 * 次へ * 」を選択して、手順 3 （クライアント証明書のアップロード）に進みます。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. 新しい秘密鍵をアップロードするには、 * Browse * を選択します。
. [ 保存（ Save ） ] を選択します。


link:../admin/index.html["StorageGRID の管理"]



 a| 
KMS の設定をロードできませんでした
 a| 
キー管理サーバの設定は存在しますが、ロードできませんでした。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 接続エラー
 a| 
アプライアンスノードがサイトのキー管理サーバに接続できませんでした。

. Grid Managerから、* Configuration *>* System Settings *>* Key Management Server *の順に選択します。
. ポートおよびホスト名のエントリが正しいことを確認します。
. サーバ証明書、クライアント証明書、およびクライアント証明書の秘密鍵が正しいかどうか、および有効期限が切れていないかどうかを確認します。
. ファイアウォールの設定により、アプライアンスノードが指定された KMS と通信できることを確認してください。
. ネットワークまたは DNS の問題を修正します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 暗号化キー名が見つかりません
 a| 
設定されているキー管理サーバに、指定した名前と一致する暗号化キーがありません。

. サイトに割り当てられている KMS が、暗号化キーと以前のバージョンに対応する正しい名前を使用していることを確認します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 暗号化キーのローテーションに失敗しました
 a| 
アプライアンスのすべてのボリュームが復号化されましたが、 1 つ以上のボリュームを最新のキーにローテーションできませんでした。テクニカルサポートにお問い合わせください。



 a| 
KMS は設定されていません
 a| 
このサイトにはキー管理サーバがありません。

. Grid Managerから、* Configuration *>* System Settings *>* Key Management Server *の順に選択します。
. このサイトに KMS を追加するか、デフォルトの KMS を追加します。


link:../admin/index.html["StorageGRID の管理"]



 a| 
KMS キーでアプライアンスボリュームを復号化できませんでした
 a| 
ノード暗号化が有効になっているアプライアンス上の 1 つ以上のボリュームを、現在の KMS キーで復号化できませんでした。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. キー管理サーバ（ KMS ）に設定されている暗号化キーと以前のバージョンのキーがあることを確認します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS サーバ証明書の有効期限
 a| 
キー管理サーバ（ KMS ）で使用されるサーバ証明書の有効期限が近づいています。

. KMS ソフトウェアを使用して、キー管理サーバのサーバ証明書を更新します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


link:../admin/index.html["StorageGRID の管理"]



 a| 
大規模な監査キュー
 a| 
監査メッセージのディスクキューがいっぱいです。

. システムの負荷を確認します -- 大量のトランザクションが発生した場合は ' 時間が経過するとアラートは自動的に解決され ' このアラートは無視してかまいません
. アラートが解除されず重大度が上がった場合は、キューサイズのグラフを確認します。数時間から数日にわたって数値が増え続けている場合は、監査の負荷がシステムの監査キャパシティを超えている可能性があります。
. クライアントの書き込みとクライアントの読み取りの監査レベルをErrorまたはOff（* Configuration *>* Monitoring *>* Audit *）に変更することで、クライアントの処理速度を下げるか、ログに記録される監査メッセージの数を減らします。


link:../audit/index.html["監査ログを確認します"]



 a| 
監査ログのディスク容量が不足しています
 a| 
監査ログに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
利用可能なノードメモリが少なくなっています
 a| 
ノードの使用可能なRAMの容量が少なくなっています。使用可能なRAMが少ない場合は、ワークロードに変化があるか、1つ以上のノードでメモリリークが発生している可能性があります。

. このアラートを監視して、問題 が自動的に解決するかどうかを確認します。
. 使用可能なメモリが Major アラートのしきい値を下回った場合は、テクニカルサポートに連絡してください。




 a| 
ストレージプールの空き容量が不足しています
 a| 
オブジェクトデータをストレージプールに格納できるスペースが少なくなっています。

. ILM *>* Storage Pools *を選択します。
. アラートに表示されたストレージプールを選択し、 * 詳細の表示 * を選択します。
. 追加のストレージ容量が必要かどうかを判断ストレージプール内の各サイトにストレージノードを追加するか、 1 つ以上の既存のストレージノードにストレージボリューム（ LUN ）を追加できます。
. 拡張手順 を実行してストレージ容量を増やします。


link:../expand/index.html["グリッドを展開します"]



 a| 
ノードメモリが不足しています
 a| 
ノードに搭載されているメモリの量が少なくなっています。仮想マシンまたはLinuxホストで使用できるRAMの容量を増やしてください。Major アラートのしきい値を確認して、 StorageGRID ノードのデフォルトの最小要件を決定します。使用しているプラットフォームに対応したインストール手順を参照してください。

* link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]
* link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]
* link:../vmware/index.html["VMware をインストールする"]




 a| 
メタデータストレージが不足しています
 a| 
オブジェクトメタデータを格納できるスペースが少なくなっています。* Criticalアラート*

. オブジェクトの取り込みを停止します。
. 拡張手順 にただちにストレージノードを追加します。


* 主要アラート *

拡張手順 にただちにストレージノードを追加します。

* Minor アラート *

. オブジェクトメタデータスペースの使用率を監視します。ノード*>*_ストレージノード_*>*ストレージ*を選択し、使用済みストレージオブジェクトメタデータのグラフを表示します。
. 拡張手順 にできるだけ早くストレージノードを追加します。


新しいストレージノードが追加されると、すべてのストレージノード間でオブジェクトメタデータが自動的にリバランシングされ、アラームが解除されます。

link:../troubleshoot/troubleshooting-storagegrid-system.html["Low metadata storageアラートのトラブルシューティング"]

link:../expand/index.html["グリッドを展開します"]



 a| 
ディスク容量不足です
 a| 
指標データベースに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
オブジェクトデータのストレージが少ない
 a| 
オブジェクトデータを格納できるスペースが少なくなっています。拡張手順 を実行してください。既存のストレージノードにストレージボリューム（ LUN ）を追加するか、または新しいストレージノードを追加することができます。

link:../troubleshoot/troubleshooting-storagegrid-system.html["Low object data storageアラートのトラブルシューティング"]

link:../expand/index.html["グリッドを展開します"]



 a| 
ルートディスク容量が不足しています
 a| 
ルートディスクに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
システムのデータ容量が不足しています
 a| 
ローカルファイルシステム/var/local上のStorageGRID システムデータに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
ノードのネットワーク接続エラー
 a| 
nodes.Network間でのデータ転送中にエラーが発生した場合、手動操作なしに接続エラーがクリアされることがあります。エラーが解消されない場合は、テクニカルサポートにお問い合わせください。

link:../troubleshoot/troubleshooting-storagegrid-system.html["Network Receive Error（NRER）アラームのトラブルシューティングを行います"]



 a| 
ノードネットワーク受信フレームエラー
 a| 
ノードで受信したネットワークフレームの割合が高いとエラーが発生しました。このアラートは、ケーブル不良やイーサネット接続のいずれかの端のトランシーバ不良など、ハードウェア問題 であることを示している可能性があります。

. アプライアンスを使用している場合は、 SFP+ または SFP28 トランシーバとケーブルを 1 本ずつ交換し、アラートが解除されるかどうかを確認します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
ノードが NTP サーバと同期されていません
 a| 
ノードの時刻がネットワークタイムプロトコル（ NTP ）サーバと同期されていません。

. Stratum 3 以上の外部 NTP サーバが 4 つ以上指定されていることを確認します。
. すべての NTP サーバが正常に動作していることを確認します。
. NTP サーバへの接続を確認します。ファイアウォールによってブロックされていないことを確認してください。




 a| 
NTP サーバでノードがロックされていません
 a| 
ノードがネットワークタイムプロトコル（ NTP ）サーバにロックされていません。

. Stratum 3 以上の外部 NTP サーバが 4 つ以上指定されていることを確認します。
. すべての NTP サーバが正常に動作していることを確認します。
. NTP サーバへの接続を確認します。ファイアウォールによってブロックされていないことを確認してください。




 a| 
非アプライアンスノードネットワークが停止しています
 a| 
1 つ以上のネットワークデバイスが停止しているか切断されています。仮想マシンまたは Linux ホストにインストールされているノードのネットワークインターフェイス（ eth ）にアクセスできないことを示すアラートが表示されます。

テクニカルサポートにお問い合わせください。



 a| 
オブジェクトが失われた
 a| 
グリッドから1つ以上のオブジェクトが失われています。このアラートは、データが永続的に失われて読み出しできなくなったことを示している可能性があります。

. このアラートはすぐに調査してください。これ以上のデータ損失を防ぐための対処が必要になる場合があります。迅速に対処すれば、損失オブジェクトをリストアできる場合もあります。
+
link:../troubleshoot/troubleshooting-storagegrid-system.html["オブジェクトデータの損失と欠落が発生した場合のトラブルシューティング"]

. 原因となっている問題を解決したら、カウンタをリセットします。
+
.. Support *>* Tools *>* Grid Topology *を選択します。
.. アラートを生成したストレージノードに対して、 * _site _ * > * _grid node_name * > * LDR * > * Data Store * > * Configuration * > * Main * の順に選択します。
.. [ * Lost Objects Count * ] を選択し、 [ * Apply Changes * ] をクリックします。






 a| 
プラットフォームサービスを利用できません
 a| 
RSMサービスを搭載したストレージノードが少なすぎて、サイトで稼働中または使用可能です。該当するサイトでRSMサービスを搭載したストレージノードの大部分がエラーのない状態で稼働していることを確認してください。

StorageGRID の管理手順の「プラットフォームサービスのトラブルシューティング」を参照してください。

link:../admin/index.html["StorageGRID の管理"]



 a| 
管理ネットワークポート 1 のサービスアプライアンスリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。

. 管理ネットワークポート 1 に接続されているケーブルと物理的な接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
管理ネットワーク（またはクライアントネットワーク）上のサービスアプライアンスのリンクがダウン
 a| 
管理ネットワーク（ eth1 ）またはクライアントネットワーク（ eth2 ）へのアプライアンスインターフェイスが停止しているか切断されている。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
サービスアプライアンスは、ネットワークポート 1 、 2 、 3 、または 4 でリンクダウンします
 a| 
アプライアンスのネットワークポート 1 、 2 、 3 、または 4 が停止しているか、切断されています。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
サービスアプライアンスストレージの接続がデグレードされました
 a| 
サービスアプライアンス内の2つのSSDのうちの1つで障害が発生したか、もう一方と同期が外れています。アプライアンスの機能には影響はありませんが、問題 にはすぐに対処する必要があります。両方のドライブに障害が発生すると、アプライアンスは動作しなくなります。

. Grid Managerから、* Nodes *>***_services applie__を選択し、** Hardware *タブを選択します。
. Storage RAID Mode * フィールドでメッセージを確認します。
. メッセージに再同期処理の進捗が表示された場合は、処理が完了するのを待ってから、アラートが解決したことを確認します。再同期メッセージは、 SSD が最近交換されたこと、または別の理由で再同期中であることを示します。
. いずれかの SSD で障害が発生したことを示すメッセージが表示された場合は、障害が発生したドライブをできるだけ早く交換します。
+
サービスアプライアンスのドライブを交換する方法については、 SG100 および SG1000 アプライアンスのインストールおよびメンテナンスガイドを参照してください。

+
link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]





 a| 
管理ネットワークポート 1 のストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。

. 管理ネットワークポート 1 に接続されているケーブルと物理的な接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
管理ネットワーク（またはクライアントネットワーク）でのストレージアプライアンスのリンクが停止
 a| 
管理ネットワーク（ eth1 ）またはクライアントネットワーク（ eth2 ）へのアプライアンスインターフェイスが停止しているか切断されている。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
ネットワークポート 1 、 2 、 3 、または 4 でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート 1 、 2 、 3 、または 4 が停止しているか、切断されています。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Managerから* Alerts *>* Alert Rules *を選択し、ルールを選択して* Edit rule *をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:managing-alerts.html["アラートルールを無効にします"]






 a| 
ストレージアプライアンスストレージの接続がデグレードされました
 a| 
コンピューティングコントローラとストレージコントローラの間の接続に問題があります。

. アプライアンスに移動して、ポートのインジケータライトを確認します。
. ポートの LED が消灯している場合は、ケーブルが正しく接続されていることを確認します。必要に応じて、ケーブルを交換します。
. 最大 5 分待ちます。
+

NOTE: 2本目のケーブルを交換する必要がある場合は、5分以上プラグを取り外さないでください。そうしないと、ルートボリュームが読み取り専用になり、ハードウェアの再起動が必要になることがあります。

. Grid Managerから* Nodes *を選択します。次に、問題があるノードの Hardware タブを選択します。アラート状態が解決したことを確認します。




 a| 
ストレージデバイスにアクセスできません
 a| 
ストレージデバイスにアクセスできません。このアラートは、基盤となるストレージデバイスの問題が原因でボリュームをマウントまたはアクセスできないことを示します。

. ノードに使用されているすべてのストレージデバイスのステータスを確認します。
+
** ノードが仮想マシンまたは Linux ホストにインストールされている場合は、オペレーティングシステムに応じた手順に従って、ハードウェアの診断を実行するか、ファイルシステムのチェックを実行します。
+
*** link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]
*** link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]
*** link:../vmware/index.html["VMware をインストールする"]


** ノードが SG100 、 SG1000 、または SG6000 アプライアンスに設置されている場合は、 BMC を使用します。
** ノードが SG5600 アプライアンスまたは SG5700 アプライアンスにインストールされている場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
+
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]






 a| 
テナントクォータの使用率が高い
 a| 
テナントクォータスペースの使用率が高くなっています。テナントのクォータを超えると、新しい取り込みは拒否されます。


NOTE: 多数の通知が生成される可能性があるため、このアラートルールはデフォルトで無効になっています。

. Grid Managerから* tenants *を選択します。
. テーブルを * クォータ使用率 * でソートします。
. クォータ使用率が 100% に近いテナントを選択します。
. 次のいずれか、または両方を実行します。
+
** 「 * Edit * 」を選択して、テナントのストレージ・クォータを増やします。
** クォータ使用率が高いことをテナントに通知します。






 a| 
ノードと通信できません
 a| 
1つ以上のサービスが応答していないか、ノードに到達できません。このアラートは、ノードが不明な理由で切断されたことを示しています。たとえば、ノードのサービスが停止したり、電源障害や予期しない停止によってノードのネットワーク接続が失われたりする場合があります。

このアラートを監視して、問題 が自動的に解決するかどうかを確認します。問題 が維持される場合は、次の手順

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このノードですべてのサービスが実行されていることを確認します。サービスが停止している場合は、開始してみてください。リカバリとメンテナンスの手順を参照してください。
. ノードのホストの電源がオンになっていることを確認します。表示されない場合は、ホストを起動します。
+

NOTE: 複数のホストの電源がオフになっている場合は、リカバリとメンテナンスの手順を参照してください。

. このノードと管理ノードの間にネットワーク接続問題 があるかどうかを確認します。
. このアラートを解決できない場合は、テクニカルサポートにお問い合わせください。


link:../maintain/index.html[""]



 a| 
予期しないノードのリブートです
 a| 
過去 24 時間以内にノードが予期せずリブートされました。

. このアラートを監視します。このアラートは 24 時間後にクリアされます。ただし、ノードが予期せずにリブートされた場合、このアラートは再度トリガーされます。
. アラートを解決できない場合は、ハードウェア障害が発生している可能性があります。テクニカルサポートにお問い合わせください。




 a| 
未識別の破損オブジェクトが検出されました
 a| 
レプリケートオブジェクトストレージにファイルが見つかりましたが、レプリケートオブジェクトとして識別できませんでした。

. ストレージノード上の基盤となるストレージに問題がないかどうかを確認します。たとえば、ハードウェア診断を実行するか、ファイルシステムチェックを実行します。
. ストレージの問題を解決したら、フォアグラウンド検証を実行してオブジェクトが欠落しているかどうかを確認し、可能であれば置き換えます。
. このアラートを監視します。このアラートは 24 時間後にクリアされますが、問題 が修正されていない場合は再度トリガーされます。
. このアラートを解決できない場合は、テクニカルサポートにお問い合わせください。


link:../troubleshoot/troubleshooting-storagegrid-system.html["フォアグラウンド検証を実行しています"]

|===
* 関連情報 *

link:commonly-used-prometheus-metrics.html["よく使用される Prometheus 指標"]
