---
permalink: monitor/generating-charts.html 
sidebar: sidebar 
keywords: charts, generating 
summary: グラフには、属性データ値がグラフィカルな形式で表示されます。データセンターサイト、グリッドノード、コンポーネント、またはサービスについてのレポートを作成できます。 
---
= グラフの生成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グラフには、属性データ値がグラフィカルな形式で表示されます。データセンターサイト、グリッドノード、コンポーネント、またはサービスについてのレポートを作成できます。

.必要なもの
* Grid Managerにはサポートされているブラウザを使用してサインインする必要があります。
* 特定のアクセス権限が必要です。


.手順
. Support *>* Tools *>* Grid Topology *を選択します。
. *_grid node_*>*_component または SERVICE_*>* Reports *>* Charts * を選択します。
. [* 属性 * （ * Attribute * ） ] ドロップダウンリストからレポートする属性を選択します。
. Y 軸をゼロから開始するには、 [ 垂直スケーリング * （ Vertical Scaling * ） ] チェックボックスの選択を解除します。
. 完全精度で値を表示するには、 * 生データ * チェックボックスをオンにするか、小数点以下の桁数を最大 3 桁まで（パーセント値としてレポートされた属性など）丸めを行うには、 * 生データ * チェックボックスの選択を解除します。
. [*Quick Query] ドロップダウン・リストから、レポートする期間を選択します。
+
カスタムクエリオプションを選択して、特定の期間を選択します。

+
グラフが表示されるまでに少し時間がかかります。期間が長い場合は集計に数分かかることもあります。

. [ カスタムクエリ ] を選択した場合は、 [ 開始日 ] と [ 終了日 ] を入力してグラフの期間をカスタマイズします。
+
の形式を使用します `_YYYY/MM/DDHH:MM:SS_` 現地時間。この形式に一致するには、先頭にゼロを補う必要があります。たとえば、「 2017/4/6 7 ： 30 ： 00 」と入力すると検証に失敗します。正しい形式は「 2017/04/06 07 ： 30 ： 00 」です。

. [ 更新（ Update ） ] をクリックします。
+
グラフが生成されるまでに少し時間がかかります。期間が長い場合は集計に数分かかることもあります。クエリで設定した時間の長さに応じて、フルレポートか要約レポートのいずれかが表示されます。

. チャートを印刷する場合は、右クリックして[*Print]を選択し、必要なプリンタ設定を変更して[*Print]をクリックします。

