---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: テキストレポートには、 NMS サービスで処理された属性データの値がテキスト形式で表示されます。データセンターサイト、グリッドノード、コンポーネント、またはサービスについてのレポートを作成できます。 
---
= テキストレポートの生成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テキストレポートには、 NMS サービスで処理された属性データの値がテキスト形式で表示されます。データセンターサイト、グリッドノード、コンポーネント、またはサービスについてのレポートを作成できます。

.必要なもの
* Grid Managerにはサポートされているブラウザを使用してサインインする必要があります。
* 特定のアクセス権限が必要です。


.このタスクについて
継続的に変化することが想定される属性データについては、 NMS サービス（ソース側）によって一定の間隔でデータがサンプリングされます。変化の少ない属性データ（状態やステータスが変わったときに変化するデータなど）については、属性の値が変わったときに NMS サービスに送信されます。

表示されるレポートの種類は、設定されている期間によって異なります。デフォルトでは、期間が 1 週間を超える場合は要約レポートが生成されます。

グレーのテキストは、サンプリング中にサービスが管理上の理由で停止していた期間を示します。青のテキストは、サービスの状態が不明であることを示します。

.手順
. Support *>* Tools *>* Grid Topology *を選択します。
. *_grid node_*>*_component または SERVICE_*>* Reports *>* Text * を選択します。
. [* 属性 * （ * Attribute * ） ] ドロップダウンリストからレポートする属性を選択します。
. 1 ページあたりの結果数を [ * 1 ページあたりの結果数 * （ * Results per Page * ） ] ドロップダウンリストから選択します。
. 最大 3 桁までの値を丸めるには（パーセント値としてレポートされた属性など）、 * 生データ * チェックボックスの選択を解除します。
. [*Quick Query] ドロップダウン・リストから、レポートする期間を選択します。
+
カスタムクエリオプションを選択して、特定の期間を選択します。

+
レポートが表示されるまでに少し時間がかかります。期間が長い場合は集計に数分かかることもあります。

. [ カスタムクエリ ] を選択した場合は、 [ 開始日 ] と [ 終了日 ] を入力してレポートする期間をカスタマイズする必要があります。
+
の形式を使用します `YYYY/MM/DDHH:MM:SS` 現地時間。この形式に一致するには、先頭にゼロを補う必要があります。たとえば、「 2017/4/6 7 ： 30 ： 00 」と入力すると検証に失敗します。正しい形式は「 2017/04/06 07 ： 30 ： 00 」です。

. [ 更新（ Update ） ] をクリックします。
+
テキストレポートが生成されるまでに少し時間がかかります。期間が長い場合は集計に数分かかることもあります。クエリで設定した時間の長さに応じて、フルレポートか要約レポートのいずれかが表示されます。

. レポートを印刷する場合は、右クリックして[*Print]を選択し、必要なプリンタ設定を変更して[*Print]をクリックします。

