---
permalink: monitor/logs-for-third-party-software.html 
sidebar: sidebar 
keywords: troubleshooting, logs 
summary: サードパーティソフトウェアのログを問題のトラブルシューティングに使用できます。 
---
= サードパーティソフトウェアのログ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サードパーティソフトウェアのログを問題のトラブルシューティングに使用できます。

|===
| カテゴリ | ファイル名 | 注： | にあります 


 a| 
apache2のログです
 a| 
`/var/local/log/apache2/access.log /var/local/log/apache2/error.log`

`/var/local/log/apache2/other_vhosts_access.log`
 a| 
apache2のログファイルです。
 a| 
管理ノード



 a| 
アーカイブ
 a| 
`/var/local/log/dsierror.log`
 a| 
TSM クライアント API のエラー情報。
 a| 
アーカイブノード



 a| 
MySQL
 a| 
/var/local/log/mysql.err

`/var/local/log/mysql.err /var/local/log/mysql-slow.log`
 a| 
MySQL によって生成されるログファイルです。

mysql.errファイルには、データベースのエラーと起動やシャットダウンなどのイベントが記録されます。

mysql-slow.logファイル（スロークエリログ）には、実行に10秒以上かかったSQLステートメントが記録されます。
 a| 
管理ノード



 a| 
オペレーティングシステム
 a| 
`/var/local/log/messages`
 a| 
このディレクトリには、オペレーティングシステムのログファイルが格納されます。これらのログに記録されたエラーは、 Grid Manager にも表示されます。Support *>* Tools *>* Grid Topology *を選択します。次に、 * Topology * > * _Site_* > * _Node_* > * SSM * > * Events * を選択します。
 a| 
すべてのノード



 a| 
NTP
 a| 
`/var/local/log/ntp.log`

`/var/lib/ntp/var/log/ntpstats/`
 a| 
。 `/var/local/log/ntp.log` NTPのエラーメッセージのログファイルが格納されます。

。 `/var/lib/ntp/var/log/ntpstats/` Directoryには、NTPタイミング統計情報が格納されます

`loopstats` ループフィルタの統計情報を記録します。

`peerstats` には、ピア統計情報が記録されます
 a| 
すべてのノード



 a| 
サンバ
 a| 
`/var/local/log/samba/`
 a| 
Samba のログディレクトリには、各 Samba プロセス（ smb 、 nmb 、および winbind ）とすべてのクライアントのホスト名 / IP を記録したログファイルが格納されます。
 a| 
CIFS 経由で監査共有をエクスポートするように設定された管理ノード

|===