---
permalink: monitor/managing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: managing, alarms, alerts 
summary: StorageGRID アラートシステムは、注意が必要な運用上の問題について通知するように設計されています。必要に応じて、従来のアラームシステムを使用してシステムを監視することもできます。 
---
= アラートとアラームの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アラートシステムは、注意が必要な運用上の問題について通知するように設計されています。必要に応じて、従来のアラームシステムを使用してシステムを監視することもできます。ここでは、次のサブセクションについて説明します。

* link:comparing-alerts-and-alarms.html["アラートとアラームの比較"]
* link:managing-alerts.html["アラートの管理"]
* link:managing-alarms.html["アラームの管理（従来のシステム）"]


StorageGRID には、問題について通知するための2つのシステムが含まれています。



== アラートシステム

アラートシステムは、 StorageGRID システムで発生する可能性のある問題を監視する主要なツールです。アラートシステムは、問題を検出、評価、解決するための使いやすいインターフェイスを提供します。

アラートルールの条件が true と評価されると、特定の重大度レベルでアラートがトリガーされます。アラートがトリガーされると、次の処理が行われます。

* アラートの重大度アイコンはグリッドマネージャのダッシュボードに表示され、現在のアラートの数が増えます。
* このアラートはノード*>*_node_name >* Overview *タブに表示されます。
* SMTP サーバを設定し、受信者に E メールアドレスを提供している場合は、 E メール通知が送信されます。
* StorageGRID SNMP エージェントが設定されている場合は、簡易ネットワーク管理プロトコル（ SNMP ）通知が送信されます。




== レガシーアラームシステム

アラームシステムはサポートされていますが、従来型システムとみなされます。アラートと同様に、属性が定義されたしきい値に達すると、特定の重大度レベルでアラームがトリガーされます。ただし、アラートとは異なり、無視しても問題なくアラートがトリガーされるアラームが多数あるため、 E メールや SNMP 通知が大量に送信されることがあります。

アラームがトリガーされると、次の処理が行われます。

* ダッシュボードに表示されていた古いアラームの数が増えます。
* このアラームは、[*Support*>*Alarms (legac)*>*Current Alarms]ページに表示されます。
* SMTP サーバを設定して 1 つ以上のメーリングリストを設定している場合は、 E メール通知が送信されます。
* StorageGRID SNMP エージェントを設定している場合は、 SNMP 通知が送信されることがあります。（ SNMP 通知は、すべてのアラームまたはアラームの重大度について送信されるわけではありません）。

