---
permalink: monitor/monitoring-events.html 
sidebar: sidebar 
keywords: monitor, monitoring events, events, storageGRID events 
summary: グリッドノードによって検出されたイベントを監視できます。これには、 syslog サーバに記録されたイベントを追跡するために作成したカスタムイベントも含まれます。グリッドマネージャに表示される Last Event メッセージには、最新のイベントに関する詳細が表示されます。 
---
= イベントの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードによって検出されたイベントを監視できます。これには、 syslog サーバに記録されたイベントを追跡するために作成したカスタムイベントも含まれます。グリッドマネージャに表示される Last Event メッセージには、最新のイベントに関する詳細が表示されます。

イベントメッセージは、にも表示されます `/var/local/log/bycast-err.log` ログファイル：

SMTT （ Total events ）アラームは、ネットワークの問題、電源の停止、アップグレードなどの問題によって繰り返しトリガーされることがあります。このセクションでは、イベントを調査する方法について説明します。これにより、これらのアラームが発生した理由をより詳しく理解できます。既知の問題 が原因でイベントが発生した場合、イベントカウンタをリセットしても安全です。



== Nodesページでイベントを確認します

ノードページには、各グリッドノードのシステムイベントがリストされます。

. [*ノード（* Nodes）]を選択し
. *_grid node_*>* Eventsを選択します。
. ページの上部で、グリッドノードで検出された最後のイベントを示す「* Last Event *」のイベントが表示されるかどうかを確認します。
+
イベントはグリッドノードからそのままリレーされ、重大度レベルが「ERROR」または「CRITICAL」のログメッセージがすべて含まれます。

. テーブルを参照して、イベントまたはエラーの数がゼロでないことを確認します。
. 問題を解決したら、[イベントカウントのリセット*]をクリックしてカウントをゼロに戻します。




== グリッドトポロジページでイベントを確認する

また、グリッドトポロジページには、グリッドノードごとのシステムイベントも表示されます。

. Support *>* Tools *>* Grid Topology *を選択します。
. [*_site *>] > [*_grid node_*>] > * ssm * > * Events * > * Overview * > * Main * の順に選択します。


.関連情報
link:resetting-event-counts.html["イベント数のリセット"]

link:../monitor/logs-files-reference.html["ログファイル参照"]
