---
permalink: maintain/all-node-types-replacing-linux-node.html 
sidebar: sidebar 
keywords:  
summary: 障害に対処するために 1 つ以上の新しい物理ホストまたは仮想ホストを導入するか、または既存のホストに Linux を再インストールする必要がある場合は、グリッドノードをリカバリする前に交換ホストを導入して設定する必要があります。この手順 は、すべてのタイプのグリッドノードのリカバリプロセスの 1 つのステップです。 
---
= すべてのグリッドノードタイプ：Linuxノードの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害に対処するために 1 つ以上の新しい物理ホストまたは仮想ホストを導入するか、または既存のホストに Linux を再インストールする必要がある場合は、グリッドノードをリカバリする前に交換ホストを導入して設定する必要があります。この手順 は、すべてのタイプのグリッドノードのリカバリプロセスの 1 つのステップです。

「 Linux 」とは、 Red Hat ® Enterprise Linux ® 、 Ubuntu ® 、 CentOS 、または Debian ® の環境を指します。サポートされているバージョンの一覧については、 NetApp Interoperability Matrix Tool を参照してください。

この手順 は、ソフトウェアベースのストレージノード、プライマリまたは非プライマリ管理ノード、ゲートウェイノード、またはアーカイブノードのリカバリプロセスの一部としてのみ実行されます。リカバリするグリッドノードのタイプに関係なく、手順は同じです。

物理 / 仮想 Linux ホストで複数のグリッドノードがホストされている場合は、任意の順序でグリッドノードをリカバリできます。ただし、プライマリ管理ノードがある場合は最初にリカバリします。リカバリのためにプライマリ管理ノードに接続しようとするときに、他のグリッドノードのリカバリが停止することはありません。

. link:deploying-new-linux-hosts.html["新しいLinuxホストの導入"]
. link:restoring-existing-nodes.html["ホストへのグリッドノードのリストア"]
. link:whats-next-performing-additional-recovery-steps-if-required.html["次の手順：必要に応じて追加のリカバリ手順を実行します"]


.関連情報
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]
