---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: storagegrid, ip address, configure ip address, configuring ip address, network configuration, network configure, network configuring 
summary: IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。 
---
= IPアドレスを設定しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。

グリッドの導入時に設定されたネットワーク設定を変更するには、ほとんどの場合、 IP 変更ツールを使用する必要があります。標準の Linux ネットワークコマンドおよびファイルを使用して手動で変更すると、すべての StorageGRID サービスに変更が反映されなかったり、アップグレード、リブート、ノードリカバリ手順の実行後に変更が失われたりすることがあります。


NOTE: グリッド内のすべてのノードのグリッドネットワークIPアドレスを変更する場合は、グリッド全体で特別な手順 を使用します。

link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["グリッド内のすべてのノードのIPアドレスの変更"]


NOTE: グリッドネットワークサブネットリストのみを変更する場合は、グリッドマネージャを使用してネットワーク設定の追加または変更を行います。グリッドネットワーク設定問題 が原因でグリッドマネージャにアクセスできない場合、またはグリッドネットワークルーティングの変更とその他のネットワーク変更を同時に実行する場合は、 IP 変更ツールを使用します。


IMPORTANT: IP 変更手順 は、停止を伴う手順 の可能性があります。グリッドの一部は、新しい設定が適用されるまで使用できない場合があります。

* イーサネット・インターフェイス *

eth0 に割り当てられる IP アドレスは、常にグリッドノードのグリッドネットワーク IP アドレスになります。eth1 に割り当てられている IP アドレスは、常にグリッドノードの管理ネットワーク IP アドレスです。eth2 に割り当てられている IP アドレスは、常にグリッドノードのクライアントネットワーク IP アドレスです。

StorageGRID アプライアンスなどの一部のプラットフォームでは、 eth0 、 eth1 、 eth2 が、下位のブリッジで構成されるアグリゲートインターフェイスや物理 / VLAN インターフェイスのボンドである場合があります。これらのプラットフォームでは、* SSM * Resources *タブに、eth0、eth1、eth2に加えて、他のインターフェイスに割り当てられているグリッドネットワーク、管理ネットワーク、およびクライアントネットワークのIPアドレスが表示されることがあります。

* DHCP *

DHCP は導入フェーズでのみ設定できます。設定時に DHCP を設定することはできません。グリッドノードの IP アドレス、サブネットマスク、およびデフォルトゲートウェイを変更する場合は、 IP アドレス変更手順を使用する必要があります。IP 変更ツールを使用すると、原因 の DHCP アドレスが静的アドレスになります。

* ハイアベイラビリティ（ HA ）グループ *

* クライアントネットワークIPアドレスは、クライアントネットワークインターフェイスで設定されたHAグループのサブネット以外に変更することはできません。
* クライアントネットワークIPアドレスを、クライアントネットワークインターフェイスで設定されたHAグループによって割り当てられた既存の仮想IPアドレスの値に変更することはできません。
* グリッドネットワークのIPアドレスは、グリッドネットワークインターフェイスで設定されているHAグループのサブネット以外に変更することはできません。
* グリッドネットワークのIPアドレスを、グリッドネットワークのインターフェイスで設定されたHAグループによって割り当てられた既存の仮想IPアドレスの値に変更することはできません。


.選択肢
* link:changing-nodes-network-configuration.html["ノードのネットワーク設定を変更する"]
* link:adding-to-or-changing-subnet-lists-on-admin-network.html["管理ネットワークのサブネットリストに対する追加または変更"]
* link:adding-to-or-changing-subnet-lists-on-grid-network.html["グリッドネットワークのサブネットリストに対する追加または変更"]
* link:linux-adding-interfaces-to-existing-node.html["Linux：既存のノードへのインターフェイスの追加"]
* link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["グリッド内のすべてのノードのIPアドレスの変更"]

