---
permalink: maintain/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。 
---
= アプライアンスノードのクローニングに関する考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。



== 交換用アプライアンスのハードウェア要件

交換用アプライアンスが次の基準を満たしていることを確認します。

* ソースノード（交換するアプライアンス）とターゲット（新しい）アプライアンスは、同じタイプのアプライアンスである必要があります。
+
** クローニングできるのは、管理ノードアプライアンスまたはゲートウェイノードアプライアンスだけです。
** クローニングできるのは、新しいストレージアプライアンスに対してのみです。


* 管理ノードまたはゲートウェイノードアプライアンスの場合、ソースノードアプライアンスとターゲットアプライアンスで同じタイプのアプライアンスを使用する必要はありません。ただし、アプライアンスタイプを変更する場合は、ケーブルまたは SFP モジュールの交換が必要になることがあります。
+
たとえば、 SG1000 ノードアプライアンスを SG100 に交換したり、 SG100 アプライアンスを SG1000 アプライアンスに交換したりできます。

* ストレージノードアプライアンスの場合、ソースノードアプライアンスとターゲットアプライアンスのストレージ容量がソースアプライアンスと同じである必要はありません。ただし、ターゲットアプライアンスのストレージ容量はソースアプライアンスと同じかそれ以上である必要があります。
+
たとえば、 SG5600 ノードアプライアンスを、 SG5700 アプライアンスまたは SG6000 アプライアンスと交換することができます。



StorageGRID 環境の特定のアプライアンスノードをクローニングする互換性のある交換用アプライアンスを選択する方法については、 StorageGRID の営業担当者にお問い合わせください。



== アプライアンスノードのクローンを作成する準備をしています

アプライアンスノードをクローニングするには、次の情報が必要です。

* グリッドネットワークの一時的な IP アドレスをネットワーク管理者から取得し、最初のインストール時にターゲットアプライアンスで使用します。ソースノードが管理ネットワークまたはクライアントネットワークに属している場合は、それらのネットワークの一時的な IP アドレスを取得します。
+
一時的な IP アドレスは通常、クローニングするソースノードアプライアンスと同じサブネット上にあり、クローニングの完了後は必要ありません。クローニング接続を確立するには、ソースアプライアンスとターゲットアプライアンスの両方が StorageGRID のプライマリ管理ノードに接続されている必要があります。

* データ転送トラフィックのクローニングに使用するネットワークを決定し、 StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを実現します。
+

NOTE: 1GbE 管理ネットワークを使用したクローニングでデータ転送を行うと、クローニングに時間がかかります。

* ターゲットアプライアンスでキー管理サーバ（ KMS ）を使用したノード暗号化が使用されるかどうかを確認し、クローニングを実行する前に最初のターゲットアプライアンスインストール時にノードの暗号化を有効にできるようにします。アプライアンスのインストールの説明に従って、ソースアプライアンスノードでノード暗号化が有効になっているかどうかを確認できます。
+
ソースノードとターゲットアプライアンスで、異なるノード暗号化設定を使用できます。データの復号化と暗号化は、データ転送中、およびターゲットノードが再起動してグリッドに参加したときに自動的に実行されます。

+
** link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]
** link:../sg5600/index.html["SG5600 ストレージアプライアンス"]
** link:../sg5700/index.html["SG5700 ストレージアプライアンス"]
** link:../sg6000/index.html["SG6000 ストレージアプライアンス"]


* ターゲット・アプライアンスの RAID モードをデフォルト設定から変更するかどうかを決定します。このため、この情報は、クローニングの前にターゲット・アプライアンスを最初にインストールするときに指定できます。ソースアプライアンスノードの現在のRAIDモードに関する情報は、Grid Managerの* Nodes *ページで確認できます。アプライアンスの [*Storage*] タブを選択します。
+
ソースノードとターゲットアプライアンスでは、 RAID 設定が異なる場合があります。

* ノードのクローニングプロセスを完了するための十分な時間を計画します。稼働中のストレージノードからターゲットアプライアンスにデータを転送するために、数日かかる場合があります。クローニングのスケジュールを一度に設定して、ビジネスへの影響を最小限に抑えることができます。
* クローニングするアプライアンスノードは一度に 1 つだけにしてください。クローニングによって、 StorageGRID の他のメンテナンス機能を同時に実行することはできません。
* アプライアンスノードのクローンを作成したら、互換性のある別のノードアプライアンスのクローンを作成するために、インストール前の状態に戻ったソースアプライアンスをターゲットとして使用できます。

