---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: リカバリパッケージファイルを使用すると、障害発生時に StorageGRID システムをリストアできます。 
---
= リカバリパッケージをダウンロードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リカバリパッケージファイルを使用すると、障害発生時に StorageGRID システムをリストアできます。

.必要なもの
* Grid Managerにはサポートされているブラウザを使用してサインインする必要があります。
* プロビジョニングパスフレーズが必要です。
* 特定のアクセス権限が必要です。


StorageGRID システムでグリッドトポロジの変更を行う前、またはソフトウェアをアップグレードする前に、現在のリカバリパッケージファイルをダウンロードしてください。グリッドトポロジを変更するかソフトウェアをアップグレードしたあとに、リカバリパッケージの新しいコピーをダウンロードします。

.手順
. [* Maintenance * （メンテナンス） ] > [* System * （システム * ） ] > [* Recovery Package] （リカバリパッケージ * ）
. プロビジョニングパスフレーズを入力し、 * ダウンロードの開始 * を選択します。
+
ダウンロードがすぐに開始されます。

. ダウンロードが完了したら、次の手順を実行
+
.. を開きます `.zip` ファイル。
.. これには、gpt-backupディレクトリと内部が含まれていることを確認します `.zip` ファイル。
.. 内側を引き出します `.zip` ファイル。
.. を開くことができることを確認します `Passwords.txt` ファイル。


. ダウンロードしたリカバリパッケージファイルをコピーします (`.zip`)を2箇所に安全に、安全に、そして別 々 の場所に移動します。
+

IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。



.関連情報
link:../admin/index.html["StorageGRID の管理"]
