---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: メンテナンス手順を実行する前に、障害グリッドノードのリカバリに必要な情報、ファイル、機器などが揃っていることを確認する必要があります。 
---
= グリッドノードリカバリに必要な項目の収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メンテナンス手順を実行する前に、障害グリッドノードのリカバリに必要な情報、ファイル、機器などが揃っていることを確認する必要があります。

[cols="1a,2a"]
|===
| 項目 | 注： 


 a| 
StorageGRID インストールアーカイブ
 a| 
グリッドノードをリカバリする必要がある場合は、使用しているプラットフォーム用のStorageGRID インストールアーカイブが必要です。

* 注： * ストレージノード上の障害ストレージボリュームをリカバリする場合、ファイルをダウンロードする必要はありません。



 a| 
リカバリパッケージ `.zip` ファイル。
 a| 
最新のリカバリパッケージのコピーを取得します `.zip` ファイル：
`sgws-recovery-package-_id-revision_.zip`

の内容 `.zip` ファイルは、システムが変更されるたびに更新されます。そのような変更を行うと、最新バージョンのリカバリパッケージを安全な場所に保管するよう求められます。グリッド障害からリカバリするには、最新のコピーを使用します。

プライマリ管理ノードが正常に動作している場合は、 Grid Manager からリカバリパッケージをダウンロードできます。[Maintenance * System * Recovery Package]を選択します。

Grid Manager にアクセスできない場合は、 ADC サービスが含まれる一部のストレージノードにリカバリパッケージの暗号化コピーがあります。各ストレージノードで、リカバリパッケージが格納された場所を確認します。 `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` リビジョン番号が最も大きいリカバリパッケージを使用してください。



 a| 
`Passwords.txt` ファイル。
 a| 
コマンドラインでグリッドノードにアクセスするために必要なパスワードが含まれています。リカバリパッケージに含まれています。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズはに含まれていません `Passwords.txt` ファイル。



 a| 
ご使用のプラットフォームの最新ドキュメント
 a| 
現在サポートされているプラットフォームのバージョンについては、Interoperability Matrix Toolを参照してください。

https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

ドキュメントについては、プラットフォームのベンダーの Web サイトを参照してください。

|===
.関連情報
link:downloading-and-extracting-storagegrid-installation-files.html["StorageGRID インストールファイルのダウンロードと展開"]

link:web-browser-requirements.html["Web ブラウザの要件"]
