---
permalink: maintain/introduction-to-storagegrid-recovery-and-maintenance.html 
sidebar: sidebar 
keywords: storagegrid, recovery, maintenance 
summary: StorageGRID のリカバリとメンテナンスの手順には、ソフトウェアホットフィックスの適用、グリッドノードのリカバリ、障害が発生したサイトのリカバリ、グリッドノードまたはサイト全体の運用停止、ネットワークメンテナンスの実行、ホストレベルおよびミドルウェアのメンテナンス手順の実行、グリッドノードの手順の実行が含まれます。 
---
= StorageGRID のリカバリとメンテナンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID のリカバリとメンテナンスの手順には、ソフトウェアホットフィックスの適用、グリッドノードのリカバリ、障害が発生したサイトのリカバリ、グリッドノードまたはサイト全体の運用停止、ネットワークメンテナンスの実行、ホストレベルおよびミドルウェアのメンテナンス手順の実行、グリッドノードの手順の実行が含まれます。

リカバリとメンテナンスのすべての作業には、StorageGRID システムに関する幅広い知識が必要です。StorageGRID システムのトポロジを確認して、グリッドの設定を把握しておく必要があります。

すべての指示に厳密に従い、すべての警告に注意する必要があります。

ここで説明していないメンテナンス手順は、サポートされていない手順であるか、またはサービス契約が必要

ハードウェアの手順については、使用している StorageGRID アプライアンスのインストールとメンテナンスの手順を参照してください。


NOTE: 「 Linux 」とは、 Red Hat ® Enterprise Linux ® 、 Ubuntu ® 、 CentOS 、または Debian ® の環境を指します。サポートされているバージョンの一覧については、 NetApp Interoperability Matrix Tool を参照してください。

.関連情報
link:../primer/index.html["グリッド入門"]

link:../network/index.html["ネットワークガイドライン"]

link:../admin/index.html["StorageGRID の管理"]

link:../sg100-1000/index.html["SG100 SG1000サービスアプライアンス"]

link:../sg6000/index.html["SG6000 ストレージアプライアンス"]

link:../sg5700/index.html["SG5700 ストレージアプライアンス"]

link:../sg5600/index.html["SG5600 ストレージアプライアンス"]

https://["NetApp Interoperability Matrix Tool で確認できます"]
