---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, adding interfaces, add interfaces, adding interface to node, add interface to node 
summary: 最初にインストールしなかったLinuxベースのノードにインターフェイスを追加する場合は、この手順 を使用する必要があります。 
---
= Linux：既存のノードへのインターフェイスの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最初にインストールしなかったLinuxベースのノードにインターフェイスを追加する場合は、この手順 を使用する必要があります。

インストール時に Linux ホスト上のノード構成ファイルで ADMIN_NETWORK_TARGET または ADMIN_NETWORK_TARGET を設定しなかった場合は、この手順 を使用してインターフェイスを追加します。ノード構成ファイルの詳細については、使用しているLinuxオペレーティングシステムでのStorageGRID のインストール手順を参照してください。

link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]

link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]

この手順 は、ノード内ではなく、新しいネットワーク割り当てが必要なノードをホストしている Linux サーバ上で実行します。この手順 で追加されるのはノードだけです。他のネットワークパラメータを指定しようとすると、検証エラーが発生します。

アドレス情報を指定するには、 IP 変更ツールを使用する必要があります。ノードのネットワーク設定の変更に関する情報を参照してください。

link:changing-nodes-network-configuration.html["ノードのネットワーク設定を変更する"]

.手順
. 新しいネットワーク割り当てが必要なノードをホストしているLinuxサーバにログインします。
. ノード構成ファイルを編集します `/etc/storagegrid/nodes/_node-name_.conf`。
+

IMPORTANT: 他のネットワークパラメータを指定しないでください。検証エラーが発生します。

+
.. 新しいネットワークターゲットを追加します。
+
[listing]
----
CLIENT_NETWORK_TARGET = bond0.3206
----
.. オプション：MACアドレスを追加します。
+
[listing]
----
CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c
----


. node validate コマンドを実行します。 `sudo storagegrid node validate _node-name_`
. 検証エラーをすべて解決します。
. node reload コマンドを実行します。 `sudo storagegrid node reload _node-name_`


.関連情報
link:../rhel/index.html["Red Hat Enterprise Linux または CentOS をインストールします"]

link:../ubuntu/index.html["Ubuntu または Debian をインストールします"]

link:changing-nodes-network-configuration.html["ノードのネットワーク設定を変更する"]
