---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。 
---
= ホットフィックスに必要な項目の確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。

[cols="1a,2a"]
|===
| 項目 | 注： 


 a| 
StorageGRID ホットフィックスファイル
 a| 
StorageGRID ホットフィックスファイルをダウンロードする必要があります。



 a| 
* ネットワークポート
* サポートされている Web ブラウザ
* SSH クライアント（ PuTTY など）

 a| 
「Webブラウザの要件」を参照してください。



 a| 
リカバリパッケージ (`.zip`)ファイル
 a| 
ホットフィックスを適用する前に、ホットフィックスの適用中に問題が発生した場合に最新のリカバリパッケージファイルをダウンロードします。その後、ホットフィックスの適用後に、リカバリパッケージファイルの新しいコピーをダウンロードして安全な場所に保存します。更新されたリカバリパッケージファイルは、障害発生時のシステムのリストアに使用できます。



| Passwords.txt ファイル  a| 
任意。 SSH クライアントを使用してホットフィックスを手動で適用する場合にのみ使用します。。 `Passwords.txt` ファイルは、リカバリパッケージに含まれるSAIDパッケージに含まれています `.zip` ファイル。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズは、に表示されません `Passwords.txt` ファイル。



 a| 
関連ドキュメント
 a| 
`readme.txt` ホットフィックスのファイル。このファイルは、ホットフィックスのダウンロードページにあります。必ずを確認してください `readme` ホットフィックスを適用する前にファイルを慎重に作成してください

|===
.関連情報
link:downloading-hotfix-file.html["ホットフィックスファイルをダウンロードしています"]

link:downloading-recovery-package.html["リカバリパッケージをダウンロードしています"]
