---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。 
---
= ポートの再マッピングの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。


CAUTION: この手順 は、ポートの再マッピングをすべて削除します。一部の再マッピングを保持する必要がある場合は、テクニカルサポートにお問い合わせください。

ロードバランサエンドポイントの設定については、 StorageGRID の管理手順を参照してください。


IMPORTANT: ポートの再マッピングでクライアントアクセスが提供される場合は、可能であればロードバランサエンドポイントとして設定した別のポートを使用するようにクライアントを再設定してください。そうしないと、ポートマッピングを削除してクライアントアクセスが失われるため、適切にスケジュールを設定する必要があります。


IMPORTANT: この手順 は、ベアメタルホスト上のコンテナとして導入した StorageGRID システムでは機能しません。ベアメタルホストでのポートの再マッピングの削除手順を参照してください。

.手順
. ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh -p 8022 admin@node_IP`
+
ポート8022はベースOSのSSHポートで、ポート22はStorageGRID を実行しているDockerコンテナのSSHポートです。

.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 次のスクリプトを実行します。 `remove-port-remap.sh`
. ノードをリブートします。
+
グリッドノードのリブート手順に従ってください。

. 再マッピングされたポートが競合している管理ノードおよびゲートウェイノードごとに上記の手順を繰り返します。


.関連情報
link:../admin/index.html["StorageGRID の管理"]

link:rebooting-grid-node.html["グリッドノードのリブート"]

link:removing-port-remaps-on-bare-metal-hosts.html["ベアメタルホストでのポートの再マッピングの削除"]
