---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: 障害が発生した非プライマリ管理ノードの属性、アラーム、およびアラートの履歴情報を維持したい場合は、プライマリ管理ノードから管理ノードデータベースをリストアします。 
---
= 非プライマリ管理ノードをリカバリする際の管理ノードデータベースのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した非プライマリ管理ノードの属性、アラーム、およびアラートの履歴情報を維持したい場合は、プライマリ管理ノードから管理ノードデータベースをリストアします。

* リカバリした管理ノードをインストールして実行する必要があります。
* StorageGRID システムには管理ノードが少なくとも 2 つ必要です。
* を用意しておく必要があります `Passwords.txt` ファイル。
* プロビジョニングパスフレーズが必要です。


管理ノードで障害が発生すると、その管理ノードデータベースに格納されていた履歴情報が失われます。このデータベースには次の情報が含まれています。

* アラートの履歴
* アラームの履歴
* 履歴属性データ。サポート**ツール*グリッドトポロジ*ページで確認できるチャートおよびテキストレポートで使用されます。


管理ノードをリカバリする際に、ソフトウェアのインストールプロセスによって、リカバリしたノードに空の管理ノードデータベースが作成されます。ただし、新しいデータベースには、現在システムに含まれているサーバとサービス、またはあとで追加されたサーバの情報だけが含まれます。

非プライマリ管理ノードをリストアした場合は、プライマリ管理ノード（ _source Admin Node_） の管理ノードデータベースをリカバリしたノードにコピーすることで、履歴情報をリストアできます。


NOTE: 管理ノードデータベースのコピーには数時間かかることがあります。ソースノードでサービスが停止している間は、 Grid Manager の一部の機能が使用できなくなります。

. ソース管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


. ソース管理ノードから次のコマンドを実行します。プロンプトが表示されたら、プロビジョニングパスフレーズを入力します。 `recover-access-points`
. ソース管理ノードからMIサービスを停止します。 `service mi stop`
. ソース管理ノードから、管理アプリケーションプログラミングインターフェイス（mgmt-api）サービスを停止します。 `service mgmt-api stop`
. リカバリした管理ノードで次の手順を実行します。
+
.. リカバリした管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。


.. MIサービスを停止します。 `service mi stop`
.. mgmt-apiサービスを停止します。 `service mgmt-api stop`
.. SSH エージェントに SSH 秘密鍵を追加します。入力するコマンド``ssh-add``
.. に記載されているSSHアクセスパスワードを入力します `Passwords.txt` ファイル。
.. ソース管理ノードのデータベースをリカバリした管理ノードにコピーします。 `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. プロンプトが表示されたら、リカバリした管理ノードで MI データベースを上書きすることを確定します。
+
データベースとその履歴データが、リカバリした管理ノードにコピーされます。コピー処理が完了すると、リカバリした管理ノードがスクリプトによって起動されます。

.. 他のサーバにパスワードなしでアクセスする必要がなくなった場合は、 SSH エージェントから秘密鍵を削除します。入力するコマンド``ssh-add -D``


. ソース管理ノードでサービスを再起動します。 `service servermanager start`

