---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: グリッドノードは、ノードのコマンドシェルからシャットダウンできます。 
---
= グリッドノードをシャットダウンしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードは、ノードのコマンドシェルからシャットダウンできます。

.必要なもの
* を用意しておく必要があります `Passwords.txt` ファイル。


.このタスクについて
この手順 を実行する前に、次の考慮事項を確認してください。

* 通常は、業務の中断を避けるために、一度に複数のノードをシャットダウンすることは避けてください。
* ドキュメントまたはテクニカルサポートから指示があった場合を除き、メンテナンス手順 の実行中にノードをシャットダウンしないでください。
* シャットダウンプロセスは、ノードがインストールされている場所によって次のように異なります。
+
** VMware ノードをシャットダウンすると、仮想マシンがシャットダウンされます。
** Linux ノードをシャットダウンすると、コンテナがシャットダウンされます。
** StorageGRID アプライアンスノードをシャットダウンすると、コンピューティングコントローラがシャットダウンされます。


* ストレージノードをシャットダウンする場合は、次の点に注意してください。
+
** ILM ルールに取り込み動作に Dual commit が指定されている場合、またはルールで Balanced が指定されていて、必要なすべてのコピーをただちに作成できない場合は、 StorageGRID は新たに取り込まれたオブジェクトをただちに同じサイトの 2 つのストレージノードにコミットしてあとから ILM を評価します。1 つのサイトで複数のストレージノードをシャットダウンすると、シャットダウン中はこれらのオブジェクトにアクセスできない場合があります。
** ストレージノードのシャットダウン中もすべてのオブジェクトにアクセスできるようにするには、ノードをシャットダウンする前に、サイトでのオブジェクトの取り込みを約 1 時間停止します。




.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。

. すべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. コマンドシェルからログアウトします。 `exit`


シャットダウンしたら、グリッドノードの電源をオフにすることができます。

link:powering-down-host.html["ホストの電源のオフ"]

.関連情報
link:../admin/index.html["StorageGRID の管理"]
