---
permalink: maintain/troubleshooting-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, recover, decommission, troubleshoot 
summary: エラーが原因でノードの手順 の運用が停止した場合は、特定の手順に従って問題のトラブルシューティングを実施できます。 
---
= ノードの運用停止のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エラーが原因でノードの手順 の運用が停止した場合は、特定の手順に従って問題のトラブルシューティングを実施できます。

.必要なもの
Grid Managerにはサポートされているブラウザを使用してサインインする必要があります。

.このタスクについて
運用停止処理中のグリッドノードをシャットダウンすると、グリッドノードが再起動されるまでタスクが停止します。グリッドノードはオンラインである必要があります。

.手順
. Support *>* Tools *>* Grid Topology *を選択します。
. グリッドトポロジツリーで各ストレージノードエントリを展開し、 DDS サービスと LDR サービスがオンラインになっていることを確認します。
+
ストレージノードの運用を停止するには、StorageGRID システムのDDSサービス（ストレージノードでホストされるサービス）がオンラインになっている必要があります。これはILMルールによる再評価の要件です。

. アクティブなグリッドタスクを表示するには、「* primary Admin Node * CMN *** Grid Tasks * Overview *」を選択します。
. グリッドタスクの運用停止のステータスを確認します。
+
.. グリッドタスクの運用停止ステータスがグリッドタスクバンドルの保存の問題を示している場合は、「* primary Admin Node ** CMN * Events * Overview *」を選択します
.. 使用可能な監査リレーの数を確認します。
+
Available Audit Relay 属性が 1 つ以上の場合、 CMN サービスは少なくとも 1 つの ADC サービスに接続されています。ADC サービスは監査リレーとして機能します。

+
グリッドタスクで運用停止処理をあるステージから別のステージに進めて終了させるには、 CMN サービスが少なくとも 1 つの ADC サービスに接続され、かつ StorageGRID システムの ADC サービスの過半数（ 50%+1 ）が使用可能である必要があります。

.. CMN サービスが十分な数の ADC サービスに接続されていない場合は、ストレージノードがオンラインであることを確認し、プライマリ管理ノードとストレージノードの間のネットワーク接続を確認します。



