---
permalink: primer/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: audit message 
summary: 監査メッセージは、 StorageGRID システムの詳細な運用状況を的確に把握するために役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。 
---
= 監査メッセージの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージは、 StorageGRID システムの詳細な運用状況を的確に把握するために役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。

通常のシステム運用中、すべての StorageGRID サービスは次の監査メッセージを生成します。

* システム監査メッセージは、監査システム自体、グリッドノードの状態、システム全体のタスクアクティビティ、およびサービスバックアップ処理に関連します。
* オブジェクトストレージの監査メッセージは、オブジェクトの格納と読み出し、グリッドノードからグリッドノードへの転送、検証など、 StorageGRID 内のオブジェクトの格納と管理に関連します。
* クライアント読み取り / 書き込み監査メッセージは、 S3 または Swift クライアントアプリケーションがオブジェクトの作成、変更、または読み出しの要求を行うときに記録されます。
* 管理監査メッセージには、管理 API に対するユーザ要求が記録されます。


各管理ノードで、監査メッセージがテキストファイルに保存されます。監査共有には、アクティブファイル（ audit.log ）と、圧縮された過去の監査ログが含まれています。

監査ログへのアクセスを簡単にするためには、NFSとCIFSの両方についてクライアントから監査共有へのアクセスを設定します（現在CIFSは廃止）。管理ノードのコマンドラインから直接監査ログファイルにアクセスすることもできます。

監査ログファイル、監査メッセージの形式、監査メッセージの種類、および監査メッセージを分析するためのツールの詳細については、監査メッセージに関する手順を参照してください。監査クライアントアクセスの設定方法については、 StorageGRID の管理手順を参照してください。

.関連情報
link:../audit/index.html["監査ログを確認します"]

link:../admin/index.html["StorageGRID の管理"]
