---
permalink: expand/configuring-expanded-storagegrid-system.html 
sidebar: sidebar 
keywords: expansion, configuration 
summary: 拡張が完了したら、統合と設定のための追加の手順を実行する必要があります。 
---
= 拡張後のStorageGRID システムの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張が完了したら、統合と設定のための追加の手順を実行する必要があります。

.このタスクについて
拡張で追加するグリッドノードに応じて、次の表の設定タスクを実行する必要があります。システムのインストールや管理の作業で選択したオプションのほか、拡張で追加したグリッドノードの設定方法によっては、省略可能なタスクもあります。

.手順
. ストレージノードを追加した場合は、次の設定タスクを実行します。
+
[cols="2a,1a"]
|===
| ストレージノードの設定タスク | を参照してください 


 a| 
ILM ルールで使用されているストレージプールを確認して、新しいストレージが使用されるようにします。

** サイトを追加した場合は、そのサイトのストレージプールを作成し、新しいストレージプールを使用する ILM ルールを更新します。
** 既存のサイトにストレージノードを追加した場合は、新しいノードが正しいストレージグレードを使用していることを確認します。
+
*注：デフォルトでは、新しいストレージノードがAll Storage Nodesストレージグレードに割り当てられ、そのグレードを使用するストレージプールに追加されます。新しいノードでカスタムのストレージグレードを使用する場合は、カスタムグレードに手動で割り当てる必要があります（* ILM *>*ストレージグレード*）。


 a| 
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]



 a| 
ストレージノードがオブジェクトを取り込んでいることを確認する。
 a| 
link:verifying-storage-node-is-active.html["ストレージノードがアクティブであることを確認しています"]



 a| 
イレイジャーコーディングデータのリバランシングを行います（推奨数のストレージノードを追加できなかった場合のみ）。
 a| 
link:rebalancing-erasure-coded-data-after-adding-storage-nodes.html["ストレージノードの追加後におけるイレイジャーコーディングデータのリバランシング"]

|===
. ゲートウェイノードを追加した場合は、次の設定タスクを実行します。
+
[cols="2a,1a"]
|===
| ゲートウェイノードの設定作業 | を参照してください 


 a| 
クライアント接続にハイアベイラビリティグループが使用される場合は、HAグループにゲートウェイノードを追加します。既存のHAグループのリストを確認して新しいノードを追加するには、* Configuration *>* Network Settings *>* High Availability Groups *を選択します。
 a| 
link:../admin/index.html["StorageGRID の管理"]

|===
. 管理ノードを追加した場合は、次の設定タスクを実行します。
+
[cols="2a,1a"]
|===
| 管理ノードの設定タスク | を参照してください 


 a| 
StorageGRID システムでシングルサインオンが有効になっている場合は、Active Directory Federation Services（AD FS；Active Directoryフェデレーションサービス）で新しい管理ノードの証明書利用者信頼を作成する必要があります。この証明書利用者信頼を作成するまで、ノードにサインインすることはできません。
 a| 
link:../admin/configuring-sso.html["シングルサインオンを設定しています"]



 a| 
管理ノードでロードバランササービスを使用する場合は、ハイアベイラビリティグループに管理ノードを追加しなければならないことがあります。既存のHAグループのリストを確認して新しいノードを追加するには、* Configuration *>* Network Settings *>* High Availability Groups *を選択します。
 a| 
link:../admin/index.html["StorageGRID の管理"]



 a| 
必要に応じて、管理ノードデータベースをプライマリ管理ノードから拡張管理ノードにコピーします。これは、各管理ノードで属性と監査の情報の整合性を維持する場合に行います。
 a| 
link:copying-admin-node-database.html["管理ノードデータベースをコピーしています"]



 a| 
必要に応じて、 Prometheus データベースをプライマリ管理ノードから拡張管理ノードにコピーします。これは、各管理ノードで指標の履歴の整合性を維持する場合に行います。
 a| 
link:copying-prometheus-metrics.html["Prometheus指標のコピー"]



 a| 
必要に応じて、既存の監査ログをプライマリ管理ノードから拡張管理ノードにコピーします。これは、各管理ノードでログの履歴情報の整合性を維持する場合に行います。
 a| 
link:copying-audit-logs.html["監査ログをコピーしています"]



 a| 
必要に応じて、 NFS または CIFS ファイル共有を通じて、監査を目的としたシステムへのアクセスを設定します。

*注意：CIFS / Sambaによる監査エクスポートは廃止されており、今後のStorageGRID リリースで削除される予定です。
 a| 
link:../admin/index.html["StorageGRID の管理"]



 a| 
必要に応じて、通知の優先送信者を変更します。拡張管理ノードを優先送信者にすることができます。設定を更新しない場合は、優先送信者として設定された既存の管理ノードから引き続き、 AutoSupport メッセージ、 SNMP 通知、アラート E メール、アラーム E メール（従来のシステム）などの通知が送信されます。
 a| 
link:../admin/index.html["StorageGRID の管理"]

|===
. アーカイブノードを追加した場合は、次の設定タスクを実行します。
+
[cols="2a,1a"]
|===
| アーカイブノードの設定タスク | を参照してください 


 a| 
アーカイブノードからターゲットの外部アーカイブストレージシステムへの接続を設定します。拡張が完了すると、 * ARC * > * Target * コンポーネントを通じて接続情報を設定するまで、アーカイブノードはアラーム状態になります。
 a| 
link:../admin/index.html["StorageGRID の管理"]



 a| 
新しいアーカイブノードを介してオブジェクトデータをアーカイブするように ILM ポリシーを更新します。
 a| 
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]



 a| 
アーカイブノードからオブジェクトデータを読み出す速度と効率を監視する属性に対してカスタムアラームを設定します。
 a| 
link:../admin/index.html["StorageGRID の管理"]

|===
. 拡張ノードが信頼されていないクライアントネットワークで追加されたかどうかを確認する方法、またはノードのクライアントネットワークが信頼されていないかどうかを変更する方法については、* Configuration *>* Network Settings *>* Untrusted Client Network *を参照してください。
+
拡張ノードのクライアントネットワークが信頼されていない場合は、ロードバランサエンドポイントを使用してクライアントネットワークのノードへの接続を確立する必要があります。詳細については、 StorageGRID の管理手順を参照してください。

. Domain Name System （ DNS ；ドメインネームシステム）を設定します。
+
DNS 設定をグリッドノードごとに個別に指定していた場合は、新しいノード用のノード単位のカスタム DNS 設定を追加する必要があります。リカバリおよびメンテナンスの手順で、単一グリッドノードのDNS設定の変更に関する情報を参照してください。

+
各サイトからローカルでアクセスできる DNS サーバをグリッド全体の DNS サーバリストにいくつか含めることを推奨します。新しいサイトを追加した場合は、そのサイト用の新しい DNS サーバをグリッド全体の DNS 設定に追加します。

+

IMPORTANT: DNS サーバの IPv4 アドレスは 2~6 個指定します。ネットワーク分離が発生した場合に各サイトがローカルにアクセスできる DNS サーバを選択する必要があります。これにより、分離されたサイトは引き続き DNS サービスにアクセスできます。グリッド全体の DNS サーバリストを設定したあとに、ノードごとに DNS サーバリストをカスタマイズできます。詳細については、リカバリおよびメンテナンスの手順にある DNS 設定の変更に関する情報を参照してください。

. 新しいサイトを追加した場合は、そのサイトから Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバにアクセスできることを確認します。
+

IMPORTANT: 各サイトの少なくとも 2 つのノードが、少なくとも 4 つの外部 NTP ソースにアクセスできることを確認します。NTP ソースにアクセスできるノードがサイトに 1 つしかないと、そのノードがダウンした場合にタイミングの問題が生じます。また、各サイトで 2 つのノードをプライマリ NTP ソースとして指定することにより、サイトがグリッドの他の部分から分離されても、正確なタイミングが保証されます。

+
詳細については、リカバリとメンテナンスの手順を参照してください。



.関連情報
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

link:verifying-storage-node-is-active.html["ストレージノードがアクティブであることを確認しています"]

link:copying-admin-node-database.html["管理ノードデータベースをコピーしています"]

link:copying-prometheus-metrics.html["Prometheus指標のコピー"]

link:copying-audit-logs.html["監査ログをコピーしています"]

link:../upgrade/index.html["ソフトウェアをアップグレードする"]

link:../maintain/index.html[""]
