---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。以前にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りのStorageGRID システムと同期されるようにすることができます。 
---
= 監査ログをコピーしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。以前にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りのStorageGRID システムと同期されるようにすることができます。

.必要なもの
* 管理ノードを追加する拡張手順が完了している必要があります。
* を用意しておく必要があります `Passwords.txt` ファイル。


.このタスクについて
他の管理ノードの監査メッセージの履歴を拡張管理ノードで使用できるようにするには、プライマリ管理ノードまたは別の既存の管理ノードから拡張管理ノードに手動で監査ログファイルをコピーする必要があります。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh _admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. AMSサービスを停止して新しいファイルが作成されないようにします。 `service ams stop`
. の名前を変更します `audit.log` fileを指定します。これにより、拡張管理ノードにコピーしたファイルが上書きされません。
+
`cd /var/local/audit/export` [+]
`ls -l` [+]
`mv audit.log _new_name_.txt`

. すべての監査ログファイルを拡張管理ノードにコピーします。
+
`scp -p * _IP_address_:/var/local/audit/export`

. プロンプトが表示されたら、のパスフレーズを入力します `/root/.ssh/id_rsa`で、に表示されているプライマリ管理ノードのSSHアクセスパスワードを入力します `Passwords.txt` ファイル。
. 元のを復元します `audit.log` ファイル：
+
`mv _new_name_.txt audit.log`

. AMS サービスを開始します。
+
`service ams start`

. サーバからログアウトします。
+
`exit`

. 拡張管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_expansion_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 監査ログファイルのユーザとグループの設定を更新します。
+
`cd /var/local/audit/export` [+]
`chown ams-user:bycast *`

. サーバからログアウトします。
+
`exit`


