---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines 
summary: StorageGRID システムのオブジェクトストレージ容量を拡張するには、既存のストレージノードにストレージボリュームを追加するか、または既存のサイトに新しいストレージノードを追加します。情報ライフサイクル管理（ ILM ）ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。 
---
= オブジェクト容量を追加する場合のガイドラインを次に示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムのオブジェクトストレージ容量を拡張するには、既存のストレージノードにストレージボリュームを追加するか、または既存のサイトに新しいストレージノードを追加します。情報ライフサイクル管理（ ILM ）ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。



== ストレージボリュームの追加に関するガイドラインを次に示します

既存のストレージノードにストレージボリュームを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在の ILM ルールを調べて、ストレージボリュームを追加してレプリケートオブジェクトまたはイレイジャーコーディングオブジェクトに使用できるストレージを増やす場所とタイミングを決定する必要があります。情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照してください。
* オブジェクトメタデータはボリューム 0 にしか格納されないため、ストレージボリュームを追加してシステムのメタデータ容量を増やすことはできません。
* 各ソフトウェアベースのストレージノードでサポートされるストレージボリュームは最大 16 個です。それよりも多くの容量が必要な場合は、新しいストレージノードを追加する必要があります。
* 各 SG6060 アプライアンスには、 1 台または 2 台の拡張シェルフを追加できます。各拡張シェルフには、 16 個のストレージボリュームが追加されます。両方の拡張シェルフを設置した場合、 SG6060 では合計 48 個のストレージボリュームをサポートできます。
* ストレージボリュームを他のストレージアプライアンスに追加することはできません。
* 既存のストレージボリュームのサイズを拡張することはできません。
* ストレージノードへのストレージボリュームの追加は、システムのアップグレードやリカバリの処理や他の拡張と同時に実行することはできません。


ストレージボリュームを追加することにし、 ILM ポリシーを満たすために拡張する必要があるストレージノードを決めたら、該当するタイプのストレージノードの手順に従います。

* 拡張シェルフをSG6060ストレージアプライアンスに追加するには、SG6000アプライアンスの設置およびメンテナンス手順を参照してください。
+
link:../sg6000/index.html["SG6000 ストレージアプライアンス"]

* ソフトウェアベースのノードの場合は、ストレージノードにストレージボリュームを追加する手順に従います。
+
link:adding-storage-volumes-to-storage-nodes.html["ストレージノードへのストレージボリュームの追加"]





== ストレージノードの追加に関するガイドラインを次に示します

既存のサイトにストレージノードを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在の ILM ルールを調べて、ストレージノードを追加してレプリケートオブジェクトまたはイレイジャーコーディングオブジェクトに使用できるストレージを増やす場所とタイミングを決定する必要があります。
* 1 つの拡張手順 に追加できるストレージノードは 10 個までです。
* 単一の拡張手順 で複数のサイトにストレージノードを追加することができます。
* 1 つの拡張手順 で、ストレージノードとその他のタイプのノードを追加できます。
* 拡張手順 を開始する前に、リカバリの一環として実行されるデータ修復処理がすべて完了したことを確認する必要があります。リカバリとメンテナンスの手順のデータ修復ジョブを確認する手順を参照してください。
* 拡張の実行前または実行後にストレージノードを削除する必要がある場合は、 1 つの運用停止ノード手順 の 10 個を超えるストレージノードの運用を停止しないでください。




== ストレージノード上のADCサービスについてのガイドラインを参照してください

拡張を設定する場合は、新しい各ストレージノードに Administrative Domain Controller （ ADC ）サービスを含めるかどうかを選択する必要があります。ADC サービスは、グリッドサービスの場所と可用性を追跡します。

* StorageGRID システムでは、各サイトで ADC サービスのクォーラムが常に利用可能である必要があります。
+

NOTE: リカバリとメンテナンスの手順のADCクォーラムに関する情報を参照してください。

* 各サイトで少なくとも 3 つのストレージノードに ADC サービスが含まれている必要があります。
* すべてのストレージノードに ADC サービスを追加することは推奨されません。ノード間の通信量が増加しているため、 ADC サービスが多すぎると原因 の速度が低下する可能性があります。
* 1 つのグリッドに ADC サービスがあるストレージノードが 48 個を超えないようにします。各サイトに ADC サービスが 3 つある 16 のサイトに相当します。
* 一般に、新しいノードの * ADC Service * 設定を選択する場合は、 * Automatic * を選択してください。ADC サービスを含む別のストレージノードを新しいノードで置き換える場合にのみ、「 * Yes 」を選択します。残りの ADC サービスの数が少なすぎるとストレージノードの運用を停止できないため、古いサービスが削除される前に新しい ADC サービスが利用可能になります。
* 導入後のノードに ADC サービスを追加することはできません。


* 関連情報 *

link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

link:../sg6000/index.html["SG6000 ストレージアプライアンス"]

link:adding-storage-volumes-to-storage-nodes.html["ストレージノードへのストレージボリュームの追加"]

link:../maintain/index.html[""]

link:performing-expansion.html["拡張の実施"]
