---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 場合によっては、新しいストレージノードを追加したあとにイレイジャーコーディングデータのリバランシングが必要になることがあります。 
---
= ストレージノードの追加後におけるイレイジャーコーディングデータのリバランシング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
場合によっては、新しいストレージノードを追加したあとにイレイジャーコーディングデータのリバランシングが必要になることがあります。

.必要なもの
* 新しいストレージノードを追加する拡張手順が完了している必要があります。
* イレイジャーコーディングデータのリバランシングに関する考慮事項を確認しておく必要があります。
+
link:considerations-for-rebalancing-erasure-coded-data.html["イレイジャーコーディングデータのリバランシングに関する考慮事項"]

+

IMPORTANT: この手順 は、サイトの 1 つ以上のストレージノードに対して * Low Object Storage * アラートがトリガーされ、推奨数の新しいストレージノードを追加できなかった場合にのみ実行してください。

* を用意しておく必要があります `Passwords.txt` ファイル。


.このタスクについて
EC のリバランシング手順 が実行されている場合、 ILM 処理と S3 および Swift クライアント処理のパフォーマンスに影響する可能性があります。そのため、この手順 は限られた場合にのみ実行してください。


NOTE: EC のリバランシングによって、手順 が一時的に大量のストレージをリザーブします。ストレージアラートがトリガーされる場合がありますが、リバランシングが完了すると解決します。予約に十分なストレージがない場合、 EC のリバランシング手順 は失敗します。ストレージ予約は、手順 が失敗したか成功したかに関係なく、 EC のリバランシング手順 が完了したときに解放されます。

[NOTE]
====
オブジェクト（またはオブジェクトパーツ）をアップロードするために S3 および Swift API 処理を実行すると、 EC のリバランシング中に 24 時間以上かかる場合に手順 のリバランシングが失敗することがあります。該当する ILM ルールの取り込みに Strict または Balanced 配置が使用されている場合、長時間の PUT 処理は失敗します。次のエラーが報告されます。

`500 Internal Server Error`

====
.手順
. [[review_object_storage] ] リバランシングするサイトの現在のオブジェクトストレージの詳細を確認します。
+
.. [*ノード（* Nodes）]を選択し
.. サイトで最初のストレージノードを選択します。
.. [ * ストレージ * ] タブを選択します。
.. Storage Used - Object Data チャートにカーソルを合わせて、ストレージノード上のレプリケートデータとイレイジャーコーディングデータの現在の量を表示します。
.. 同じ手順を繰り返して、サイトの他のストレージノードを表示します。


. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 次のコマンドを入力します。
+
`rebalance-data start --site "_site-name_"`

+
の場合 `"_site-name_"`をクリックし、新しいストレージノードを追加した最初のサイトを指定します。囲みます `site-name` 引用符で囲みます。

+
EC Rebalance 手順 が開始され、ジョブ ID が返されます。

. ジョブ ID をコピーします。
. EC Rebalance 手順 のステータスを監視します。
+
** 単一の EC Rebalance 手順 のステータスを表示するには、次の手順を実行します
+
`rebalance-data status --job-id _job-id_`

+
の場合 `_job-id_`で、手順 の起動時に返されたIDを指定します。

** 現在の EC Rebalance 手順 と、以前に完了した手順のステータスを表示するには、次の手順を実行します。
+
`rebalance-data status`

+
[NOTE]
====
rebalance -dataコマンド のヘルプを表示するには、次の手順を実行します。

`rebalance-data --help`

====


. 返されたステータスに基づいて、追加の手順を実行します。
+
** ステータスがの場合 `In progress`を実行している場合、ECのリバランシング処理はまだ実行中です。手順 は、完了するまで定期的に監視する必要があります。
** ステータスがの場合 `Failure`をクリックし、を実行します <<rebalance_fail,失敗の手順>>。
** ステータスがの場合 `Success`をクリックし、を実行します <<rebalance_succeed,成功のステップ>>。


. EC Rebalance 手順 によって大量の負荷が生成されている（取り込み処理に影響があるなど）場合は、手順 を一時停止します。
+
`rebalance-data pause --job-id _job-id_`

. EC のリバランシング手順 を終了する必要がある場合（ StorageGRID ソフトウェアのアップグレードを実行できるようにする場合など）は、次のように入力します。
+
`rebalance-data abort --job-id _job-id_`

+

NOTE: EC のリバランシング手順 を終了すると、移動済みのデータフラグメントは新しい場所に残ります。データは元の場所に戻されません。

. [[rebalance _fail]] EC rebalance手順 のステータスがの場合 `Failure`、次の手順を実行します。
+
.. サイトのすべてのストレージノードがグリッドに接続されていることを確認します。
.. これらのストレージノードに影響している可能性があるアラートがないかどうかを確認し、解決してください。
+
特定のアラートの詳細については、監視とトラブルシューティングの手順を参照してください。

.. EC Rebalance手順 ：+を再起動します
`rebalance-data start –-job-id _job-id_`
.. ECのリバランシング手順 のステータスがまだの場合 `Failure`、テクニカルサポートにお問い合わせください。


. [rebalance _succeed ]] EC Rebalance手順 のステータスがの場合 `Success`必要に応じて <<review_object_storage,オブジェクトストレージを確認する>> をクリックすると、サイトの最新の詳細が表示されます。
+
イレイジャーコーディングされたデータをサイトのストレージノード間でより均等に配置します。

+

NOTE: レプリケートされたオブジェクトデータは、EC Rebalance手順 によって移動されません。

. 複数のサイトでイレイジャーコーディングを使用している場合は、影響を受ける他のすべてのサイトに対してこの手順 を実行します。


.関連情報
link:considerations-for-rebalancing-erasure-coded-data.html["イレイジャーコーディングデータのリバランシングに関する考慮事項"]

link:../monitor/index.html["トラブルシューティングを監視します"]
