---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords:  
summary: Lost Objects （ LOST ）アラームと * Object lost * アラートをトリガーした（失われた可能性があると特定した）オブジェクトを検索してリストアできる場合があります。 
---
= 失われた可能性があるオブジェクトの検索とリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lost Objects （ LOST ）アラームと * Object lost * アラートをトリガーした（失われた可能性があると特定した）オブジェクトを検索してリストアできる場合があります。

.必要なもの
* 「損失オブジェクトの調査」で特定した損失オブジェクトの UUID が必要です。
* を用意しておく必要があります `Passwords.txt` ファイル。


.このタスクについて
この手順 を使用して、グリッド内の他の場所で損失オブジェクトのレプリケートコピーを検索できます。ほとんどの場合、損失オブジェクトは見つかりません。ただし、迅速に対処すれば、損失レプリケートオブジェクトを検索してリストアできる場合があります。


IMPORTANT: この手順 のサポートについては、テクニカルサポートにお問い合わせください。

.手順
. 管理ノードの監査ログで、オブジェクトが存在する可能性のある場所を検索します。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@grid_node_IP`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。


.. 監査ログが格納されているディレクトリに移動します。 `cd /var/local/audit/export/`
.. grep を使用して、失われた可能性があるオブジェクトに関連付けられている監査メッセージを抽出し、出力ファイルに送信します。入力するコマンド `grep uuid-valueaudit_file_name > output_file_name`
+
例：

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > messages_about_lost_object.txt
----
.. grep を使用して、この出力ファイルから Location Lost （ LLST ）監査メッセージを抽出します。入力するコマンド `grep LLST output_file_name`
+
例：

+
[listing]
----
Admin: # grep LLST messages_about_lost_objects.txt
----
+
LLST 監査メッセージは次のサンプルメッセージのようになります。

+
[listing]
----
[AUDT:\[NOID\(UI32\):12448208\][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD\(CSTR\):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%\#3tN6"\]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):
1581535134379225][ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM]
[ATID(UI64):7086871083190743409]]
----
.. LLST メッセージで PCLD フィールドと NOID フィールドを検索します。
+
PCLD の値は、欠落しているレプリケートオブジェクトコピーへのディスク上の完全なパスです。NOID の値は、オブジェクトのコピーが存在する可能性のある LDR のノード ID です。

+
オブジェクトの場所が見つかった場合は、オブジェクトをリストアできる場合があります。

.. この LDR ノード ID のストレージノードを探します。
+
ノード ID を使用してストレージノードを特定する方法は 2 つあります。

+
*** Grid Managerで、* Support *>* Tools *>* Grid Topology *を選択します。次に、「 * _ データセンター _ * > * _ ストレージノード _ * > * LDR * 」を選択します。LDR ノード ID は Node Information テーブルに含まれています。この LDR をホストしているストレージノードが見つかるまで、各ストレージノードの情報を確認します。
*** グリッドのリカバリパッケージをダウンロードして解凍します。SAID パッケージには _\docs_directory があります。index.html ファイルを開くと、 Servers Summary には、すべてのグリッドノードのすべてのノード ID が表示されます。




. 監査メッセージで指定されているストレージノードにオブジェクトが存在するかどうかを確認します。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@grid_node_IP`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. オブジェクトのファイルパスが存在するかどうかを確認します。
+
オブジェクトのファイルパスには、 LLST 監査メッセージの PCLD の値を使用します。

+
たとえば、次のように入力します。

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
* 注 * ：オブジェクトファイルのパスは、特殊文字をエスケープするために、必ず一重引用符で囲んでください。

+
*** オブジェクトパスが見つからない場合はオブジェクトが失われるため、この手順 を使用してリストアすることはできません。テクニカルサポートにお問い合わせください。
*** オブジェクトパスが見つかった場合は、手順に進みます <<restore_the_object_to_StorageGRID,オブジェクトを StorageGRID にリストアします>>。見つかったオブジェクトを StorageGRID にリストアできます。






[[restore_the_object_to_StorageGRID]]
. オブジェクトパスが見つかった場合は、オブジェクトをStorageGRID にリストアします。
+
.. 同じストレージノードから、オブジェクトファイルの所有権を変更して StorageGRID で管理できるようにします。入力するコマンド `chown ldr-user:bycast 'file_path_of_object'`
.. Telnet で localhost 1402 に接続して、 LDR コンソールにアクセスします。入力するコマンド `telnet 0 1402`
.. 入力するコマンド `cd /proc/STOR`
.. 入力するコマンド `Object_Found 'file_path_of_object'`
+
たとえば、次のように入力します。

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
を発行します `Object\_Found` コマンドは、グリッドにオブジェクトの場所を通知します。また、アクティブな ILM ポリシーがトリガーされ、ポリシーの指定に従って追加のコピーが作成されます。



+
* 注：オブジェクトが見つかったストレージノードがオフラインの場合は、オンラインの任意のストレージノードにオブジェクトをコピーできます。オンラインのストレージノードの /var/local/rangedb ディレクトリにオブジェクトを配置します。次に、問題 を実行します `Object\_Found` コマンドを使用し、オブジェクトへのファイルパスを指定します。

+
** オブジェクトをリストアできない場合は、を参照してください `Object\_Found` コマンドが失敗します。テクニカルサポートにお問い合わせください。
** オブジェクトが StorageGRID に正常にリストアされた場合は、成功を伝えるメッセージが表示されます。例：
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
手順に進みます <<verify_that_new_locations_were_created,新しい場所が作成されたことを確認します>>





[[verify_that_new_locations_were_created]]
. オブジェクトがStorageGRID に正常にリストアされた場合は、新しい場所が作成されていることを確認します。
+
.. 入力するコマンド `cd /proc/OBRP`
.. 入力するコマンド `ObjectByUUID UUID_value`
+
次の例は、 UUID 926026C4-00A4-449B-AC72-BCCA72DD1311 のオブジェクトに 2 つの場所があることを示しています。

+
[listing]
----
ade 12448208: /proc/OBRP > ObjectByUUID 926026C4-00A4-449B-AC72-BCCA72DD1311

{
    "TYPE(Object Type)": "Data object",
    "CHND(Content handle)": "926026C4-00A4-449B-AC72-BCCA72DD1311",
    "NAME": "cats",
    "CBID": "0x38186FE53E3C49A5",
    "PHND(Parent handle, UUID)": "221CABD0-4D9D-11EA-89C3-ACBB00BB82DD",
    "PPTH(Parent path)": "source",
    "META": {
        "BASE(Protocol metadata)": {
            "PAWS(S3 protocol version)": "2",
            "ACCT(S3 account ID)": "44084621669730638018",
            "*ctp(HTTP content MIME type)": "binary/octet-stream"
        },
        "BYCB(System metadata)": {
            "CSIZ(Plaintext object size)": "5242880",
            "SHSH(Supplementary Plaintext hash)": "MD5D 0xBAC2A2617C1DFF7E959A76731E6EAF5E",
            "BSIZ(Content block size)": "5252084",
            "CVER(Content block version)": "196612",
            "CTME(Object store begin timestamp)": "2020-02-12T19:16:10.983000",
            "MTME(Object store modified timestamp)": "2020-02-12T19:16:10.983000",
            "ITME": "1581534970983000"
        },
        "CMSM": {
            "LATM(Object last access time)": "2020-02-12T19:16:10.983000"
        },
        "AWS3": {
            "LOCC": "us-east-1"
        }
    },
    "CLCO\(Locations\)": \[
        \{
            "Location Type": "CLDI\(Location online\)",
            "NOID\(Node ID\)": "12448208",
            "VOLI\(Volume ID\)": "3222345473",
            "Object File Path": "/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila\#3udu",
            "LTIM\(Location timestamp\)": "2020-02-12T19:36:17.880569"
        \},
        \{
            "Location Type": "CLDI\(Location online\)",
            "NOID\(Node ID\)": "12288733",
            "VOLI\(Volume ID\)": "3222345984",
            "Object File Path": "/var/local/rangedb/0/p/19/11/00rH0%DkRt78Rrb\#3s;L",
            "LTIM\(Location timestamp\)": "2020-02-12T19:36:17.934425"
        }
    ]
}
----
.. LDR コンソールからサインアウトします。入力するコマンド `exit`


. 管理ノードから、監査ログを検索してこのオブジェクトを ORLM 監査メッセージで探し、必要に応じて情報ライフサイクル管理（ ILM ）によってコピーが配置されていることを確認します。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@grid_node_IP`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。


.. 監査ログが格納されているディレクトリに移動します。 `cd /var/local/audit/export/`
.. grep を使用して、オブジェクトに関連付けられている監査メッセージを出力ファイルに抽出します。入力するコマンド `grep uuid-valueaudit_file_name > output_file_name`
+
例：

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > messages_about_restored_object.txt
----
.. grep を使用して、この出力ファイルから Object Rules Met （ ORLM ）監査メッセージを抽出します。入力するコマンド `grep ORLM output_file_name`
+
例：

+
[listing]
----
Admin: # grep ORLM messages_about_restored_object.txt
----
+
以下は、 ORLM 監査メッセージの例です。

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. 監査メッセージで LOCS フィールドを検索します。
+
このフィールドの CLDI の値は、オブジェクトコピーが作成されたノード ID とボリューム ID です。このメッセージは、 ILM が適用され、 2 つのオブジェクトコピーがグリッド内の 2 つの場所に作成されたことを示しています。

.. Grid Manager で損失オブジェクトの数をリセットします。




.関連情報
link:troubleshooting-storagegrid-system.html["損失オブジェクトを調査しています"]

link:troubleshooting-storagegrid-system.html["オブジェクトデータの場所を確認する"]

link:troubleshooting-storagegrid-system.html["損失オブジェクトと欠落オブジェクトのカウントのリセット"]

link:../audit/index.html["監査ログを確認します"]
