---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords:  
summary: オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。 
---
= オブジェクトデータの損失と欠落が発生した場合のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。

StorageGRID システムは、オブジェクトのメタデータに記載された場所の情報を使用して、オブジェクトの読み出し元の場所を特定します。想定される場所でオブジェクトのコピーが見つからない場合、システムは ILM ポリシーにオブジェクトのコピーを複数保持するルールが含まれているものとして、システム内の他の場所から別のコピーを読み出そうとします。

この読み出しに成功すると、欠落しているオブジェクトのコピーが StorageGRID システムによって置き換えられます。そうしないと、* Objects lost *アラートとレガシーLOST（Lost Objects）アラームが次のようにトリガーされます。

* レプリケートコピーについては、別のコピーを読み出せない場合、オブジェクトが失われたとみなされ、アラートとアラームがトリガーされます。
* イレイジャーコーディングされたコピーについては、想定される場所からコピーを読み出せない場合、他の場所からの読み出しが試行される前に「 Corrupt Copies Detected （ ECOR ）」属性の値が 1 つ増分されます。他のコピーが見つからないと、アラートとアラームがトリガーされます。


すべての * Objects Lost * アラートをすぐに調査して損失のルート原因 を特定し、オフラインなどの何らかの理由で現在使用できないストレージノードやアーカイブノードにオブジェクトが残っていないかどうかを確認する必要があります。

コピーがないオブジェクトデータが失われた場合、リカバリ解決策 はありません。ただし、既知の損失オブジェクトが新しい損失オブジェクトをマスキングしないように、Lost Objectカウンタをリセットする必要があります。

.関連情報
link:troubleshooting-storagegrid-system.html["損失オブジェクトを調査しています"]

link:troubleshooting-storagegrid-system.html["損失オブジェクトと欠落オブジェクトのカウントのリセット"]
