---
permalink: ilm/comparing-s3-object-lock-to-legacy-compliance.html 
sidebar: sidebar 
keywords:  
summary:  
---
= S3 オブジェクトロックと従来の準拠の比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5のS3オブジェクトロック機能は、以前のバージョンのStorageGRID で使用できた準拠機能に代わる機能です。新しいS3オブジェクトロック機能はAmazon S3の要件に準拠しているため、「従来のコンプライアンス」と呼ばれる独自のStorageGRID 準拠機能は廃止されています。

グローバル準拠設定を有効にしている場合は、StorageGRID 11.5にアップグレードすると、新しいグローバルS3オブジェクトロック設定が自動的に有効になります。テナントユーザは、StorageGRID 11.5で準拠を有効にした新しいバケットを作成できなくなります。ただし、必要に応じて、テナントユーザは既存の従来の準拠バケットを引き続き使用および管理できます。これには次のタスクの実行が含まれます。

* 従来の準拠が有効になっている既存のバケットに新しいオブジェクトを取り込む。
* 従来の準拠が有効になっている既存のバケットの保持期間を延長する。
* 従来の準拠が有効になっている既存のバケットの自動削除設定を変更する。
* 従来の準拠が有効になっている既存のバケットにリーガルホールドを適用する。
* リーガルホールドを解除する。


https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["ネットアップのナレッジベース： StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^]

以前のバージョンの StorageGRID で従来の準拠機能を使用していた場合、次の表を参照して、 StorageGRID の S3 オブジェクトロック機能と比較する方法を確認してください。

[cols="1a,1a,1a"]
|===
|  | S3 オブジェクトロック（新規） | コンプライアンス（レガシー） 


 a| 
この機能はグローバルにどのように有効になりますか。
 a| 
Grid Managerから* Configuration *>* System Settings *>* S3 Object Lock *を選択します。
 a| 
サポートは終了しました。

*注：グローバル準拠設定を有効にしている場合、StorageGRID 11.5にアップグレードすると、グローバルなS3オブジェクトロック設定が自動的に有効になります。



 a| 
バケットで機能を有効にするにはどうすればよいですか？
 a| 
Tenant Manager 、テナント管理 API 、または S3 REST API を使用して新しいバケットを作成するときは、 S3 オブジェクトロックを有効にする必要があります。
 a| 
準拠を有効にした新しいバケットを作成することはできなくなりました。ただし、既存の準拠バケットには引き続き新しいオブジェクトを追加できます。



 a| 
バケットのバージョン管理はサポートされているか
 a| 
はい。バケットのバージョン管理は必須であり、バケットで S3 オブジェクトのロックが有効になっている場合は自動的に有効になります。
 a| 
いいえ従来の準拠機能では、バケットのバージョン管理は許可されていません。



 a| 
オブジェクト保持はどのように設定されますか。
 a| 
ユーザーは、オブジェクトバージョンごとに retain-until date を設定できます。
 a| 
ユーザはバケット全体の保持期間を設定する必要があります。保持期間を指定すると、バケット内のすべてのオブジェクトが環境 で保持されます。



 a| 
バケットには保持とリーガルホールドのデフォルト設定を適用できるか。
 a| 
いいえS3オブジェクトのロックが有効になっているStorageGRID バケットでは、デフォルトの保持期間は使用されません。代わりに、オブジェクトバージョンごとにretain-dateを指定できます。
 a| 
はい。



 a| 
保持期間は変更できますか。
 a| 
オブジェクトバージョンの retain-until は、上げることはできますが、減らすことはできません。
 a| 
バケットの保持期間は、増やすことはできますが、減らすことはできません。



 a| 
リーガルホールドはどこで制御されますか？
 a| 
バケット内のオブジェクトバージョンにリーガルホールドを適用したり、リーガルホールドを解除したりできます。
 a| 
リーガルホールドはバケットに適用され、バケット内のすべてのオブジェクトに適用されます。



 a| 
オブジェクトを削除できるのはいつですか。
 a| 
オブジェクトがリーガルホールドの対象でない場合は、 retain-until 日に達したあとでオブジェクトバージョンを削除できます。
 a| 
バケットがリーガルホールドの対象でない場合は、保持期間が過ぎたあとにオブジェクトを削除できます。オブジェクトは自動または手動で削除できます。



 a| 
バケットライフサイクル設定はサポートされていますか。
 a| 
はい。
 a| 
いいえ

|===