---
permalink: fabricpool/best-practices-for-load-balancing.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, Layer 7, cloud tier, best practices 
summary: StorageGRID をFabricPool クラウド階層として接続する前に、StorageGRID グリッドマネージャを使用して少なくとも1つのロードバランサエンドポイントを設定します。 
---
= ロードバランシングのベストプラクティスを参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID をFabricPool クラウド階層として接続する前に、StorageGRID グリッドマネージャを使用して少なくとも1つのロードバランサエンドポイントを設定します。



== ロードバランシングとは

データを FabricPool から StorageGRID システムに階層化すると、 StorageGRID はロードバランサを使用して取り込みと読み出しのワークロードを管理します。ロードバランシングは、 FabricPool ワークロードを複数のストレージノードに分散することで、速度と接続容量を最大化します。

StorageGRID ロードバランササービスはすべての管理ノードとすべてのゲートウェイノードにインストールされ、レイヤ 7 のロードバランシングを提供します。クライアント要求の Transport Layer Security （ TLS ）終了を実行し、要求を検査し、ストレージノードへの新しいセキュアな接続を確立します。

各ノード上のロードバランササービスは、クライアントトラフィックをストレージノードに転送する際に独立して動作します。重み付きのプロセスを使用すると、ロードバランササービスは、より多くの要求をより多くの CPU を使用可能なストレージノードにルーティングします。

推奨されるロードバランシングメカニズムは StorageGRID ロードバランササービスですが、代わりにサードパーティのロードバランサを統合することもできます。詳細については、ネットアップのアカウント担当者にお問い合わせいただくか、次のテクニカルレポートを参照してください。

https://["StorageGRID ロードバランサオプション"^]


NOTE: ゲートウェイノード上の別の Connection Load Balancer （ CLB ）サービスは廃止され、 FabricPool での使用は推奨されなくなりました。



== StorageGRID ロードバランシングのベストプラクティスを参照してください

一般的なベストプラクティスとして、 StorageGRID システムの各サイトにロードバランササービスを使用するノードが 2 つ以上必要です。たとえば、サイトには管理ノードとゲートウェイノードの両方、または管理ノードが2つ含まれている場合があります。SG100 または SG100 サービスアプライアンス、ベアメタルノード、仮想マシン（ VM ）ベースのノードのいずれを使用しているかに関係なく、各ロードバランシングノードに適切なネットワーク、ハードウェア、または仮想化インフラがあることを確認します。

StorageGRID ロードバランサエンドポイントを設定して、ゲートウェイノードと管理ノードが FabricPool の受信要求と送信要求に使用するポートを定義する必要があります。



== ロードバランサエンドポイント証明書のベストプラクティス

FabricPool で使用するロードバランサエンドポイントを作成する際には、プロトコルとしてHTTPSを使用する必要があります。その後、公開された信頼された証明書またはプライベート認証局（CA）によって署名された証明書をアップロードするか、自己署名証明書を生成できます。この証明書は、 ONTAP が StorageGRID で認証することを許可します。

ベストプラクティスとして、 CA サーバ証明書を使用して接続を保護することを推奨します。CA によって署名された証明書は、無停止でローテーションできます。

ロードバランサエンドポイントで使用する CA 証明書を要求する場合は、証明書のドメイン名が、そのロードバランサエンドポイント用に ONTAP に入力するサーバ名と一致していることを確認してください。可能であれば、ワイルドカード（ * ）を使用して仮想ホスト形式の URL を許可します。例：

[listing]
----
*.s3.storagegrid.company.com
----
StorageGRID を FabricPool クラウド階層として追加する場合は、 ONTAP クラスタにも同じ証明書をインストールする必要があります。また、ルート証明書と下位の認証局（ CA ）証明書もインストールする必要があります。


NOTE: StorageGRID では、さまざまな目的でサーバ証明書が使用されます。ロードバランササービスに接続する場合は、Object Storage APIサービスエンドポイントのサーバ証明書をアップロードする必要はありません。

ロードバランシングエンドポイントのサーバ証明書の詳細を確認するには、次の手順を実行します。

* link:../admin/managing-load-balancing.html["負荷分散の管理"]
* link:../harden/hardening-guideline-for-server-certificates.html["サーバ証明書のセキュリティ強化ガイドライン"]

