---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: StorageGRID をFabricPool クラウド階層として接続する前に、StorageGRID グリッドマネージャを使用してハイアベイラビリティ（HA\）グループを設定します。 
---
= ハイアベイラビリティグループのベストプラクティス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID をFabricPool クラウド階層として接続する前に、StorageGRID グリッドマネージャを使用してハイアベイラビリティ（HA）グループを設定します。



== ハイアベイラビリティ（HA）グループとは

FabricPool データの管理に常にロードバランササービスを使用できるようにするには、複数の管理ノードとゲートウェイノードのネットワークインターフェイスを 1 つのエンティティ（ハイアベイラビリティ（ HA ）グループと呼ばれます）にグループ化します。HA グループのアクティブノードで障害が発生した場合、グループ内の別のノードがワークロードの管理を続行できます。

各 HA グループは、関連付けられたノード上の共有サービスへの可用性の高いアクセスを提供します。たとえば、すべての管理ノードで構成されるHAグループは、一部の管理ノード管理サービスとロードバランササービスへの高可用性アクセスを提供します。ゲートウェイノードのみ、または管理ノードとゲートウェイノードの両方で構成されるHAグループは、共有ロードバランササービスへの可用性の高いアクセスを提供します。

HAグループを作成するときは、グリッドネットワーク（eth0）またはクライアントネットワーク（eth2）に属するネットワークインターフェイスを選択します。HAグループ内のすべてのインターフェイスは、同じネットワークサブネット内に存在する必要があります。

HAグループは、グループ内のアクティブインターフェイスに追加された仮想IPアドレスを1つ以上維持します。アクティブインターフェイスが使用できなくなった場合、仮想IPアドレスは別のインターフェイスに移動します。このフェイルオーバープロセスにかかる時間は通常数秒です。クライアントアプリケーションへの影響はほとんどなく、通常の再試行で処理を続行できます。

ロードバランシングノードのHAグループを設定すると、FabricPool はそのHAグループの仮想IPアドレスに接続します。



== ハイアベイラビリティ（ HA ）グループのベストプラクティス

FabricPool 用の StorageGRID HA グループを作成する際のベストプラクティスは、次のワークロードによって異なります。

* プライマリワークロードのデータで FabricPool を使用する場合は、データの取得の中断を回避するために、ロードバランシングノードを少なくとも 2 つ含む HA グループを作成する必要があります。
* FabricPool の snapshot-only のボリューム階層化ポリシーまたは非プライマリのローカルのパフォーマンス階層（ディザスタリカバリ先や NetApp SnapMirror ® デスティネーションなど）を使用する予定の場合は、 1 つのノードだけで HA グループを設定できます。


ここでは、アクティブ / バックアップ HA の HA グループの設定（一方のノードがアクティブでもう一方のノードがバックアップ）について説明します。ただし、 DNS ラウンドロビンまたはアクティブ / アクティブ HA を使用することもできます。これらの他の HA 構成のメリットについては、を参照してください link:../admin/configuration-options-for-ha-groups.html["HA グループの設定オプション"]。
