---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: 以下に記載するシンプルなポリシーの例をベースに、独自の ILM ルールとポリシーを作成します。 
---
= FabricPool データ用の ILM ポリシーの例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下に記載するシンプルなポリシーの例をベースに、独自の ILM ルールとポリシーを作成します。

この例では、コロラド州デンバーの 1 つのデータセンターに 4 つのストレージノードがある StorageGRID システムの ILM ルールと ILM ポリシーを設計していることを前提としています。この例のFabricPool データは、というバケットを使用しています `fabricpool-bucket`。

[CAUTION]
====
以下の ILM ルールとポリシーは一例にすぎません。ILM ルールを設定する方法は多数あります。新しいポリシーをアクティブ化する前に、ドラフトポリシーをシミュレートして、コンテンツの損失を防ぐためにドラフトポリシーが想定どおりに機能することを確認してください。

詳細については、以下をご覧ください。 link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

====
.手順
. *Den という名前のストレージプールを作成します。Denver サイトを選択します。
. 2 plus 1 * という名前のイレイジャーコーディングプロファイルを作成します。2+1 イレイジャーコーディングスキームと *Den * ストレージプールを選択します。
. のデータにのみ適用されるILMルールを作成します `fabricpool-bucket`。次のルール例では、イレイジャーコーディングコピーを作成します。
+
[cols="1a,1a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
FabricPool データ用の 2+1 のイレイジャーコーディング



 a| 
バケット名
 a| 
`fabricpool-bucket`

FabricPool テナントアカウントでフィルタリングすることもできます。



 a| 
高度なフィルタリング
 a| 
オブジェクトサイズ（ MB ）が 0.2 MB を超えています。

* 注： * FabricPool は 4MB のオブジェクトのみを書き込みますが、このルールではイレイジャーコーディングを使用するため、オブジェクトサイズフィルタを追加する必要があります。



 a| 
参照時間
 a| 
取り込み時間



 a| 
配置
 a| 
0 日目のストアから永遠に



 a| 
を入力します
 a| 
イレイジャーコーディング



 a| 
場所
 a| 
デン (2 プラス 1)



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. 最初のルールに一致しないオブジェクトのレプリケートコピーを 2 つ作成する ILM ルールを作成します。基本フィルタ（テナントアカウントまたはバケット名）や高度なフィルタは選択しないでください。
+
[cols="1a,1a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2 つのレプリケートコピー



 a| 
バケット名
 a| 
_ なし _



 a| 
高度なフィルタリング
 a| 
_ なし _



 a| 
参照時間
 a| 
取り込み時間



 a| 
配置
 a| 
0 日目のストアから永遠に



 a| 
を入力します
 a| 
レプリケート



 a| 
場所
 a| 
デン



 a| 
コピー
 a| 
2.



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. ドラフトの ILM ポリシーを作成して 2 つのルールを選択レプリケーションルールではフィルタを使用しないため、ポリシーのデフォルト（最後の）ルールを使用できます。
. テストオブジェクトをグリッドに取り込みます。
. ポリシーをテストオブジェクトでシミュレートして動作を確認します。
. ポリシーをアクティブ化する。


このポリシーをアクティブ化すると、 StorageGRID はオブジェクトデータを次のように配置します。

* のFabricPool から階層化されたデータ `fabricpool-bucket` 2+1イレイジャーコーディングスキームを使用してイレイジャーコーディングされます。2 つのデータフラグメントと 1 つのパリティフラグメントが 3 つの異なるストレージノードに配置されます。
* 他のすべてのバケット内のオブジェクトがレプリケートされます。2 つのコピーが作成され、 2 つの異なるストレージノードに配置されます。
* イレイジャーコーディングコピーとレプリケートコピーは、 S3 クライアントによって削除されるまで StorageGRID に保持されます。StorageGRID ILM によってこれらの項目が削除されることはありません。

