---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: FabricPool を使用して StorageGRID にデータを階層化する場合は、 StorageGRID 情報ライフサイクル管理（ ILM ）ルールおよび FabricPool データを管理するための ILM ポリシーの作成に関する要件を理解しておく必要があります。FabricPool データに適用される ILM ルールがシステム停止を伴わないようにする必要があります。 
---
= StorageGRID の情報ライフサイクル管理とFabricPool のデータを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool を使用して StorageGRID にデータを階層化する場合は、 StorageGRID 情報ライフサイクル管理（ ILM ）ルールの作成要件と、 FabricPool データを管理するための ILM ポリシーの作成要件を理解しておく必要があります。FabricPool データに適用される ILM ルールがシステム停止を伴わないようにする必要があります。

[IMPORTANT]
====
FabricPool は、 StorageGRID の ILM ルールやポリシーを認識しません。StorageGRID の ILM ポリシーの設定ミスが原因でデータが失われる可能性があります。

詳細については、以下をご覧ください。 link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

====


== FabricPool データに関するILMのガイドライン

以下のガイドラインを確認し、 ILM ルールと ILM ポリシーが FabricPool データとビジネス要件に適していることを確認してください。すでに StorageGRID ILM を使用している場合は、次のガイドラインに従って、アクティブな ILM ポリシーの更新が必要になることがあります。

* レプリケーションルールとイレイジャーコーディングルールを任意に組み合わせて、クラウド階層のデータを保護できます。
+
コスト効率に優れたデータ保護を実現するために、サイト内で 2+1 のイレイジャーコーディングを使用することを推奨します。イレイジャーコーディングは、レプリケーションよりも多くのCPUを使用しますが、ストレージ容量は大幅に少なくなります。4+1スキームと6+1スキームは2+1よりも少ない容量を使用しますが、グリッド拡張時にストレージノードを追加する場合にスループットが低下し、柔軟性が低下します。

* FabricPool データに適用するルールは、イレイジャーコーディングを使用するか、少なくとも 2 つのレプリケートコピーを作成する必要があります。
+

IMPORTANT: ある期間にレプリケートコピーを 1 つしか作成しない ILM ルールには、データが永続的に失われるリスクがあります。オブジェクトのレプリケートコピーが 1 つしかない場合、ストレージノードに障害が発生したり、重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス作業中は、オブジェクトへのアクセスが一時的に失われます。

* FabricPool クラウド階層のデータが期限切れになる、または削除される ILM ルールは使用しないでください。StorageGRID ILM によって FabricPool オブジェクトが削除されないように、各 ILM ルールの保持期間を「 forever 」に設定します。
* FabricPool クラウド階層のデータをバケットから別の場所に移動するルールは作成しないでください。ILMルールを使用して、アーカイブノードを使用してFabricPool データをテープにアーカイブしたり、クラウドストレージプールを使用してFabricPool データをGlacierに移動したりすることはできません。
+

NOTE: クラウドストレージプールターゲットからオブジェクトを読み出すレイテンシが増加しているため、 FabricPool でクラウドストレージプールを使用することはサポートされていません。

* ONTAP 9.8 以降では、オプションでオブジェクトタグを作成して階層化データを分類およびソートし、管理を容易にすることができます。たとえば、タグを設定できるのは、 StorageGRID に接続されている FabricPool ボリュームのみです。次に、 StorageGRID で ILM ルールを作成する際に、高度なフィルタ「オブジェクトタグ」を使用してこのデータを選択し、配置します。

